### ISSUE TITLE
Problem with search using elastic search

### ISSUE THREAD

**Issue by zmwas** [mirumee/saleor#1015]
I am trying to run the demo and I get NotFoundError: TransportError(404, u'index_not_found_exception', u'no such index')
Here is the stack trace:
```
Traceback (most recent call last):
  File "/home/zack/.environments/sports/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/zack/.environments/sports/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/zack/.environments/sports/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zack/.environments/sports/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zack/sportsnstuff/sportsnstuff/saleor/search/views.py", line 29, in search
    results = list(results)
  File "/home/zack/sportsnstuff/sportsnstuff/saleor/product/utils.py", line 57, in products_with_availability
    for product in products:
  File "/home/zack/sportsnstuff/sportsnstuff/saleor/search/backends/base.py", line 181, in __iter__
    return iter(self.results())
  File "/home/zack/sportsnstuff/sportsnstuff/saleor/search/backends/base.py", line 147, in results
    self._results_cache = self._do_search()
  File "/home/zack/sportsnstuff/sportsnstuff/saleor/search/backends/elasticsearch.py", line 447, in _do_search
    hits = self.backend.es.search(**params)
  File "/home/zack/.environments/sports/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/zack/.environments/sports/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 539, in search
    doc_type, '_search'), params=params, body=body)
  File "/home/zack/.environments/sports/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/zack/.environments/sports/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 110, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/zack/.environments/sports/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 114, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
NotFoundError: TransportError(404, u'index_not_found_exception', u'no such index')
```

Am I supposed to add any code to make the demo search for goods?

**Comment by MadHamza** [comment]
You should run the command that creates the updates the search index for you
python manage.py update_index
