### ISSUE TITLE
Issue deploying on Heroku

### ISSUE THREAD

**Issue by nguyentrantuan** [mirumee/saleor#1037]
Hi, I'm new to SaleOr and ran into problems deploying on Heroku while I kept all the settings at default.

What did I do wrong?

The error log as follow:

```

> Traceback (most recent call last):
>          File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2813, in _dep_map
>            return self.__dep_map
>          File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2624, in __getattr__
>            raise AttributeError(attr)
>        AttributeError: _DistInfoDistribution__dep_map
>        
>        During handling of the above exception, another exception occurred:
>        
>        Traceback (most recent call last):
>          File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2804, in _parsed_pkg_info
>            return self._pkg_info
>          File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2624, in __getattr__
>            raise AttributeError(attr)
>        AttributeError: _pkg_info
>        
>        During handling of the above exception, another exception occurred:
>        
>        Traceback (most recent call last):
>          File "/app/.heroku/python/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
>            status = self.run(options, args)
>          File "/app/.heroku/python/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
>            prefix=options.prefix_path,
>          File "/app/.heroku/python/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
>            **kwargs
>          File "/app/.heroku/python/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
>            self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
>          File "/app/.heroku/python/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
>            isolated=self.isolated,
>          File "/app/.heroku/python/lib/python3.5/site-packages/pip/wheel.py", line 247, in move_wheel_files
>            prefix=prefix,
>          File "/app/.heroku/python/lib/python3.5/site-packages/pip/locations.py", line 140, in distutils_scheme
>            d = Distribution(dist_args)
>          File "/app/.heroku/python/lib/python3.5/site-packages/setuptools/dist.py", line 321, in __init__
>            _Distribution.__init__(self, attrs)
>          File "/app/.heroku/python/lib/python3.5/distutils/dist.py", line 281, in __init__
>            self.finalize_options()
>          File "/app/.heroku/python/lib/python3.5/site-packages/setuptools/dist.py", line 389, in finalize_options
>            ep.require(installer=self.fetch_build_egg)
>          File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in require
>            items = working_set.resolve(reqs, env, installer, extras=self.extras)
>          File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 862, in resolve
>            new_requirements = dist.requires(req.extras)[::-1]
>          File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2568, in requires
>            dm = self._dep_map
>          File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2815, in _dep_map
>            self.__dep_map = self._compute_dependencies()
>          File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2824, in _compute_dependencies
>            for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
>          File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2806, in _parsed_pkg_info
>            metadata = self.get_metadata(self.PKG_INFO)
>          File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata
>            value = self._get(self._fn(self.egg_info, name))
>          File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1577, in _get
>            with open(path, 'rb') as stream:
>        FileNotFoundError: [Errno 2] No such file or directory: '/tmp/build_b6a6e372e0b5346cc9f63736d02d4e30/mirumee-saleor-ac8e8ec/.heroku/python/lib/python3.5/site-packages/appdirs-1.4.3.dist-info/METADATA'
>  !     Push rejected, failed to compile Python app.
>  !     Push failed

```

**Comment by abispo** [comment]
I get the same error using the docker way to install in my local machine.

**Comment by Daviey** [comment]
@abispo Are you sure it is the same issue?  I am seeing something different, on Docker I am seeing:
```
Installing collected packages: appdirs, pytz, babel, babeldjango, docutils, python-dateutil, jmespath, botocore, s3transfer, boto3, requests, braintree, pycparser, cffi, idna, pyasn1, cryptography, cssselect, cssutils, dj-database-url, dj-email-url, django, django-absolute, django-bootstrap3, django-cache-url, django-countries, lxml, premailer, django-emailit, django-materializecss-form, django-mptt, pyjwt, stripe, suds-jurko, xmltodict, django-payments, prices, django-prices, django-prices-openexchangerates, redis, django-redis, django-storages, pillow, django-versatileimagefield, django-webpack-loader, djangorestframework, urllib3, elasticsearch, faker, google-i18n-address, google-measurement-protocol, typing, promise, graphql-core, graphql-relay, graphene, iso8601, singledispatch, graphene-django, jsonfield, markdown, maxminddb, maxminddb-geolite2, pbr, mock, oauthlib, psycopg2, purl, py, pyparsing, pytest, pytest-django, requests-oauthlib, satchless, defusedxml, python3-openid, social-auth-core, social-auth-app-django, text-unidecode, uwsgi
  Found existing installation: appdirs 1.4.3
    Uninstalling appdirs-1.4.3:
      Successfully uninstalled appdirs-1.4.3
  Rolling back uninstall of appdirs
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2813, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2624, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2804, in _parsed_pkg_info
    return self._pkg_info
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2624, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python3.5/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 321, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/local/lib/python3.5/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 389, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 862, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2568, in requires
    dm = self._dep_map
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2815, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2824, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2806, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1577, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/site-packages/appdirs-1.4.3.dist-info/METADATA'
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install -r /app/requirements.txt' returned a non-zero code: 2
```

**Comment by rlimaeco** [comment]
I had this kind of problem in docker compose in my localhost
The problem is the module appdirs that fails to build in current time of pip install -r requeriments
Change the Dockerfile to something like:

ADD requirements.txt /app/
RUN pip install appdirs --upgrade
RUN pip install -r /app/requirements.txt --upgrade

**Comment by patrys** [comment]
Everything should work now. We've updated all of the troublesome dependencies.
