### ISSUE TITLE
'yarn run build-assets' fails

### ISSUE THREAD

**Issue by Akramz** [mirumee/saleor#1064]
Config : 

OS : Ubuntu 16.04 (From AWS EC2)
Node : v8.1.2
npm : v2.15.11
yarn : 0.27.5

The error : 
```
yarn run v0.27.5
$ node ./node_modules/webpack/bin/webpack.js -p
ModuleBuildError: Module build failed: Error: Command failed: /home/ubuntu/Rackets_shop/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /home/ubuntu/Rackets_shop/node_modules/svg2png/lib/converter.js {"height":128,"width":128}
/home/ubuntu/Rackets_shop/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory

    at ChildProcess.exithandler (child_process.js:200:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:862:16)
    at Socket.<anonymous> (internal/child_process.js:338:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:490:12)
    at DependenciesBlock.onModuleBuildFailed (/home/ubuntu/Rackets_shop/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/home/ubuntu/Rackets_shop/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /home/ubuntu/Rackets_shop/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/ubuntu/Rackets_shop/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /home/ubuntu/Rackets_shop/node_modules/favicons-webpack-plugin/lib/favicons.js:32:23
    at /home/ubuntu/Rackets_shop/node_modules/favicons-webpack-plugin/lib/favicons.js:56:21
    at /home/ubuntu/Rackets_shop/node_modules/favicons/es5.js:193:28
    at /home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:52:16
    at /home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:696:30
    at /home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:167:37
    at /home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:1209:30
    at /home/ubuntu/Rackets_shop/node_modules/favicons/es5.js:143:24
    at /home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:52:16
    at done (/home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:241:17)
    at /home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/Rackets_shop/node_modules/favicons/es5.js:137:25
    at /home/ubuntu/Rackets_shop/node_modules/favicons/es5.js:122:24
    at /home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:726:13
    at /home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:52:16
    at done (/home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:241:17)
    at /home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:723:17
    at /home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:167:37
    at /home/ubuntu/Rackets_shop/node_modules/favicons/es5.js:110:24
    at /home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:52:16
    at done (/home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:241:17)
    at /home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/Rackets_shop/node_modules/favicons/es5.js:107:28
    at /home/ubuntu/Rackets_shop/node_modules/favicons/es5.js:72:32
    at /home/ubuntu/Rackets_shop/node_modules/async/lib/async.js:52:16
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Any hint would be much appreciated.

Thank you.

**Comment by polkolins** [comment]
It's about dependency in Phantom.js. Try to install libfontconfig **sudo apt-get install libfontconfig** and look into this issue https://github.com/ariya/phantomjs/issues/10904

**Comment by nikitashalnov** [comment]
Roger that, increasing the RAM helps me to finish the build.

**Comment by deathping1994** [comment]
@polkolins, I tried installing libfontconfig on ubuntu 16.04 but it install libfontconfig1. And I continue to get the same error. Any other suggestions to fix it ?

`Note, selecting 'libfontconfig1' instead of 'libfontconfig'
libfontconfig1 is already the newest version (2.11.94-0ubuntu1.1).`

```` yarn run v1.3.2
$ node ./node_modules/webpack/bin/webpack.js -p
Error: Module build failed: Error: Command failed: /home/ubuntu/saleor/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /home/ubuntu/saleor/node_modules/svg2png/lib/converter.js {"height":1294,"width":750}

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
    at Object.eval (eval at <anonymous> (/home/ubuntu/saleor/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22), <anonymous>:70:7)
    at __webpack_require__ (eval at <anonymous> (/home/ubuntu/saleor/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22), <anonymous>:20:30)
    at eval (eval at <anonymous> (/home/ubuntu/saleor/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22), <anonymous>:63:18)
    at eval (eval at <anonymous> (/home/ubuntu/saleor/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22), <anonymous>:66:10)
    at Compilation.<anonymous> (/home/ubuntu/saleor/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22)
    at next (/home/ubuntu/saleor/node_modules/webpack/node_modules/tapable/lib/Tapable.js:204:14)
````

**Comment by resourceldg** [comment]
@deathping1994 can you solve it?
