### ISSUE TITLE
yarn run build-assets fails

### ISSUE THREAD

**Issue by sergey-pshichenko** [mirumee/saleor#1076]
I looked at other reported issues but this looks like a different error. 

I'm using Ubuntu 16.04 on Digital Ocean.
Also, I already tried increasing virtual memory to 4GB and installing libfontconfig.

```
internal/child_process.js:294
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:294:26)
    at exports.spawn (child_process.js:369:9)
    at Object.exports.execFile (child_process.js:137:15)
    at Object.execFile (/var/www/saleor/node_modules/pn/_promisify.js:35:27)
    at module.exports (/var/www/saleor/node_modules/svg2png/lib/svg2png.js:11:29)
    at Object.nearest (/var/www/saleor/node_modules/favicons/helpers-es5.js:276:25)
    at /var/www/saleor/node_modules/favicons/es5.js:58:41
    at fn (/var/www/saleor/node_modules/async/lib/async.js:746:34)
    at /var/www/saleor/node_modules/async/lib/async.js:1213:16
    at /var/www/saleor/node_modules/async/lib/async.js:166:37
    at /var/www/saleor/node_modules/async/lib/async.js:706:43
    at /var/www/saleor/node_modules/async/lib/async.js:167:37
    at Object.async.waterfall (/var/www/saleor/node_modules/async/lib/async.js:710:44)
    at /var/www/saleor/node_modules/favicons/es5.js:57:27
    at createFavicon (/var/www/saleor/node_modules/favicons/es5.js:74:19)
    at /var/www/saleor/node_modules/favicons/es5.js:106:24
    at Object.async.forEachOf.async.eachOf (/var/www/saleor/node_modules/async/lib/async.js:233:13)
    at createFavicons (/var/www/saleor/node_modules/favicons/es5.js:105:19)
    at /var/www/saleor/node_modules/favicons/es5.js:116:24
    at /var/www/saleor/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/var/www/saleor/node_modules/async/lib/async.js:233:13)
    at _parallel (/var/www/saleor/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/var/www/saleor/node_modules/async/lib/async.js:731:9)
    at createPlatform (/var/www/saleor/node_modules/favicons/es5.js:115:19)
    at /var/www/saleor/node_modules/favicons/es5.js:133:21
    at Object.async.forEachOf.async.eachOf (/var/www/saleor/node_modules/async/lib/async.js:233:13)
    at createOffline (/var/www/saleor/node_modules/favicons/es5.js:129:19)
    at create (/var/www/saleor/node_modules/favicons/es5.js:176:90)
    at /var/www/saleor/node_modules/favicons/es5.js:182:20
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fkonigy** [comment]
@sergey-pshichenko 
please take a look at the installation manual [here](https://saleor.readthedocs.io/en/latest/installation.html#installation)
I installed it on Ubuntu 16.04 without problem.

**Comment by arkilis** [comment]
Same issue here. Ubuntu 16.04

**Comment by rlimaeco** [comment]
Which version of nodejs and yarn is installed ? Did you try to delete the node_modules directory ?

**Comment by arkilis** [comment]
@richlloydmiles tried to delete `node_modules ` but not working either.

**Comment by richlloydmiles** [comment]
@arkilis I don't think you meant to tag me in this?

**Comment by rlimaeco** [comment]
@arkilis you should say the yarn and nodejs versions, without that it's a shoot in the dark  heeheh

**Comment by DonerKebab** [comment]
Yo, anybody solved this issue? I had same problem, my node version is v6.11.3 and yarn version is v0.20.3.

**Comment by DonerKebab** [comment]
Ok, after few hours google i knew that it related to phantomjs. Follow these step to solve this issue:
1. cd to: ./node_modules/phantomjs-prebuilt
2. run: node install.js

**Comment by elwoodxblues** [comment]
FYI we've recently switched to NPM. Having the latest NPM and Node versions you should be able to install the frontend assets without any problems.
