### ISSUE TITLE
How to change default currency?

### ISSUE THREAD

**Issue by chulaihunde** [mirumee/saleor#1091]
edit setting file:

DEFAULT_COUNTRY = 'CN' #'US'
DEFAULT_CURRENCY = 'CNY' #'CNH' #'USD'

when click orders #18 in dashboard:

[23/Aug/2017 10:19:35] "GET /jsi18n/ HTTP/1.1" 200 3331
Internal Server Error: /dashboard/orders/18/
Traceback (most recent call last):
  File "/home/long/wagtailTranslation/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/long/wagtailTranslation/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/long/wagtailTranslation/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/long/wagtailTranslation/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/long/wagtailTranslation/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/long/wagtailTranslation/saleor-master/saleor/dashboard/order/views.py", line 65, in order_details
    balance = captured - order.get_total()
  File "/home/long/wagtailTranslation/local/lib/python2.7/site-packages/prices/__init__.py", line 138, in __sub__
    (other.currency, self.currency))
ValueError: Cannot subtract prices in u'CNY' from u'USD'
[23/Aug/2017 10:20:06] "GET /dashboard/orders/18/ HTTP/1.1" 500 102609

**Comment by Hisagr** [comment]
When you change default currency, you need to delete all orders with the old default currency to make this work.
