### ISSUE TITLE
Struggling to install due to "could not open hstore.control"

### ISSUE THREAD

**Issue by soydemadrid** [mirumee/saleor#1156]
Hi can anyone help. I can't seem to get past installation step 4 in the documentation on Ubuntu 16.04 LTS.

I've installed the virtualenv, ran the install requirements.txt and export SECRET_KEY etc.

Then on python manage.py migrate I get this error:

```
  Applying product.0021_add_hstore_extension...Traceback (most recent call last):
  File "/home/website/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: could not open extension control file "/usr/share/postgresql/9.3/extension/hstore.control": No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/website/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/website/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/website/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/website/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/website/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/website/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/website/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/website/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/website/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/website/lib/python3.5/site-packages/django/contrib/postgres/operations.py", line 17, in database_forwards
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS %s" % schema_editor.quote_name(self.name))
  File "/home/website/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/home/website/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/website/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/website/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/website/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/website/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: could not open extension control file "/usr/share/postgresql/9.3/extension/hstore.control": No such file or directory
```

On searching around I found that on Ubuntu you need to install postgresql-contrib too so I also did: sudo apt-get install postgresql postgresql-contrib

But that didn't help... Thanks again for any help getting Saleor up and running.

**Comment by elwoodxblues** [comment]
This looks like issue with your database configuration. You have to make sure that the HStore extension is installed correctly. I would recommend running the project in Docker as it doesn't require any manual database configuration.

**Comment by soydemadrid** [comment]
Hi thanks, I'm not sure how to set it up in Docker as I've followed this guide which doesn't mention Docker:
https://saleor.readthedocs.io/en/latest/installation.html#installation

I think I need to enable hstore in the database but I'm not sure how to do that?

I've installed postgresql-contrib as many suggest online but that doesn't help either...

Can I instead just use MySQL or does Saelor have to use postgresql?

Thanks for any further help.

**Comment by elwoodxblues** [comment]
Here is the part about Docker: [https://saleor.readthedocs.io/en/latest/development.html#docker](https://saleor.readthedocs.io/en/latest/development.html#docker). Postgres is required and only supported database as we use some of it's specific features (like hstore) in Saleor.

**Comment by soydemadrid** [comment]
Hi thanks, do I just follow that docker guide from within the virtualenv where I've downloaded saelor etc, or do I come out of that and do this separately somewhere else? Thanks again for the reply! Looking forward to using Saelor hopefully soon! :)

**Comment by elwoodxblues** [comment]
According to the above docs you'll have the whole environment created inside Docker, so you don't need any virtualenv on your local machine. You only have to make sure that you install docker and docker-compose on your computer. Also, if you have running Postgres database you have to stop it prior to running docker-compose to avoid port conflicts.

**Comment by soydemadrid** [comment]
Hi thanks - in the docs it almost seems like the Deployment section is for after you build your store? I can't even install Saleor to build the store... But I've tried the Docker steps now too to see if that helps but can't seem to run the first command:

> 
> sh-4.3$ ls
> app.json            Dockerfile  locale        Procfile         requirements.txt  setup.cfg  tox.ini
> circle.yml          docs        manage.py     README.md        runtime.txt       templates  webpack.config.js
> docker-compose.yml  LICENSE     package.json  requirements.in  saleor            tests      yarn.lock
> sh-4.3$ yarn run build-assets --production
> yarn run v1.1.0
> warning You are using Node "4.2.6" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
> $ node ./node_modules/webpack/bin/webpack.js -p "--production"
> error Couldn't find the binary node ./node_modules/webpack/bin/webpack.js -p "--production"
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> sh-4.3$

**Comment by elwoodxblues** [comment]
Hey @soydemadrid, were you able to resolve your issue? We have switched to NPM some time ago. Having the latest versions of NPM and Node should allow you to install everything smoothly.

**Comment by davnustratbac** [comment]
It appears the hstore extensions should be available in the contrib packages 
https://askubuntu.com/questions/354686/postgres-doesnt-have-hstore-extension

**Comment by Pacu2** [comment]
For the reference, the issue could be resolved by installing contrib packages
`apt install postgresql-contrib-9.5`
