### ISSUE TITLE
No module named parse

### ISSUE THREAD

**Issue by raybesiga** [mirumee/saleor#1495]
Following the installation guide for Saleor in a virtualenv with Python 2.7. When I run the `python manage.py migrate` command. I get the following error:

```bash 
(saleor)➜  saleor git:(master) ✗ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/raybesiga/.virtualenvs/saleor/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/raybesiga/.virtualenvs/saleor/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/raybesiga/.virtualenvs/saleor/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/raybesiga/.virtualenvs/saleor/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/raybesiga/.virtualenvs/saleor/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/raybesiga/Projects/saleor/saleor/discount/models.py", line 14, in <module>
    from ..cart.utils import (
  File "/Users/raybesiga/Projects/saleor/saleor/cart/utils.py", line 15, in <module>
    from ..core.utils import to_local_currency
  File "/Users/raybesiga/Projects/saleor/saleor/core/utils/__init__.py", line 6, in <module>
    from urllib.parse import urljoin
ImportError: No module named parse
(saleor)➜  saleor git:(master) ✗
```

My pip installation is successful and when i run `pip freeze` the result is as below

```bash
(saleor)➜  saleor git:(master) ✗ pip freeze
amqp==2.2.2
asn1crypto==0.22.0
Babel==2.5.1
BabelDjango==0.2.2
billiard==3.5.0.3
boto==2.38.0
boto3==1.4.8
botocore==1.8.1
braintree==3.37.2
cairocffi==0.8.0
CairoSVG==1.0.22
celery==4.1.0
certifi==2017.7.27.1
cffi==1.10.0
chardet==3.0.4
contextlib2==0.5.5
cryptography==2.0.3
cssselect==0.9.1
cssselect2==0.2.1
cssutils==1.0
defusedxml==0.5.0
dj-database-url==0.4.2
dj-email-url==0.0.10
Django==1.11.5
django-absolute==0.3
django-babel==0.6.1
django-bootstrap3==9.0.0
django-cache-url==1.3.1
django-celery-results==1.0.1
django-countries==4.6.1
django-elasticsearch-dsl==0.4.1
django-emailit==0.2.2
django-filter==1.0.4
django-impersonate==1.1
django-model-utils==2.0.3
django-mptt==0.8.7
django-offsite-storage==0.0.5
django-payments==0.12.1
django-phonenumber-field==1.3.0
django-prices==0.7.0
django-prices-openexchangerates==0.1.15
django-redis==4.8.0
django-render-block==0.5
django-selectable==0.8.0
django-storages==1.6.5
django-templated-email==2.2.0
django-versatileimagefield==1.7.1
django-webpack-loader==0.5.0
dnspython==1.15.0
docutils==0.14
elasticsearch==5.5.1
elasticsearch-dsl==5.3.0
email-validator==1.0.2
enum34==1.1.6
fake-factory==0.5.2
Faker==0.8.3
freezegun==0.3.9
funcsigs==1.0.2
futures==3.2.0
google-i18n-address==2.0.3
google-measurement-protocol==0.1.6
graphene==2.0.1
graphene-django==2.0.0
graphql-core==2.0
graphql-relay==0.4.5
html5lib==0.999999999
idna==2.6
ipaddress==1.0.19
iso8601==0.1.12
jmespath==0.9.3
jsonfield==2.0.2
kombu==4.1.0
lxml==3.4.4
Markdown==2.6.9
maxminddb==1.3.0
maxminddb-geolite2==2017.803
mock==2.0.0
oauthlib==2.0.4
olefile==0.44
pbr==3.1.1
pdfrw==0.4
phonenumberslite==8.8.5
Pillow==4.0.0
premailer==2.9.2
prices==0.5.9
promise==2.1
psycopg2==2.7.3.1
purl==1.3.1
py==1.4.34
pycparser==2.18
pycrypto==2.6.1
PyJWT==1.5.3
Pyphen==0.9.4
pytest==3.2.2
pytest-django==3.1.2
pytest-mock==1.6.3
pytest-vcr==0.3.0
python-dateutil==2.6.1
python-openid==2.2.5
python3-openid==3.1.0
pytz==2017.2
PyYAML==3.12
redis==2.10.6
requests==2.18.4
requests-oauthlib==0.8.0
Rx==1.6.0
s3transfer==0.1.10
saleor==0.1.0a0
satchless==1.1.3
singledispatch==3.4.0.3
six==1.11.0
social-auth-app-django==2.0.0
social-auth-core==1.4.0
stripe==1.65.0
suds-jurko==0.6
text-unidecode==1.0
tinycss2==0.6.1
typing==3.6.2
Unidecode==0.4.18
urllib3==1.21.1
uWSGI==2.0.15
vcrpy==1.10.3
vine==1.1.4
WeasyPrint==0.41
webencodings==0.5.1
wrapt==1.10.11
xmltodict==0.11.0
(saleor)➜  saleor git:(master) ✗
```

I have followed the guide to the letter so I am wondering why this error arises?

**Comment by raybesiga** [comment]
Whoa. Thanks @dotslash227. Let me read up on how to migrate my project to Python 3. Is there a separate installation manual for Python 3 projects?

**Comment by dominik-zeglen** [comment]
You can run commands with `python3` instead of `python`, eg. `python3 manage.py migrate`. Another way of running Saleor (in python3) is to use Docker - here's link if you're interested: https://saleor.readthedocs.io/en/latest/development.html#docker

**Comment by raybesiga** [comment]
Thanks @dominik-zeglen So i take it that I install Python 3, create a new virtualenv that uses Python3 and follow all of the same commands, correct?

**Comment by patrys** [comment]
@raybesiga Yes, the commands don't differ between Python 2 and 3.

**Comment by dotslash227** [comment]
If you are running Linux/Mac, chances are that you already have Python 3 installed on your system, just use python3 manage.py instead of python manage.py

If you are on Windows, you need to install Python 3 for Windows seperately and set up environment variables for python3 to be able to use python2 and python3 simultaneously, or else you can remove python2 from your system.

I would recommend completely switching to Python 3 from Python 2 if you are totally into Django Development because the new Django 2.0 has dropped support for Python2. 

Anyway, the commands for running Saleor on python2 and python3 are same, the official saleor documentation, although contains a typo that it support both python 2 and 3, is meant only for python 3. I was able to figure that out by reading the commit messages in the official repo in many files, as it said "drop python2 support".

PS: You can create a new virtualenv for python3 by this command: python3 -m virtualenv env.

**Comment by raybesiga** [comment]
hey guys, 

So I installed Python3, virtualenv and virtualenvwrapper as per this [gist I wrote](https://gist.github.com/raybesiga/56f413d20083ee6b9cbbdc2836448238).

I installed the requirements for my Python3 environment

```bash 
(marketplace) ➜  saleor git:(master) ✗ pip3 install -r requirements.txt
Requirement already satisfied: amqp==2.2.2 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: asn1crypto==0.22.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: babel==2.5.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: billiard==3.5.0.3 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: boto3==1.4.8 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied: botocore==1.8.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied: braintree==3.37.2 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 13))
Requirement already satisfied: cairocffi==0.8.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 14))
Requirement already satisfied: cairosvg==1.0.22 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 15))
Requirement already satisfied: celery[redis]==4.1.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 16))
Requirement already satisfied: certifi==2017.7.27.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 17))
Requirement already satisfied: cffi==1.10.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 18))
Requirement already satisfied: chardet==3.0.4 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 19))
Requirement already satisfied: cryptography==2.0.3 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 20))
Requirement already satisfied: cssselect2==0.2.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 21))
Requirement already satisfied: defusedxml==0.5.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 22))
Requirement already satisfied: dj-database-url==0.4.2 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 23))
Requirement already satisfied: dj-email-url==0.0.10 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 24))
Requirement already satisfied: django-babel==0.6.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 25))
Requirement already satisfied: django-bootstrap3==9.0.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 26))
Requirement already satisfied: django-cache-url==1.3.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 27))
Requirement already satisfied: django-celery-results==1.0.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 28))
Requirement already satisfied: django-countries==4.6.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 29))
Requirement already satisfied: django-elasticsearch-dsl==0.4.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 30))
Requirement already satisfied: django-filter==1.0.4 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 31))
Requirement already satisfied: django-impersonate==1.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 32))
Requirement already satisfied: django-mptt==0.8.7 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 33))
Requirement already satisfied: django-payments==0.12.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 34))
Requirement already satisfied: django-phonenumber-field==1.3.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 35))
Requirement already satisfied: django-prices-openexchangerates==0.1.15 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 36))
Requirement already satisfied: django-prices==0.7.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 37))
Requirement already satisfied: django-redis==4.8.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 38))
Requirement already satisfied: django-render-block==0.5 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 39))
Requirement already satisfied: django-storages==1.6.5 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 40))
Requirement already satisfied: django-templated-email==2.2.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 41))
Requirement already satisfied: django-versatileimagefield==1.7.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 42))
Requirement already satisfied: django-webpack-loader==0.5.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 43))
Requirement already satisfied: django==1.11.5 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 44))
Requirement already satisfied: dnspython==1.15.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 45))
Requirement already satisfied: docutils==0.14 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 46))
Requirement already satisfied: elasticsearch-dsl==5.3.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 47))
Requirement already satisfied: elasticsearch==5.5.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 48))
Requirement already satisfied: email-validator==1.0.2 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 49))
Requirement already satisfied: faker==0.8.3 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 50))
Requirement already satisfied: freezegun==0.3.9 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 51))
Requirement already satisfied: google-i18n-address==2.0.3 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 52))
Requirement already satisfied: google-measurement-protocol==0.1.6 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 53))
Requirement already satisfied: graphene-django==2.0.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 54))
Requirement already satisfied: graphene==2.0.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 55))
Requirement already satisfied: graphql-core==2.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 56))
Requirement already satisfied: graphql-relay==0.4.5 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 57))
Requirement already satisfied: html5lib==0.999999999 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 58))
Requirement already satisfied: idna==2.6 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 59))
Requirement already satisfied: iso8601==0.1.12 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 60))
Requirement already satisfied: jmespath==0.9.3 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 61))
Requirement already satisfied: jsonfield==2.0.2 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 62))
Requirement already satisfied: kombu==4.1.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 63))
Requirement already satisfied: markdown==2.6.9 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 64))
Requirement already satisfied: maxminddb-geolite2==2017.803 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 65))
Requirement already satisfied: maxminddb==1.3.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 66))
Requirement already satisfied: oauthlib==2.0.4 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 67))
Requirement already satisfied: olefile==0.44 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 68))
Requirement already satisfied: pdfrw==0.4 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 69))
Requirement already satisfied: phonenumberslite==8.8.5 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 70))
Requirement already satisfied: pillow==4.0.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 71))
Requirement already satisfied: prices==0.5.9 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 72))
Requirement already satisfied: promise==2.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 73))
Requirement already satisfied: psycopg2==2.7.3.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 74))
Requirement already satisfied: purl==1.3.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 75))
Requirement already satisfied: py==1.4.34 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 76))
Requirement already satisfied: pycparser==2.18 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 77))
Requirement already satisfied: pyjwt==1.5.3 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 78))
Requirement already satisfied: pyphen==0.9.4 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 79))
Requirement already satisfied: pytest-django==3.1.2 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 80))
Requirement already satisfied: pytest-mock==1.6.3 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 81))
Requirement already satisfied: pytest-vcr==0.3.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 82))
Requirement already satisfied: pytest==3.2.2 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 83))
Requirement already satisfied: python-dateutil==2.6.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 84))
Requirement already satisfied: python3-openid==3.1.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 85))
Requirement already satisfied: pytz==2017.2 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 86))
Requirement already satisfied: pyyaml==3.12 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 87))
Requirement already satisfied: redis==2.10.6 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 88))
Requirement already satisfied: requests-oauthlib==0.8.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 89))
Requirement already satisfied: requests==2.18.4 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 90))
Requirement already satisfied: rx==1.6.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 91))
Requirement already satisfied: s3transfer==0.1.10 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 92))
Requirement already satisfied: satchless==1.1.3 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 93))
Requirement already satisfied: singledispatch==3.4.0.3 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 94))
Requirement already satisfied: six==1.11.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 95))
Requirement already satisfied: social-auth-app-django==2.0.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 96))
Requirement already satisfied: social-auth-core==1.4.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 97))
Merge branch 'master' of https://github.com/mirumee/saleor
Requirement already satisfied: stripe==1.65.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 98))
Requirement already satisfied: suds-jurko==0.6 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 99))
Requirement already satisfied: text-unidecode==1.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 100))
Requirement already satisfied: tinycss2==0.6.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 101))
Requirement already satisfied: typing==3.6.2 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 102))
Requirement already satisfied: urllib3==1.21.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 103))
Requirement already satisfied: uwsgi==2.0.15 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 104))
Requirement already satisfied: vcrpy==1.10.3 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 105))
Requirement already satisfied: vine==1.1.4 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 106))
Requirement already satisfied: weasyprint==0.41 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 107))
Requirement already satisfied: webencodings==0.5.1 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 108))
Requirement already satisfied: wrapt==1.10.11 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 109))
Requirement already satisfied: xmltodict==0.11.0 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from -r requirements.txt (line 110))
Requirement already satisfied: setuptools>=18.5 in /Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages (from html5lib==0.999999999->-r requirements.txt (line 58))
```
However, when i run the migration, this is the output with Python3 as well.

```bash
(marketplace) ➜  saleor git:(master) ✗ python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/raybesiga/.virtualenvs/marketplace/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/raybesiga/Projects/saleor/saleor/discount/models.py", line 14, in <module>
    from ..cart.utils import (
  File "/Users/raybesiga/Projects/saleor/saleor/cart/utils.py", line 15, in <module>
    from ..core.utils import to_local_currency
  File "/Users/raybesiga/Projects/saleor/saleor/core/utils/__init__.py", line 5, in <module>
    from urlparse import urlparse
ModuleNotFoundError: No module named 'urlparse'
(marketplace) ➜  saleor git:(master) ✗
```
Something I am missing? @dotslash227 @dominik-zeglen @patrys

**Comment by dotslash227** [comment]
1. Remove your existing virtual environment
2. Create a new virtual environment using this command: python3 -m virtualenv env
3. Activate virtualenv: source env/bin/activate
4. pip install -r requirements.txt

The error you posted is basically python2 trying to run a python3 library.

**Comment by raybesiga** [comment]
Thanks @dotslash227 @dominik-zeglen @patrys I was able to resolve the error. Thanks for the amazing support.

**Comment by bastianhilton** [comment]
so the way i got my saleor install to work was py -3 manage.py migrate (using windows 10 command line) and it works, also setup your hash or that will incur another error message
