### ISSUE TITLE
SiteSettings Primary Key error

### ISSUE THREAD

**Issue by raybesiga** [mirumee/saleor#1519]
Hi guys

I get an error when i run `python manage.py migrate`

```bash
(handmade) ➜  saleor git:(master) ✗ python3 manage.py migrate
System check identified some issues:

WARNINGS:
saleor.W001: Session caching cannot work with locmem backend
	HINT: User sessions need to be globally shared, use a cache server like Redis.
Operations to perform:
  Apply all migrations: auth, cart, contenttypes, discount, django_celery_results, django_prices_openexchangerates, impersonate, order, product, sessions, shipping, site, sites, social_django, userprofile
Running migrations:
  Applying cart.0004_auto_20171129_1004... OK
  Applying discount.0006_auto_20171129_1004... OK
  Applying django_celery_results.0001_initial... OK
  Applying impersonate.0001_initial... OK
  Applying order.0019_auto_20171109_1423... OK
  Applying order.0020_auto_20171123_0609... OK
  Applying order.0021_auto_20171129_1004... OK
  Applying order.0022_auto_20171205_0428... OK
  Applying order.0023_auto_20171206_0506... OK
  Applying order.0024_remove_order_status... OK
  Applying order.0025_auto_20171214_1015... OK
  Applying order.0026_auto_20171218_0428... OK
  Applying product.0036_auto_20171115_0608... OK
  Applying product.0037_auto_20171124_0847... OK
  Applying product.0038_auto_20171129_0616... OK
  Applying product.0037_auto_20171129_1004... OK
  Applying product.0039_merge_20171130_0727... OK
  Applying product.0040_auto_20171205_0428... OK
  Applying product.0041_auto_20171205_0546... OK
  Applying product.0042_auto_20171206_0501... OK
  Applying product.0043_auto_20171207_0839... OK
  Applying shipping.0006_auto_20171109_0908... OK
  Applying shipping.0007_auto_20171129_1004... OK
  Applying site.0006_auto_20171025_0454... OK
  Applying site.0007_auto_20171027_0856...Traceback (most recent call last):
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
__fake__.DoesNotExist: SiteSettings matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "site_sitesettings_pkey"
DETAIL:  Key (id)=(1) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/raybesiga/Projects/saleor/saleor/site/migrations/0007_auto_20171027_0856.py", line 21, in link_to_sites
    defaults={'domain': site.domain, 'name': site.name})
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/models/query.py", line 506, in _create_object_from_params
    six.reraise(*exc_info)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/models/query.py", line 498, in _create_object_from_params
    obj = self.create(**params)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/raybesiga/Projects/saleor/handmade/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "site_sitesettings_pkey"
DETAIL:  Key (id)=(1) already exists.

(handmade) ➜  saleor git:(master) ✗
```
Should i delete the database and recreate it? I run `python manage.py migrate` before and got a urllib error so there should not be an issue. Please advise.

**Comment by elwoodxblues** [comment]
This migration tries to create a `SiteSettings` object corresponding to the `Site` from `django.contrib.sites`. In this case, you should be fine with recreating the database and running migrations again, but this migration shouldn't fail in such case. We'll have to check this.

**Comment by patrys** [comment]
I've seen this once and it was related to the PostgreSQL sequence not being updated so it tried to insert a second row while using PK equal to 1.

**Comment by patrys** [comment]
@raybesiga as a temporary workaround you could try to run:
```bash
manage.py dbshell
```

And then:
```sql
ALTER SEQUENCE site_sitesettings_id_seq RESTART WITH 2;
```

**Comment by raybesiga** [comment]
Thanks @patrys I decided to follow @elwoodxblues advice and create a new database. It is a weird case though..

**Comment by Pacu2** [comment]
I think this is resolved by now
