### ISSUE TITLE
Elastic search error

### ISSUE THREAD

**Issue by adrhem** [mirumee/saleor#1525]
Hi everyone, I am deploying a saleor version but when I am trying to test the search with elastic_search I get the folliwing error:

```
GET http://207.210.229.227:9200/storefront__product_product/_search?from=0&_source=pk [status:404 request:0.030s]
Internal Server Error: /search/
Traceback (most recent call last):
  File "/root/Env/dunes/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/Env/dunes/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/root/Env/dunes/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/Env/dunes/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/dunes/saleor/search/views.py", line 29, in search
    results = list(results)
  File "/root/dunes/saleor/product/utils.py", line 58, in products_with_availability
    for product in products:
  File "/root/dunes/saleor/search/backends/base.py", line 181, in __iter__
    return iter(self.results())
  File "/root/dunes/saleor/search/backends/base.py", line 147, in results
    self._results_cache = self._do_search()
  File "/root/dunes/saleor/search/backends/elasticsearch.py", line 447, in _do_search
    hits = self.backend.es.search(**params)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 623, in search
    doc_type, '_search'), params=params, body=body)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: <unprintable NotFoundError object>
GET http://207.210.229.227:9200/storefront__product_product/_search?size=21&_source=pk&from=0 [status:404 request:0.022s]
Traceback (most recent call last):
  File "/root/Env/dunes/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/Env/dunes/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/root/Env/dunes/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/Env/dunes/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/dunes/saleor/search/views.py", line 29, in search
    results = list(results)
  File "/root/dunes/saleor/product/utils.py", line 58, in products_with_availability
    for product in products:
  File "/root/dunes/saleor/search/backends/base.py", line 181, in __iter__
    return iter(self.results())
  File "/root/dunes/saleor/search/backends/base.py", line 147, in results
    self._results_cache = self._do_search()
  File "/root/dunes/saleor/search/backends/elasticsearch.py", line 447, in _do_search
    hits = self.backend.es.search(**params)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 623, in search
    doc_type, '_search'), params=params, body=body)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: <unprintable NotFoundError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Env/dunes/lib/python3.5/site-packages/django/template/defaultfilters.py", line 969, in pprint
    return pformat(value)
  File "/usr/lib/python3.5/pprint.py", line 58, in pformat
    compact=compact).pformat(object)
  File "/usr/lib/python3.5/pprint.py", line 144, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "/usr/lib/python3.5/pprint.py", line 161, in _format
    rep = self._repr(object, context, level)
  File "/usr/lib/python3.5/pprint.py", line 393, in _repr
    self._depth, level)
  File "/usr/lib/python3.5/pprint.py", line 405, in format
    return _safe_repr(object, context, maxlevels, level)
  File "/usr/lib/python3.5/pprint.py", line 555, in _safe_repr
    rep = repr(object)
  File "/root/dunes/saleor/search/backends/base.py", line 187, in __repr__
    data = list(self[:21])
  File "/root/dunes/saleor/search/backends/base.py", line 181, in __iter__
    return iter(self.results())
  File "/root/dunes/saleor/search/backends/base.py", line 147, in results
    self._results_cache = self._do_search()
  File "/root/dunes/saleor/search/backends/elasticsearch.py", line 447, in _do_search
    hits = self.backend.es.search(**params)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 623, in search
    doc_type, '_search'), params=params, body=body)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: <unprintable NotFoundError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/root/Env/dunes/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/root/dunes/saleor/wsgi/health_check.py", line 7, in health_check_wrapper
    return application(environ, start_response)
  File "/root/Env/dunes/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/root/Env/dunes/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/root/Env/dunes/lib/python3.5/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/root/Env/dunes/lib/python3.5/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/root/Env/dunes/lib/python3.5/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/root/Env/dunes/lib/python3.5/site-packages/django/views/debug.py", line 84, in technical_500_response
    html = reporter.get_traceback_html()
  File "/root/Env/dunes/lib/python3.5/site-packages/django/views/debug.py", line 327, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/root/Env/dunes/lib/python3.5/site-packages/django/views/debug.py", line 261, in get_traceback_data
    v = pprint(v)
  File "/root/Env/dunes/lib/python3.5/site-packages/django/template/defaultfilters.py", line 971, in pprint
    return "Error in formatting: %s: %s" % (e.__class__.__name__, force_text(e, errors="replace"))
  File "/root/Env/dunes/lib/python3.5/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/root/Env/dunes/lib/python3.5/site-packages/elasticsearch/exceptions.py", line 55, in __str__
    cause = ', %r' % self.info['error']['root_cause'][0]['reason']
```

Can you help me guys?

**Comment by elwoodxblues** [comment]
@salwator Do you have any ideas what could be the problem here?

**Comment by salwator** [comment]
@adrhem It looks like problem with connection to elasticsearch instance. Are you sure your ports are properly configured? Can we see your ES configuration in settings?

**Comment by elwoodxblues** [comment]
@adrhem Were you able to resolve this issue?

**Comment by elwoodxblues** [comment]
Closing due to no response. Please reopen if there are further questions.
