### ISSUE TITLE
object() takes no parameters 

### ISSUE THREAD

**Issue by kwatog** [mirumee/saleor#1533]
I recently merged 2 months worth of commits to my local copy. Obviously, it is a big update for me but still managed to do complete the migration(required superuser) and installed the latest requirements.txt. But when I tried to run the server, it crashed.

I'm running on the following environment:
OS : Windows
Python : 3.6
Django : 1.11.5 (as per req.txt)

### Steps to reproduce the problem
1. git fetch
2. git merge
3. pip install -r requirements.txt
4. python manage.py migrate

Unfortunately, I'm too newbie to understand the problem. I'm suspecting the problem started with the error below
>mw_instance = middleware(handler)
TypeError: object() takes no parameters

Take note that my instance is working perfectly fine before the update.

Here's the full stack trace.
> Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x07885E40>
Traceback (most recent call last):
  File "D:\django\shopenv\lib\site-packages\django\utils\autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "D:\django\shopenv\lib\site-packages\django\core\management\commands\runserver.py", line 147, in inner_run
    handler = self.get_handler(*args, **options)
  File "D:\django\shopenv\lib\site-packages\django\contrib\staticfiles\management\commands\runserver.py", line 28, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "D:\django\shopenv\lib\site-packages\django\core\management\commands\runserver.py", line 68, in get_handler
    return get_internal_wsgi_application()
  File "D:\django\shopenv\lib\site-packages\django\core\servers\basehttp.py", line 47, in get_internal_wsgi_application
    return import_string(app_path)
  File "D:\django\shopenv\lib\site-packages\django\utils\module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "D:\django\shopenv\lib\importlib\__init__.py", line 126, in import_module

  >  return _bootstrap._gcd_import(name[level:], package, level)
  > File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\DJANGO\store\saleor\wsgi\__init__.py", line 23, in <module>
    application = get_wsgi_application()
  File "D:\django\shopenv\lib\site-packages\django\core\wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "D:\django\shopenv\lib\site-packages\django\core\handlers\wsgi.py", line 151, in __init__
    self.load_middleware()
  File "D:\django\shopenv\lib\site-packages\django\core\handlers\base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters
mw_instance = middleware(handler)
TypeError: object() takes no parameters

**Comment by kwatog** [comment]
Sorry, my bad. My custom middleware no longer works with django 1.11.5. I didn't realize I still have that.
