### ISSUE TITLE
Error when execute ´npm run build-assets´

### ISSUE THREAD

**Issue by btenaglia** [mirumee/saleor#1566]
I try to install de application and I have a problem when execute 

**npm run build-assets**

**Server Info:**
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

node -v
v9.3.0

npm -v
5.5.1

**The error is:**
npm run build-assets

> saleor@0.0.0 build-assets /home/ubuntu/ecommerce_project/ecommerce
> node ./node_modules/webpack/bin/webpack.js -p

events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:999:13)
    at WriteWrap.afterWrite [as oncomplete] (net.js:883:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor@0.0.0 build-assets: `node ./node_modules/webpack/bin/webpack.js -p`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saleor@0.0.0 build-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-01-04T21_30_43_099Z-debug.log

Any Idea?
Thanks!

**Comment by dominik-zeglen** [comment]
It looks like you didn't run `npm install` before `npm run build-assets`.

**Comment by btenaglia** [comment]
@dominik-zeglen 
Yes, I run it before but the error is when run run build-assets

**Comment by dominik-zeglen** [comment]
I was unable to reproduce this bug - but I encountered another, strictly linked to node `9.3.0`. One of webpack plugins, `node sass`, is not working yet with `9.3.0`, so I would recommend you to use tested `8.x`, preferably `8.9.4` version.

**Comment by primal100** [comment]
I had this issue with centos and fixed it by installing fontconfig-devel with yum. I believe the apt-get equivalent is libfontconfig1-dev or try one of these:

https://apps.ubuntu.com/cat/search/?q=fontconfig&op=

You might need to rerun npm install after

**Comment by btenaglia** [comment]
@primal100 Thanks so much! Your solution was ok! I fixed the problem!

**Comment by resourceldg** [comment]
UBUNTU 16.04 Xenial core 32 bits 
hi!!

help...I have a problem  whit similar output like initial thread
try
inside venv
sudo apt-get install libfontconfig1-dev
also sudo apt-get install libfontconfig
I tried with rerun npm install
I even stopped the apache server before executing it
but this did not work
returns the error output after a long delay and S.O disconnect browser
below I leave the complete output
---------------------------------------------------------------------------------------------------------------------------------

venvsaleor) lucas@lucas-HP-530-Notebook-PC:~/Desktop/ecommerce/venvsaleor/saleor$ npm run build-assets

> saleor@0.0.0 build-assets /home/lucas/Desktop/ecommerce/venvsaleor/saleor
> node ./node_modules/webpack/bin/webpack.js -p

Error: Module build failed: Error: Command failed: /home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/svg2png/lib/converter.js {"height":1294,"width":750}

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
    at Object.eval (eval at <anonymous> (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22), <anonymous>:70:7)
    at __webpack_require__ (eval at <anonymous> (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22), <anonymous>:20:30)
    at eval (eval at <anonymous> (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22), <anonymous>:63:18)
    at eval (eval at <anonymous> (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22), <anonymous>:66:10)
    at Compilation.<anonymous> (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22)
    at next (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/webpack/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.<anonymous> (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/uglifyjs-webpack-plugin/dist/index.js:244:6)
    at Compilation.applyPluginsAsyncSeries (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/webpack/lib/Compilation.js:664:10)
    at Compilation.applyPluginsAsyncSeries (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/webpack/node_modules/tapable/lib/Tapable.js:195:46)
    at sealPart2 (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/webpack/lib/Compilation.js:660:9)
    at Compilation.applyPluginsAsyncSeries (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/webpack/node_modules/tapable/lib/Tapable.js:195:46)
    at Compilation.seal (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/webpack/lib/Compilation.js:603:8)
    at applyPluginsParallel.err (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/webpack/lib/Compiler.js:508:17)
    at /home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/webpack/lib/Compilation.js:505:11)
    at processModuleDependencies.err (/home/lucas/Desktop/ecommerce/venvsaleor/saleor/node_modules/webpack/lib/Compilation.js:475:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor@0.0.0 build-assets: `node ./node_modules/webpack/bin/webpack.js -p`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saleor@0.0.0 build-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lucas/.npm/_logs/2018-01-12T04_37_21_967Z-debug.log
(venvsaleor) lucas@lucas-HP-530-Notebook-PC:~/Desktop/ecommerce/venvsaleor/saleor$

**Comment by r0hi7** [comment]
Me too getting the same issue. 
```
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! saleor@0.0.0 build-assets: `webpack -p --progress`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the saleor@0.0.0 build-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-06-14T07_05_40_468Z-debug.log
```
I have `libfontconfig-dev` installed and `npm install` before this step. 

`node --version` v10.4.1
`npm --version`  6.1.0

**Comment by NyanKiyoshi** [comment]
Does installing those packages help?

```shell
apt install libffi-dev libjpeg-dev zlib1g-dev python-cairocffi libcairo2-dev gir1.2-pango
```

**Comment by Korred** [comment]
For anyone still trying to figure this out – the solution for me was to increase the memory size.
I was running a 1GB RAM DigitalOcean Ubuntu 16.04.4 x64 Droplet. After increasing the memory size to 8GB (not sure how much is actually needed) everything ran and completed without error. 

Maybe splitting “npm run build-assets” into smaller steps would solve the problem for low-memory systems.

Good luck! 🍀

**Comment by bdferguson** [comment]
I'm getting a similar error with webpack on Ubuntu 18.04 with ```libfontconfig-dev``` and the other packages suggested by @NyanKiyoshi installed:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! saleor@0.0.0 build-assets: `webpack -p`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the saleor@0.0.0 build-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
```node --version``` 8.10.0
```npm --version``` 5.6.0

**Comment by NyanKiyoshi** [comment]
@bdferguson as of today, Saleor is requiring to have nodejs 10+. Try upgrading it first. Then if the issue is still there, could you show the full stack, I'm guessing this was not the full output? (may be wrong)

**Comment by aceinthedeck** [comment]
As @Korred suggested. It seems this is related to RAM. I increased the server memory to 3GB from 1GB and it worked just fine.
