### ISSUE TITLE
Exception doesn't have a 'message' attribute on Python3.4+

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1667]
### What I'm trying to achieve

Refunding a product from the dashboard that was paid using the dummy provider.

### Steps to reproduce the problem

1. Refund an order with an input higher than the captured amount
2. Look at the error stack console, it should fail

### What I expected to happen

A simple error message (`Payment gateway error: Refund amount can not be greater then captured amount `)

![pic](https://i.imgur.com/0Q4vTXn.png)
(notice the typo from [django-payments](https://github.com/mirumee/django-payments/blob/db6279d220085f83f3c85b46b12d46aa871c5433/payments/models.py#L161))

### What happened instead/how it failed

```
Traceback (most recent call last):
  File "py3venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "py3venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "py3venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "py3venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "py3venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "development/saleor/saleor/dashboard/order/views.py", line 137, in refund_payment
    if form.is_valid() and form.refund():
  File "development/saleor/saleor/dashboard/order/forms.py", line 97, in refund
    return self.try_payment_action(self.payment.refund)
  File "development/saleor/saleor/dashboard/order/forms.py", line 75, in try_payment_action
    self.payment_error(e.message)
AttributeError: 'ValueError' object has no attribute 'message'
```

Edit: while I'm here, I would like to thank the whole team behind this project and all the contributors. You are doing a great job, working on such a clean, well structured code and repository, feels just great.

**Comment by elwoodxblues** [comment]
Hey @NyanKiyoshi, thanks for reporting this issue, we'll take a look at it. Also, thanks for your kind words about the project, we're doing our best to make the codebase easy to understand and pleasant to work with 🙂.
