### ISSUE TITLE
Deleting an item leading the cart to be empty leads to exception

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1787]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve
Empty a cart.

### Steps to reproduce the problem

First method:
1. Add an item to the cart;
2. Go to cart;
3. (optional) open the debugger to see the network request failing;
3. Remove the item from cart;
4. The code makes a request to `/cart/shipingoptions/` which leads to an exception (not directly visible).

Second method:
1. Have an empty cart;
2. Send a `POST` request to the endpoint `/cart/shipingoptions/` with a country;
3. It should make an exception.

or run

```python
    response = client.post('/cart/shipingoptions/', {'country': 'US'})
    assert response.status_code == 200
```

### What happened instead/how it failed

```
Note: price = '<< MISSING VARIABLE "price_range.min_price" >>'

ERROR django.request Internal Server Error: /cart/shipingoptions/ [PID:23255:Thread-29]
Traceback (most recent call last):
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 411, in render
    return strip_spaces_between_tags(self.nodelist.render(context).strip())
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/library.py", line 245, in render
    return t.render(new_context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django_prices/templatetags/prices_i18n.py", line 73, in gross
    return format_price(price.gross, price.currency, html, normalize)
AttributeError: 'str' object has no attribute 'gross'
ERROR django.request Internal Server Error: /cart/shipingoptions/ [PID:23255:Thread-29]
Traceback (most recent call last):
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 411, in render
    return strip_spaces_between_tags(self.nodelist.render(context).strip())
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/library.py", line 245, in render
    return t.render(new_context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/sayuri/py3venv/lib/python3.6/site-packages/django_prices/templatetags/prices_i18n.py", line 73, in gross
    return format_price(price.gross, price.currency, html, normalize)
AttributeError: 'str' object has no attribute 'gross'
```

**Comment by akjanik** [comment]
@NyanKiyoshi It is indeed a bug, second method worked for me, however first one didn't. Can you share if you removed item from cart in unusual way? I am just clicking trash icon and it seems to work fine.

After some investigation, `get_shipping_options` from `Cart` app looks quite obsolete, being a part of `/cart/`, however `art/shipingoptions/` itself does not seems like something we want to share with user.
It's a mystery to me why it is included in main `html` tag of `base.html`.
@elwoodxblues any suggestions how we should proceed with this one?

**Comment by elwoodxblues** [comment]
@akjanik This view is called to return a partial template of cart items, recalculated after any modification to the cart. Since this is AJAX call, we have to tell the JS what's the URL of the view, that's why we pass it in `base.html`. No mysteries in here. I agree it's an obsolete approach and we have a plan to get rid of this in the future.

The bug happens because all prices passed to the template are `None`. Can we just update the `subtotal_table.html` template to handle this case?
