### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### ISSUE THREAD

**Issue by xponrails** [mirumee/saleor#1799]
Hi I tried to install saleor in my Osx environment.

I'm using python 3.6 and the latest sources on master branch.

This in the output of the pip install:
```
(saleor) ➜  saleor git:(master) ✗ python -m pip install -r requirements.txt
Requirement already satisfied: amqp==2.2.2 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: asn1crypto==0.24.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: attrs==17.4.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: babel==2.5.3 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: billiard==3.5.0.3 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied: bleach==2.1.2 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied: boto3==1.5.31 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 13))
Requirement already satisfied: botocore==1.8.45 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 14))
Requirement already satisfied: braintree==3.39.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 15))
Requirement already satisfied: cairocffi==0.8.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 16))
Requirement already satisfied: cairosvg==2.1.3 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 17))
Requirement already satisfied: celery[redis]==4.1.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 18))
Requirement already satisfied: certifi==2018.1.18 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 19))
Requirement already satisfied: cffi==1.11.4 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 20))
Requirement already satisfied: chardet==3.0.4 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 21))
Requirement already satisfied: cryptography==2.1.4 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 22))
Requirement already satisfied: cssselect2==0.2.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 23))
Requirement already satisfied: defusedxml==0.5.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 24))
Requirement already satisfied: dj-database-url==0.4.2 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 25))
Requirement already satisfied: dj-email-url==0.0.10 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 26))
Requirement already satisfied: django-babel==0.6.2 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 27))
Requirement already satisfied: django-bootstrap4==0.0.5 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 28))
Requirement already satisfied: django-cache-url==2.0.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 29))
Requirement already satisfied: django-celery-results==1.0.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 30))
Requirement already satisfied: django-countries==5.1.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 31))
Requirement already satisfied: django-elasticsearch-dsl==0.4.4 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 32))
Requirement already satisfied: django-filter==1.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 33))
Requirement already satisfied: django-fsm==2.6.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 34))
Requirement already satisfied: django-impersonate==1.3 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 35))
Requirement already satisfied: django-js-asset==1.0.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 36))
Requirement already satisfied: django-mptt==0.9.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 37))
Requirement already satisfied: django-payments==0.12.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 38))
Requirement already satisfied: django-phonenumber-field==2.0.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 39))
Requirement already satisfied: django-prices-openexchangerates==0.1.15 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 40))
Requirement already satisfied: django-prices==0.7.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 41))
Requirement already satisfied: django-redis==4.8.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 42))
Requirement already satisfied: django-render-block==0.5 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 43))
Requirement already satisfied: django-storages==1.6.5 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 44))
Requirement already satisfied: django-templated-email==2.2.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 45))
Requirement already satisfied: django-versatileimagefield==1.9 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 46))
Requirement already satisfied: django-webpack-loader==0.5.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 47))
Requirement already satisfied: django==2.0.2 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 48))
Requirement already satisfied: docutils==0.14 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 49))
Requirement already satisfied: elasticsearch-dsl==5.4.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 50))
Requirement already satisfied: elasticsearch==5.5.2 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 51))
Requirement already satisfied: faker==0.8.11 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 52))
Requirement already satisfied: freezegun==0.3.9 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 53))
Requirement already satisfied: google-i18n-address==2.2.2 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 54))
Requirement already satisfied: google-measurement-protocol==0.1.6 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 55))
Requirement already satisfied: graphene-django==2.0.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 56))
Requirement already satisfied: graphene==2.0.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 57))
Requirement already satisfied: graphql-core==2.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 58))
Requirement already satisfied: graphql-relay==0.4.5 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 59))
Requirement already satisfied: html5lib==1.0.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 60))
Requirement already satisfied: idna==2.6 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 61))
Requirement already satisfied: iso8601==0.1.12 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 62))
Requirement already satisfied: jmespath==0.9.3 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 63))
Requirement already satisfied: jsonfield==2.0.2 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 64))
Requirement already satisfied: kombu==4.1.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 65))
Requirement already satisfied: markdown==2.6.11 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 66))
Requirement already satisfied: maxminddb-geolite2==2017.803 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 67))
Requirement already satisfied: maxminddb==1.3.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 68))
Requirement already satisfied: multidict==3.3.2 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 69))
Requirement already satisfied: oauthlib==2.0.6 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 70))
Requirement already satisfied: pdfrw==0.4 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 71))
Requirement already satisfied: phonenumberslite==8.8.11 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 72))
Requirement already satisfied: pillow==5.0.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 73))
Requirement already satisfied: pluggy==0.6.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 74))
Requirement already satisfied: prices==0.5.9 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 75))
Requirement already satisfied: promise==2.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 76))
Requirement already satisfied: psycopg2==2.7.4 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 77))
Requirement already satisfied: purl==1.3.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 78))
Requirement already satisfied: py==1.5.2 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 79))
Requirement already satisfied: pycparser==2.18 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 80))
Requirement already satisfied: pyjwt==1.5.3 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 81))
Requirement already satisfied: pyphen==0.9.4 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 82))
Requirement already satisfied: pytest-django==3.1.2 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 83))
Requirement already satisfied: pytest-mock==1.7.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 84))
Requirement already satisfied: pytest-vcr==0.3.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 85))
Requirement already satisfied: pytest==3.4.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 86))
Requirement already satisfied: python-dateutil==2.6.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 87))
Requirement already satisfied: python3-openid==3.1.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 88))
Requirement already satisfied: pytz==2018.3 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 89))
Requirement already satisfied: pyyaml==3.12 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 90))
Requirement already satisfied: redis==2.10.6 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 91))
Requirement already satisfied: requests-oauthlib==0.8.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 92))
Requirement already satisfied: requests==2.18.4 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 93))
Requirement already satisfied: rx==1.6.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 94))
Requirement already satisfied: s3transfer==0.1.12 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 95))
Requirement already satisfied: singledispatch==3.4.0.3 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 96))
Requirement already satisfied: six==1.11.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 97))
Requirement already satisfied: social-auth-app-django==2.1.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 98))
Requirement already satisfied: social-auth-core==1.6.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 99))
Requirement already satisfied: stripe==1.77.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 100))
Requirement already satisfied: suds-jurko==0.6 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 101))
Requirement already satisfied: text-unidecode==1.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 102))
Requirement already satisfied: tinycss2==0.6.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 103))
Requirement already satisfied: typing==3.6.2 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 104))
Requirement already satisfied: urllib3==1.22 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 105))
Requirement already satisfied: uwsgi==2.0.15 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 106))
Requirement already satisfied: vcrpy==1.11.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 107))
Requirement already satisfied: vine==1.1.4 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 108))
Requirement already satisfied: weasyprint==0.42.2 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 109))
Requirement already satisfied: webencodings==0.5.1 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 110))
Requirement already satisfied: wrapt==1.10.11 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 111))
Requirement already satisfied: xmltodict==0.11.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 112))
Requirement already satisfied: yarl==0.17.0 in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from -r requirements.txt (line 113))
Requirement already satisfied: setuptools in /Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages (from pytest==3.4.0->-r requirements.txt (line 86))
```

and this is the output when I run the `python manage.py migrate`:

```
(saleor) ➜  saleor git:(master) ✗ python manage.py migrate                 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/django/core/management/__init__.py", line 216, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 12, in <module>
    from django.db.migrations.autodetector import MigrationAutodetector
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/django/db/migrations/autodetector.py", line 11, in <module>
    from django.db.migrations.questioner import MigrationQuestioner
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/django/db/migrations/questioner.py", line 9, in <module>
    from .loader import MigrationLoader
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/django/db/migrations/loader.py", line 8, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 9, in <module>
    class MigrationRecorder:
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 22, in MigrationRecorder
    class Migration(models.Model):
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/django/db/models/base.py", line 100, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/django/apps/registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/django/apps/registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

As you can see, I'm using Django 2 as specified in the requirements.txt

What's wrong? I want to use Django 2 as you said in your blog.

https://medium.com/saleor/january-release-of-saleor-1d01c126af0

Do I need to checkout this tag?
https://github.com/mirumee/saleor/releases/tag/v2018.01

**Comment by xponrails** [comment]
Solved,
I was missing to set the SECRET_KEY.

**Comment by patrys** [comment]
I think this could be reported as a bug in Django. The error message is irrelevant at best.

**Comment by hassanzadeh** [comment]
I'm using python 3.4.3 and I have exported the secrete key: export SECRETE_KEY='mysecrete' but I still get exactly the same error. any help?

**Comment by patrys** [comment]
Can you verify the spelling on that? It's supposed to say `SECRET_KEY`.

**Comment by hassanzadeh** [comment]
Yes sorry, it was my typo, I'm using SECRET_KEY and get that error.
another thing is that I'm not sure I have installed postgres the right way, but my guess is that this error is not due to that.

**Comment by tkwon** [comment]
I'm running 
django 2.0.3
python 3.5.2

I have defined a SECRET_KEY as previous commenters. My traceback is as shows:

(env) PS C:\Users\Tom\projects\saleor> python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\core\management\__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\core\management\__init__.py", line 216, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\core\management\__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "C:\Users\Tom\projects\saleor\env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\core\management\commands\migrate.py", line 12, in <module>
    from django.db.migrations.autodetector import MigrationAutodetector
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\db\migrations\autodetector.py", line 11, in <module>
    from django.db.migrations.questioner import MigrationQuestioner
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\db\migrations\questioner.py", line 9, in <module>
    from .loader import MigrationLoader
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\db\migrations\loader.py", line 8, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\db\migrations\recorder.py", line 9, in <module>
    class MigrationRecorder:
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\db\migrations\recorder.py", line 22, in MigrationRecorder
    class Migration(models.Model):
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\db\models\base.py", line 100, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\apps\registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\apps\registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by nabirhossain** [comment]
I am also face this same problem. 
any one can solve this problem?
if solve . How?

**Comment by NyanKiyoshi** [comment]
@nabirhossain what OS?

On Linux, to ensure you set `SECRET_KEY`, do (copy paste as is): `env | grep SECRET_KEY`
On Windows, it should be showing as `SECRET_KEY=somethingsomething` by running `SET`.

Let us know if it shows or not before looking further.

**Comment by malibres-indra** [comment]
Im still experience this error, even though I already defined SECRET_KEY to my environment

![image](https://user-images.githubusercontent.com/91582576/219899858-17b7465d-104b-4880-be0d-5f98a60a941f.png)
