### ISSUE TITLE
Failing to send emails triggers errors and may trigger a 500 in some views.

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1827]
### What I'm trying to achieve
Add (create) a user as staff.

### Steps to reproduce the problem

1. Not quite sure of every way to raise this. But here is how it happened for me: use a gmail address as SMTP server to send the confirmation email. Which was never allowed from your IP address (can have been used through mail.google.com but not from Thunderbird or any other client than the official web one).
2. Create a staff user.

### What I expected to happen
Maybe ignore the failed email sending or abort, or else.

### What happened instead/how it failed
Crashed.

Stack (note that I'm using the release from January but I did check if there was a try block or else on master):

```
ERROR django.request Internal Server Error: /dashboard/staff/staff-create/ [PID:19270:b'uWSGIWorker7Core0']
Traceback (most recent call last):
  File "/home/sanic/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/sanic/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sanic/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sanic/env/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/sanic/env/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/sanic/deploy/saleor/dashboard/staff/views.py", line 68, in staff_create
    send_promote_customer_to_staff_email(staff)
  File "/home/sanic/env/lib/python3.5/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/home/sanic/env/lib/python3.5/site-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "/home/sanic/deploy/saleor/dashboard/emails.py", line 41, in send_promote_customer_to_staff_email
    context=ctx)
  File "/home/sanic/env/lib/python3.5/site-packages/templated_email/__init__.py", line 70, in send_templated_mail
    headers=headers, create_link=create_link, **kwargs)
  File "/home/sanic/env/lib/python3.5/site-packages/templated_email/backends/vanilla_django.py", line 263, in send
    e.send(fail_silently)
  File "/home/sanic/env/lib/python3.5/site-packages/django/core/mail/message.py", line 294, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/sanic/env/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/home/sanic/env/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 70, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python3.5/smtplib.py", line 729, in login
    raise last_exception
  File "/usr/lib/python3.5/smtplib.py", line 720, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib/python3.5/smtplib.py", line 641, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.14 <https://accounts.google.com/signin/continue?REMOVED\n5.7.14 RREMOVED> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 b28sm12513276wrg.66 - gsmtp')
UWSGI uwsgi "POST /dashboard/staff/staff-create/ HTTP/1.1" 500 163 1146ms [PID:19270:Worker-7] [RSS:0MB]
```

**Comment by patrys** [comment]
I think this is not specific to this particular email?

**Comment by NyanKiyoshi** [comment]
I'm not quite sure, I can't really test right now. But the weird thing, is I didn't had the issue when creating a order. I forgot to edit the message for that. But I would guess it was async so it wasn't directly visible.

I did check uwsgi logs but didn't see any errors. I will take a look into that as soon as I can and will keep you updated and also look if there is other way to trigger a crash.
