### ISSUE TITLE
list object has no attribute 'lower'

### ISSUE THREAD

**Issue by hassanzadeh** [mirumee/saleor#1854]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve
The only change I made was to use sqlite3 instead of postgres.
...

### Steps to reproduce the problem

1.Simply checked out from git
2. replaced the database directive
 it failed

...

(Please include a stack trace if this problem results in a crash.)
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
ERROR django.request Internal Server Error: / [PID:23989:Thread-1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.4/dist-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.4/dist-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/lib/python3.4/dist-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
ERROR django.request Internal Server Error: / [PID:23989:Thread-1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.4/dist-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.4/dist-packages/django/http/request.py", line 97, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "/usr/local/lib/python3.4/dist-packages/django/http/request.py", line 565, in validate_host
    if pattern == '*' or is_same_domain(host, pattern):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/http.py", line 273, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'
ERROR django.server "GET / HTTP/1.1" 500 83661 [PID:23989:Thread-1]
ERROR django.server "GET / HTTP/1.1" 500 83661 [PID:23989:Thread-1]
ERROR django.server "GET / HTTP/1.1" 500 83661 [PID:23989:Thread-1]

**Comment by hassanzadeh** [comment]
I'm using Django 2, I guess your code is not compatible with that.

**Comment by hassanzadeh** [comment]
Oh my bad, I messed up with the settings.

**Comment by rafalp** [comment]
Also please take a note that Saleor is developed against the PostgreSQL as it elevates features specific to it (like `hstore`) and will not work with SQLite.

If you are looking to play around with it on local host, Docker is fast and easy way to go about it:

[Setting up the Saleor for development on localhost](https://saleor.readthedocs.io/en/latest/customization/docker.html)

**Comment by hassanzadeh** [comment]
Thank you, 
I will try to isntall Postgres then.

**Comment by BATTLEROYALXS** [comment]
> Oh my bad, I messed up with the settings.

Maybe say why there is this bug could be usefull for other peoples maybe ?
