### ISSUE TITLE
relation "account_user" does not exist

### ISSUE THREAD

**Issue by hassanzadeh** [mirumee/saleor#1859]
I'm not sure why this error is thrown. I can't find any account_user relation.

### What I'm trying to achieve
To install the master branch
...

### Steps to reproduce the problem
as provided by the documentation

(Please include a stack trace if this problem results in a crash.)
ubuntu@ip-172-31-17-237:~/saleor$ python3 manage.py migrate
/usr/local/lib/python3.4/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release
2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psyc
opg/docs/install.html#binary-install-from-pypi>.
  """)
System check identified some issues:

WARNINGS:
saleor.W001: Session caching cannot work with locmem backend
        HINT: User sessions need to be globally shared, use a cache server like Redis.
Operations to perform:
  Apply all migrations: auth, contenttypes, django_celery_results, django_prices_openexchangerates, impersonate, sessions, sites, soci
al_django
Running migrations:
  Applying impersonate.0001_initial...Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "account_user" does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/base/schema.py", line 90, in __exit__
    self.execute(sql)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/base/schema.py", line 117, in execute
 File "/usr/local/lib/python3.4/dist-packages/django/db/backends/base/schema.py", line 117, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "account_user" does not exist

**Comment by hassanzadeh** [comment]
I also noted that the makemigration command does not make any py file in the migrations dirs.

**Comment by hassanzadeh** [comment]
This link: http://rahmonov.me/posts/django-1.8-bug/ says downgrading django might do the trick still not sure and I Don't want to downgrade

**Comment by hassanzadeh** [comment]
Some updates:
I tried django1.11, get the same error. Also I get some warning related to psycopg2 when makingmigrations, and the error has to do with the same lib, not sure if that is the cause.

**Comment by NyanKiyoshi** [comment]
You can ignore the psycopg2 warning. Nothing to do about it (not you at least).

**Comment by hassanzadeh** [comment]
Then what is the cause of that error?
I have been working to figure it out for 2 days, with no luck

**Comment by hassanzadeh** [comment]
Ok, another important update, I switched to the demo branch and it works now,
But why the master is not working? Which one is more updated?

**Comment by NyanKiyoshi** [comment]
psycopg2 (a postgresql driver for python), is deprecating the default psycopg2 package which requires to be compiled (automatically done by Python) on installation by a standalone package `psycopg2-binary` that comes precompiled. No worries about it.

Did you try to set saleor's DB user to a superuser in postgresql? Maybe it's failing to create some things on which it depends. Saleor needs some special permissions for creation (only creation) if I recall correctly.

Try to set the database user as superuser (`ALTER USER saleor WITH SUPERUSER;`).

**Comment by hassanzadeh** [comment]
Thanks, yes I did make it super user and as I said above on demo it is working.

**Comment by NyanKiyoshi** [comment]
No idea. I will try to see. I'm not using master but the customized version which is the January release.

**Comment by hassanzadeh** [comment]
They are using gql now, that's why I want to use the latest possible version.

**Comment by NyanKiyoshi** [comment]
Yeah, that's a good thing. I will try to see if what can trigger that error... Not sure.
Note the build doesn't fail on travis. That's kind of weird.

Could you tell me you postgresql server version?
```bash
┌─╼ [~]
└────╼ psql --version
psql (PostgreSQL) 10.2
```

**Comment by hassanzadeh** [comment]
Sure,
it is: psql (PostgreSQL) 10.3 (Ubuntu 10.3-1.pgdg14.04+1)

**Comment by NyanKiyoshi** [comment]
I recognize that you are running on a EC2 instance. I will launch one and reproduce your environment.

**Comment by hassanzadeh** [comment]
is hello at vanille.bid your email address?

**Comment by NyanKiyoshi** [comment]
Yes!

**Comment by hassanzadeh** [comment]
Ok, I'm emailing you my credentials.

**Comment by NyanKiyoshi** [comment]
No need right now. Let me test on my own new clean instance. (plus you should probably use a SSH key instead of password and disable the password authentication on the EC2 instance if that's what you are doing?)

**Comment by NyanKiyoshi** [comment]
No issues on my side on EC2... Here is what I did if that may help (note that I created a virtualenv instead of installing requirements as root)...

```bash
# As root
apt-get install postgresql-10 python-dev libffi-dev python-psycopg2 libpq-dev libjpeg-dev zlib1g-dev python-cairocffi libcairo2-dev gir1.2-pango
systemctl start postgresql

sudo -sHu postgres
cd
createuser -P -s saleor
createdb saleor

# As user
git clone https://github.com/mirumee/saleor
cd saleor
virtualenv -p /usr/bin/python3.4 env

. env/bin/activate
pip3 install -r requirements.txt 
SECRET_KEY='none' python3 manage.py migrate
```

**Comment by hassanzadeh** [comment]
Thanks,
I installed a fresh ubuntu 16.0.
Now I'm getting another error, It turns out that saleor is updated but not tested.
There is no PriceField in the django_price app that I find in mirumee github. 

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/ubuntu/saleor/saleor/discount/models.py", line 10, in <module>
    from django_prices.models import PriceField
ImportError: cannot import name 'PriceField'

**Comment by hassanzadeh** [comment]
Did they mean MoneyField instead?

**Comment by hassanzadeh** [comment]
May I ask which version your installed?

**Comment by hassanzadeh** [comment]
Nothing is consistent, I wish the developer at least run this once locally, now after replace all the money with Price, there is another thing and perhaps many more:
 from django_prices.templatetags.prices_i18n import net
ImportError: cannot import name 'net'

**Comment by NyanKiyoshi** [comment]
I cloned the latest from the master branch.
Are you sure you installed correctly the requirements using `pip3 install -r requirements.txt`?

**Comment by hassanzadeh** [comment]
Sure, here it is:
ubuntu@ip-172-31-30-107:~/data/saleor$ pip3 freeze
amqp==2.2.2
attrs==17.4.0
Babel==2.5.3
billiard==3.5.0.3
blinker==1.3
boto3==1.6.3
botocore==1.9.3
braintree==3.42.0
cairocffi==0.8.0
CairoSVG==2.1.3
celery==4.1.0
cffi==1.11.5
chardet==2.3.0
cloud-init==17.1
command-not-found==0.3
configobj==5.0.6
cryptography==1.2.3
cssselect2==0.2.1
defusedxml==0.5.0
dj-database-url==0.5.0
dj-email-url==0.0.10
Django==2.0.2
django-babel==0.6.2
django-bootstrap4==0.0.6
django-cache-url==2.0.0
django-celery-results==1.0.1
django-countries==5.1.1
django-elasticsearch-dsl==0.4.4
django-filter==1.1.0
django-fsm==2.6.0
django-impersonate==1.3
django-js-asset==1.0.0
django-mptt==0.9.0
django-payments==0.12.1
django-phonenumber-field==2.0.0
django-prices==1.0.0
django-prices-openexchangerates==1.0.0
django-redis==4.9.0
django-render-block==0.5
django-storages==1.6.5
django-templated-email==2.2.0
django-versatileimagefield==1.9
django-webpack-loader==0.6.0
docutils==0.14
elasticsearch==5.5.2
elasticsearch-dsl==5.4.0
Faker==0.8.11
freezegun==0.3.9
google-i18n-address==2.2.2
google-measurement-protocol==0.1.6
graphene==2.0.1
graphene-django==2.0.0
graphql-core==2.0
graphql-relay==0.4.5
hibagent==1.0.1
html5lib==1.0.1
idna==2.0
iso8601==0.1.12
Jinja2==2.8
jmespath==0.9.3
jsonfield==2.0.2
jsonpatch==1.10
jsonpointer==1.9
kombu==4.1.0
language-selector==0.1
Markdown==2.6.11
MarkupSafe==0.23
maxminddb==1.3.0
maxminddb-geolite2==2017.803
multidict==4.1.0
oauthlib==1.0.3
pdfrw==0.4
phonenumberslite==8.9.0
Pillow==5.0.0
pluggy==0.6.0
prettytable==0.7.2
prices==1.0.0
promise==2.1
psycopg2==2.7.4
purl==1.3.1
py==1.5.2
pyasn1==0.1.9
pycparser==2.18
pycurl==7.43.0
pygobject==3.20.0
PyJWT==1.3.0
Pyphen==0.9.4
pyserial==3.0.1
pytest==3.4.1
pytest-django==3.1.2
pytest-mock==1.7.1
pytest-vcr==0.3.0
python-apt==1.1.0b1+ubuntu0.16.4.1
python-dateutil==2.6.1
python-debian==0.1.27
python-systemd==231
python3-openid==3.1.0
pytz==2018.3
PyYAML==3.11
redis==2.10.6
requests==2.9.1
requests-oauthlib==0.8.0
Rx==1.6.1
s3transfer==0.1.13
satchless==1.1.3
singledispatch==3.4.0.3
six==1.10.0
social-auth-app-django==2.1.0
social-auth-core==1.7.0
ssh-import-id==5.5
stripe==1.79.1
suds-jurko==0.6
text-unidecode==1.2
tinycss2==0.6.1
typing==3.6.4
ufw==0.35
unattended-upgrades==0.1
urllib3==1.22
uWSGI==2.0.17
vcrpy==1.11.1
vine==1.1.4
WeasyPrint==0.42.2
webencodings==0.5.1
wrapt==1.10.11
xmltodict==0.11.0
yarl==1.1.1

**Comment by hassanzadeh** [comment]
Thank you so much, that was the issue.
Trying to figure out other things now.

**Comment by hassanzadeh** [comment]
Ok, I'm all set, thank you so much for your help.
By the way what is the defaul admin login email/pass?

**Comment by NyanKiyoshi** [comment]
Depends. I think if you ran `python manage.py populatedb` it probably created `admin@example.com` and password `admin`.

But, I would recommend you to use `python manage.py createsuperuser`, it will prompt you to enter a email address and a password.

**Comment by hassanzadeh** [comment]
Oh thanks,
actually that returns an error, I believe this could be a bug in the code:

django.db.utils.IntegrityError: null value in column "billing_address_id" violates not-null constraint

Full trace:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: null value in column "billing_address_id" violates not-null constraint
DETAIL:  Failing row contains (6, 2018-03-04 17:27:01.990888+00, 2018-03-04 17:27:01.990901+00, , , 6ad5e67e-3bf0-4371-ba3f-9a327a7c6f26, null, null, 1, null, null, null, , null, en-us, 0.0000).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 365, in execute
****
   self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/data/saleor/saleor/core/management/commands/populatedb.py", line 65, in handle
    for msg in create_orders(20):
  File "/home/ubuntu/data/saleor/saleor/core/utils/random_data.py", line 474, in create_orders
    order = create_fake_order()
  File "/home/ubuntu/data/saleor/saleor/core/utils/random_data.py", line 443, in create_fake_order
    order = Order.objects.create(**user_data)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 417, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ubuntu/data/saleor/saleor/order/models.py", line 88, in save
    return super().save(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1281, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "billing_address_id" violates not-null constraint
DETAIL:  Failing row contains (6, 2018-03-04 17:27:01.990888+00, 2018-03-04 17:27:01.990901+00, , , 6ad5e67e-3bf0-4371-ba3f-9a327a7c6f26, null, null, 1, null, null, null, , null, en-us, 0.0000).

**Comment by hassanzadeh** [comment]
Just something to check, the next time I ran it, it ended. So some null are not allowed somwhere.

**Comment by NyanKiyoshi** [comment]
I don't run into any issues on my side. It may be from previous failed/ aborted command that you ran before.

**Comment by hassanzadeh** [comment]
ok, thanks.

**Comment by herokri** [comment]
Solved the problem "account_user" by doing:
python manage.py makemigrations account
before 
python manage.py migrate
