### ISSUE TITLE
ImportError: No module named 'html5lib.filters.base'

### ISSUE THREAD

**Issue by pards** [mirumee/saleor#1861]
### What I'm trying to achieve

Following the installation instructions

### Steps to reproduce the problem

`python manage.py runserver`

### What I expected to happen

Expected server to start

### What happened instead/how it failed

```
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.

  """)

/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.

  """)

Performing system checks...

 

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7efd678e4840>

Traceback (most recent call last):

  File "/home/developer/.local/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper

    fn(*args, **kwargs)

  File "/home/developer/.local/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run

    self.check(display_num_errors=True)

  File "/home/developer/.local/lib/python3.5/site-packages/django/core/management/base.py", line 364, in check

    include_deployment_checks=include_deployment_checks,

  File "/home/developer/.local/lib/python3.5/site-packages/django/core/management/base.py", line 351, in _run_checks

    return checks.run_checks(**kwargs)

  File "/home/developer/.local/lib/python3.5/site-packages/django/core/checks/registry.py", line 73, in run_checks

    new_errors = check(app_configs=app_configs)

  File "/home/developer/.local/lib/python3.5/site-packages/django/core/checks/urls.py", line 13, in check_url_config

    return check_resolver(resolver)

  File "/home/developer/.local/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver

    return check_method()

  File "/home/developer/.local/lib/python3.5/site-packages/django/urls/resolvers.py", line 397, in check

    for pattern in self.url_patterns:

  File "/home/developer/.local/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__

    res = instance.__dict__[self.name] = self.func(instance)

  File "/home/developer/.local/lib/python3.5/site-packages/django/urls/resolvers.py", line 536, in url_patterns

    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)

  File "/home/developer/.local/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__

    res = instance.__dict__[self.name] = self.func(instance)

  File "/home/developer/.local/lib/python3.5/site-packages/django/urls/resolvers.py", line 529, in urlconf_module

    return import_module(self.urlconf_name)

  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 986, in _gcd_import

  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 665, in exec_module

  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed

  File "/home/developer/saleor/saleor/urls.py", line 14, in <module>

    from .dashboard.urls import urlpatterns as dashboard_urls

  File "/home/developer/saleor/saleor/dashboard/urls.py", line 13, in <module>

    from .product.urls import urlpatterns as product_urls

  File "/home/developer/saleor/saleor/dashboard/product/urls.py", line 3, in <module>

    from . import views

  File "/home/developer/saleor/saleor/dashboard/product/views.py", line 12, in <module>

    from . import forms

  File "/home/developer/saleor/saleor/dashboard/product/forms.py", line 1, in <module>

    import bleach

  File "/home/developer/.local/lib/python3.5/site-packages/bleach/__init__.py", line 8, in <module>

    from bleach.linkifier import (

  File "/home/developer/.local/lib/python3.5/site-packages/bleach/linkifier.py", line 6, in <module>

    from html5lib.filters.base import Filter

ImportError: No module named 'html5lib.filters.base'

```

**Comment by akjanik** [comment]
Hi @pards! Can you please specify what OS you are running and what version of `html5lib` is installed?

**Comment by Pacu2** [comment]
Closing for now, please reopen if this issue reappears
