### ISSUE TITLE
Graphql

### ISSUE THREAD

**Issue by hassanzadeh** [mirumee/saleor#1864]
I get error in the backend when gql requests are sent for filtering products:

### What I'm trying to achieve
testing
...

### Steps to reproduce the problem
just installed the demo.

**INFO django.server "POST /graphql HTTP/1.1" 200 18793 [PID:18744:Thread-180]
INFO django.server "POST /graphql HTTP/1.1" 200 18793 [PID:18744:Thread-180]
ERROR graphql.execution.executor An error occurred while resolving field CategoryType.products [PID:18744:Thread-181]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python3.5/dist-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/graphene_django/debug/middleware.py", line 56, in resolve
    promise = next(root, info, **args)
  File "/usr/local/lib/python3.5/dist-packages/graphql/execution/middleware.py", line 57, in make_it_promise
    return Promise.resolve(next(*a, **b))
  File "/usr/local/lib/python3.5/dist-packages/graphene_django/fields.py", line 128, in connection_resolver
    return on_resolve(iterable)
  File "/usr/local/lib/python3.5/dist-packages/graphene_django/fields.py", line 80, in resolve_connection
    iterable = cls.merge_querysets(default_queryset, iterable)
  File "/usr/local/lib/python3.5/dist-packages/graphene_django/fields.py", line 70, in merge_querysets
    return queryset & default_queryset
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 317, in __and__
    combined.query.combine(other.query, sql.AND)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/query.py", line 525, in combine
    "Cannot combine a unique query with a non-unique query."
AssertionError: Cannot combine a unique query with a non-unique query.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/graphql/execution/executor.py", line 330, in complete_value_catching_error
    exe_context, return_type, field_asts, info, result)
  File "/usr/local/lib/python3.5/dist-packages/graphql/execution/executor.py", line 383, in complete_value
    raise GraphQLLocatedError(field_asts, original_error=result)
graphql.error.located_error.GraphQLLocatedError: Cannot combine a unique query with a non-unique query.

**

**Comment by elwoodxblues** [comment]
Hej, I've just updated the `demo` branch with latest changes from `master`. Could you pull and check it again? I think this issue should be resolved now.

**Comment by hassanzadeh** [comment]
Thanks,
I just checked, I'm confused, last time when I tested demo, it was using react that's why without pressing any update key, I was getting that error the moment I checked a checkbox, but now there is no sign of react, and of course when there is no react I wont get any error. Am I missing something?

**Comment by elwoodxblues** [comment]
If you're on `demo` branch, you should have dynamic category view which is rendered in React and allows for dynamic filtering. This was introduced experimentally some time ago for the purpose of testing GraphQL in Saleor. On the other hand, on `master` branch there are "static" Django views.

**Comment by hassanzadeh** [comment]
I see, let me reinstall then.

**Comment by hassanzadeh** [comment]
by the way, what front-end lib are you using to connect to graphql server? Is it apollo or relay?

**Comment by hassanzadeh** [comment]
By the way, I noticed that the back and forward buttons do not work properly, can you check that as well?

**Comment by elwoodxblues** [comment]
We use Apollo as the GraphQL client.

Generally, you should rather refer to `master` for the most recent version of Saleor. We use `demo` branch only to serve the [demo store](https://demo.getsaleor.com/) and there are some customizations that you shouldn't need.

**Comment by hassanzadeh** [comment]
Thanks, but when do you think your master branch will incorporate your recent react/gql addons?

**Comment by elwoodxblues** [comment]
We made the decision to implement the entire storefront as a single-page app with React and full GraphQL API only recently. Our priority now is to incorporate React in the Dashboard first and we're planning to do it by the end of June 2018. Our next goal will be rewriting the storefront. A long-term roadmap is being prepared and will be published on Github.

**Comment by hassanzadeh** [comment]
Ok, good luck with your journey.
