### ISSUE TITLE
AttributeError: 'OrderLine' object has no attribute 'get_price_per_item'

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1867]
When placing an order I got the following error from the Google Analytics reporting script:

```
ERROR saleor.order.signals Recording order in analytics failed [PID:65745:Thread-255]
Traceback (most recent call last):
  File "/Users/marcin/mirumee/saleor/saleor/order/signals.py", line 20, in order_status_change
    analytics.report_order(order.tracking_client_id, order)
  File "/Users/marcin/mirumee/saleor/saleor/core/analytics.py", line 55, in report_order
    for ol in group]
  File "/Users/marcin/mirumee/saleor/saleor/core/analytics.py", line 55, in <listcomp>
    for ol in group]
AttributeError: 'OrderLine' object has no attribute 'get_price_per_item'
```

It probably broke with our recent changes (dropping Satchless or merging new prices library). As this is a Celery task, the error is visible in the console but doesn't block the site.

**Comment by rafalp** [comment]
Yep, `get_price_per_item` getter has been superseded by the `unit_price` combined field on model
