### ISSUE TITLE
Exception Value:	 Cannot add amount in 'INR' to 'USD'

### ISSUE THREAD

**Issue by suthargk** [mirumee/saleor#2041]
Exception Value: | Cannot add amount in 'INR' to 'USD'
After changing DEFAULT CURRENT in settings.py

**Comment by patrys** [comment]
We can't help you unless you can provide a full stack trace. From the exception alone it's hard to tell where it occurred and which amount was represented in US dollars.

**Comment by suthargk** [comment]
here : http://dpaste.com/0V6XTVK

**Comment by patrys** [comment]
It seems that you have some existing `saleor.order.models.Payment` instances with their currency set to `USD`. The code is not prepared to handle a case where a payment is using a different currency than the order so I suggest that you take care of those.

**Comment by Pacu2** [comment]
I think this is already resolved

**Comment by VimalP0904** [comment]
please give a solution for this

**Comment by NyanKiyoshi** [comment]
Hi, we don't support multiple currencies at the moment. You should use INR for everything. The fact that you have both INR and USD in your database, means you have mixed currencies in your store.

I expect that it happened to you in development, the easiest would be to start from scratch: wipe the database, populate the database with INR as default currency. And only use INR.

**Comment by Olegt0rr** [comment]
Please make `populatedb` using default currency, it will help to avoid this issue for newbies.
Now I'm running new app with non-USD-currency and get exception on populatedb step.

**Comment by cristian05** [comment]
I,m having the same error: `ValueError: Cannot add amount in 'COP' to 'USD'`, I execute `populatedb` with `DEFAULT_CURRENCY` equal to `COP` but the error its the same:

```shell
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ferri/.cache/virtualenvs/saleor-2.11-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/ferri/.cache/virtualenvs/saleor-2.11-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ferri/.cache/virtualenvs/saleor-2.11-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ferri/.cache/virtualenvs/saleor-2.11-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/var/www/saleor/saleor/core/management/commands/populatedb.py", line 112, in handle
    for msg in create_orders(20):
  File "/var/www/saleor/saleor/core/utils/random_data.py", line 652, in create_orders
    order = create_fake_order(discounts)
  File "/var/www/saleor/saleor/core/utils/random_data.py", line 569, in create_fake_order
    order.total = sum([line.get_total() for line in lines], shipping_price)
  File "/home/ferri/.cache/virtualenvs/saleor-2.11-py3.8/lib/python3.8/site-packages/prices/taxed_money.py", line 73, in __add__
    net = self.net + other.net
  File "/home/ferri/.cache/virtualenvs/saleor-2.11-py3.8/lib/python3.8/site-packages/prices/money.py", line 84, in __add__
    raise ValueError(
ValueError: Cannot add amount in 'COP' to 'USD'
```

### Environmnet

Saleor 2.11
Django 3.1.2
ubuntu 20.04
python 3.8.5

DEFAULT_COUNTRY=CO
DEFAULT_CURRENCY=COP
