### ISSUE TITLE
saleor.W001: Session caching cannot work with locmem backend

### ISSUE THREAD

**Issue by ZnaeW** [mirumee/saleor#2125]
I was installing Saleor and had the following problem after the migration:
```

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7feb5d026400>
Traceback (most recent call last):
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "saleor" to address: Name or service not known
```

he above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 123, in inner_run
    self.check_migrations()
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/core/management/base.py", line 427, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/migrations/loader.py", line 206, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/scripts/saleor/shop/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "saleor" to address: Name or service not known
`
```

I read the other topics related to this problem, but It didn't helo me, I need to run ASAP. thank you

**Comment by akjanik** [comment]
Hi, can you please describe how did you installed Saleor? Did you use docker or non-docker way? Was it during running `makemigrations/migrate` command on after, while trying `runserver`?

**Comment by ZnaeW** [comment]
I installed following the guide http://saleor.readthedocs.io/en/latest/, but I think it was a problem with the database. I've solved by myself. Thank you for asking and answering me. Just for the record, I tried non-docker way and was after migrate.

**Comment by akjanik** [comment]
Good to know, thank you for the update, I am happy you solved the problem. Setting up database can be painful sometimes, docker comes very handy there.
