### ISSUE TITLE
Database migration error

### ISSUE THREAD

**Issue by leikoilja** [mirumee/saleor#2144]
### What I'm trying to achieve
I am trying to install and set up Saleor for the first time. Following [documentation](http://saleor.readthedocs.io/en/latest/gettingstarted/installation-windows.html) i have installed all newest dependencies and packages. Getting to the point when i need to migrate the database it keeps showing me the Django 'Apps aren't loaded yet.' error.

### Steps to reproduce the problem

1. Follow official installation [documentation](http://saleor.readthedocs.io/en/latest/gettingstarted/installation-windows.html) 
2. In "Installation for Windows" point 5 login to phAdmin, right click to create a user
3. Set name and password to be 'saleor'
4. In Privileges tab enable all options (incl. superuser)

### What I expected to happen
I would expect successful database migration 

### What happened instead/how it failed
Getting Django error:
```
(Saleor) E:\Development\Web\eCommerce\saleor>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Ilja\Envs\Saleor\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Users\Ilja\Envs\Saleor\lib\site-packages\django\core\management\__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Ilja\Envs\Saleor\lib\site-packages\django\core\management\__init__.py", line 216, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\Users\Ilja\Envs\Saleor\lib\site-packages\django\core\management\__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "C:\Users\Ilja\Envs\Saleor\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\Users\Ilja\Envs\Saleor\lib\site-packages\django\core\management\commands\migrate.py", line 12, in <module>
    from django.db.migrations.autodetector import MigrationAutodetector
  File "C:\Users\Ilja\Envs\Saleor\lib\site-packages\django\db\migrations\autodetector.py", line 11, in <module>
    from django.db.migrations.questioner import MigrationQuestioner
  File "C:\Users\Ilja\Envs\Saleor\lib\site-packages\django\db\migrations\questioner.py", line 9, in <module>
    from .loader import MigrationLoader
  File "C:\Users\Ilja\Envs\Saleor\lib\site-packages\django\db\migrations\loader.py", line 8, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "C:\Users\Ilja\Envs\Saleor\lib\site-packages\django\db\migrations\recorder.py", line 9, in <module>
    class MigrationRecorder:
  File "C:\Users\Ilja\Envs\Saleor\lib\site-packages\django\db\migrations\recorder.py", line 22, in MigrationRecorder
    class Migration(models.Model):
  File "C:\Users\Ilja\Envs\Saleor\lib\site-packages\django\db\models\base.py", line 100, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\Ilja\Envs\Saleor\lib\site-packages\django\apps\registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\Ilja\Envs\Saleor\lib\site-packages\django\apps\registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by NyanKiyoshi** [comment]
Hi!

Did you (and correctly) set the `SECRET_KEY` environment variable before running this command?

This error happens when the `SECRET_KEY` value is not set.

**Comment by leikoilja** [comment]
Thank you, @NyanKiyoshi for your fast replies and help.
I have figured out that i might have added SECTER_KEY env variable in a wrong way. After googling i have found and created env variable as [this](https://www.twilio.com/blog/2017/01/how-to-set-environment-variables.html) article describes. After creating it i have received an error "django.db.utils.OperationalError: FATAL: database "saleor" does not exist", after some search in this git [forum](django.db.utils.OperationalError: FATAL: database "saleor" does not exist) i have found out that you need to manually create db named 'saleor' and set owner to be 'saleor' as well. I have done that using pgAdmin panel and it worked 👍 Now it successfully migrates.
Thank you @NyanKiyoshi
