### ISSUE TITLE
Incompatible units: 'px' and 'rem'.

### ISSUE THREAD

**Issue by raybesiga** [mirumee/saleor#2232]
### Adding Spectre CSS library breaks my build

So, I want to add the [Spectre CSS Toolkit](https://picturepan2.github.io/spectre/) to my frontend build of Saleor but when i take the necessary steps, it breaks the build. Below are the details:

```
(sokonee) ➜  sokoni git:(master) ✗ npm run build-assets

> saleor@0.0.0 build-assets /Users/raybesiga/Projects/sokoni
> webpack -p --progress

  0% compiling(node:3641) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Hash: d3adfa612cd5ed4dd152
Version: webpack 4.5.0
Time: 86413ms
Built at: 2018-5-23 16:37:29
 28 assets
Entrypoint dashboard = dashboard.css dashboard.js
Entrypoint document = document.css document.js
Entrypoint storefront = storefront.js
   [5] (webpack)/buildin/module.js 519 bytes {0} {2} [built]
   [7] (webpack)/buildin/global.js 509 bytes {0} [built]
  [17] ./saleor/static/images/pass-visible.svg 62 bytes {0} [built]
  [18] ./saleor/static/images/pass-invisible.svg 64 bytes {0} [built]
  [24] ./saleor/static/js/stores/variantPicker.js 1.54 KiB {0} [built]
  [38] ./saleor/static/scss/storefront.scss 1.06 KiB {0} [built] [failed] [1 error]
  [41] ./saleor/static/js/storefront.js 523 bytes {0} [built]
  [43] ./saleor/static/dashboard/scss/document.scss 39 bytes {1} [built]
  [44] ./saleor/static/dashboard/js/document.js 48 bytes {1} [built]
  [57] ./saleor/static/dashboard/images/close.svg 55 bytes {2} [built]
  [58] ./saleor/static/dashboard/images/done.svg 54 bytes {2} [built]
  [59] ./saleor/static/dashboard/images/editor/format_clear.svg 62 bytes {2} [built]
  [76] ./saleor/static/dashboard/scss/dashboard.scss 39 bytes {2} [built]
  [78] (webpack)/buildin/amd-options.js 82 bytes {2} [built]
  [80] ./saleor/static/dashboard/js/dashboard.js 151 bytes {2} [built]
    + 66 hidden modules

ERROR in ./saleor/static/scss/storefront.scss
Module build failed: ModuleBuildError: Module build failed:
$control-padding-y: ($control-size - $line-height) / 2 - $border-width !default;
                   ^
      Incompatible units: 'px' and 'rem'.
      in /Users/raybesiga/Projects/sokoni/node_modules/spectre.css/src/_variables.scss (line 88, column 21)
    at runLoaders (/Users/raybesiga/Projects/sokoni/node_modules/webpack/lib/NormalModule.js:242:20)
    at /Users/raybesiga/Projects/sokoni/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/raybesiga/Projects/sokoni/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/raybesiga/Projects/sokoni/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/raybesiga/Projects/sokoni/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/Users/raybesiga/Projects/sokoni/node_modules/neo-async/async.js:7921:18)
    at options.error (/Users/raybesiga/Projects/sokoni/node_modules/node-sass/lib/index.js:294:32)
 @ ./saleor/static/js/storefront.js 9:0-34
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--5-1!node_modules/postcss-loader/lib/index.js??ref--5-2!node_modules/sass-loader/lib/loader.js??ref--5-3!saleor/static/dashboard/scss/dashboard.scss:
     11 assets
    Entrypoint mini-css-extract-plugin = *
       [0] ./saleor/static/dashboard/images/chevron-right.svg 63 bytes {0} [built]
      [13] ./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./saleor/static/dashboard/scss/dashboard.scss 645 KiB {0} [built]
        + 12 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--5-1!node_modules/postcss-loader/lib/index.js??ref--5-2!node_modules/sass-loader/lib/loader.js??ref--5-3!saleor/static/dashboard/scss/document.scss:
    Entrypoint mini-css-extract-plugin = *
       [1] ./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./saleor/static/dashboard/scss/document.scss 7.49 KiB {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--5-1!node_modules/postcss-loader/lib/index.js??ref--5-2!node_modules/sass-loader/lib/loader.js??ref--5-3!saleor/static/scss/storefront.scss:
    Entrypoint mini-css-extract-plugin = *
       [0] ./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./saleor/static/scss/storefront.scss 297 bytes {0} [built] [failed] [1 error]

    ERROR in ./saleor/static/scss/storefront.scss (./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./saleor/static/scss/storefront.scss)
    Module build failed:
    $control-padding-y: ($control-size - $line-height) / 2 - $border-width !default;
                       ^
          Incompatible units: 'px' and 'rem'.
          in /Users/raybesiga/Projects/sokoni/node_modules/spectre.css/src/_variables.scss (line 88, column 21)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! saleor@0.0.0 build-assets: `webpack -p --progress`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the saleor@0.0.0 build-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### What I expected to happen

I think it is a little misleading given the units are all in rem in the _variables.scss file. I expected that the build would be intact as the Sass syntax is clean and compliant, and that the units are actually in `rem` and not `px`

```
// Unit sizes
$unit-o: .05rem !default;
$unit-h: .1rem !default;
$unit-1: .2rem !default;
$unit-2: .4rem !default;
$unit-3: .6rem !default;
$unit-4: .8rem !default;
$unit-5: 1rem !default;
$unit-6: 1.2rem !default;
$unit-7: 1.4rem !default;
$unit-8: 1.6rem !default;
$unit-9: 1.8rem !default;
$unit-10: 2rem !default;
$unit-12: 2.4rem !default;
$unit-16: 3.2rem !default;

// Font sizes
$html-font-size: 20px !default;
$html-line-height: 1.5 !default;
$font-size: .8rem !default;
$font-size-sm: .7rem !default;
$font-size-lg: .9rem !default;
$line-height: 1rem !default;

// Sizes
$layout-spacing: $unit-2 !default;
$layout-spacing-sm: $unit-1 !default;
$layout-spacing-lg: $unit-4 !default;
$border-radius: $unit-h !default;
$border-width: $unit-o !default;
$border-width-lg: $unit-h !default;
$control-size: $unit-9 !default;
$control-size-sm: $unit-7 !default;
$control-size-lg: $unit-10 !default;
$control-padding-x: $unit-2 !default;
$control-padding-x-sm: $unit-2 * .75 !default;
$control-padding-x-lg: $unit-2 * 1.5 !default;
$control-padding-y: ($control-size - $line-height) / 2 - $border-width !default;
$control-padding-y-sm: ($control-size-sm - $line-height) / 2 - $border-width !default;
$control-padding-y-lg: ($control-size-lg - $line-height) / 2 - $border-width !default;
$control-icon-size: .8rem !default;
```

What I suspect may be the problem is that `Spectre` uses `Gulp` to build while with Saleor we use `npm run build-assets`. Is there a way to resolve this issue? Thanks everyone.

**Comment by NyanKiyoshi** [comment]
Hi!

Saleor is using Bootstrap 4 as base. Looks like your code is using Bootstrap's value for the variable `border-width` which is `1px` ([see here](https://github.com/twbs/bootstrap/blob/2ea0a9bba9880d50b9a898dd148cbe66b694e52d/scss/_variables.scss#L208)).

You should not try to use two frameworks, it's only gonna create mess.

**Comment by raybesiga** [comment]
Great catch @NyanKiyoshi! Is there no way to decouple Saleor from Bootstrap without the entire frontend build breaking? I think we should investigate options in this regard. Any suggestions?

**Comment by patrys** [comment]
Bootstrap 4 is only used by the storefront. If you remove all Bootstrap imports from your JS and SCSS (storefront.js and storefront.scss) you should be able to provide custom replacements without the build breaking.

In this case you are importing both and they happen to reference some common variable names which means certain variables are set twice and to values the other framework is not expecting.

**Comment by shamspias** [comment]
I fix my problem after doing this.
npm install sass-loader node-sass webpack --save-dev
