### ISSUE TITLE
hstore.control error meanwhile db migration

### ISSUE THREAD

**Issue by Arkango** [mirumee/saleor#2244]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve
i'm having some trouble during the migration of the db
because there is an exception about the migration of the table 
 Applying product.0021_add_hstore_extension.
but the other tables are migrated correctly
i'm using linux mint , postgres 9.5 
...

### Steps to reproduce the problem

1. python manage.py migrate

### What I expected to happen
the migration of the db
yes is done, but the erroe on that extension.
my user i did as a superuser
### What happened instead/how it failed

...

(Please include a stack trace if this problem results in a crash.)

python manage.py migrate
System check identified some issues:

WARNINGS:
saleor.W001: Session caching cannot work with locmem backend
	HINT: User sessions need to be globally shared, use a cache server like Redis.
Operations to perform:
  Apply all migrations: account, auth, checkout, contenttypes, discount, django_celery_results, django_prices_openexchangerates, django_prices_vatlayer, impersonate, menu, order, page, product, sessions, shipping, site, sites, social_django
Running migrations:
  Applying product.0021_add_hstore_extension...Traceback (most recent call last):
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: could not open extension control file "/usr/share/postgresql/9.5/extension/hstore.control": No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/contrib/postgres/operations.py", line 19, in database_forwards
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS %s" % schema_editor.quote_name(self.name))
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 117, in execute
    cursor.execute(sql, params)
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/www/html/saleor/tutorial-env/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: could not open extension control file "/usr/share/postgresql/9.5/extension/hstore.control": No such file or directory

**Comment by NyanKiyoshi** [comment]
Hi! Can you try to run:
```shell
apt install postgresql-contrib-9.4
```

**Comment by Arkango** [comment]
thank you NyanKiyoshi

**Comment by imehmood** [comment]
I am facing same problem although I have postgresql-contrib already installed  as shown below. Any idea?
Cent OS 7
$ sudo yum install postgresql-contrib
Package postgresql-contrib-9.2.24-1.el7_5.x86_64 already installed and latest version
Nothing to do
