### ISSUE TITLE
Error after install " Cannot import name ResolveInfo"

### ISSUE THREAD

**Issue by critiquecom** [mirumee/saleor#2302]
### ****What I'm trying to achieve****
New to Saleor and to Gihub :-) Wishing to establish  a Saleor CMS on windows VM Azure 
### Steps to reproduce the problem
1. I followed the Saleor installation instruction steps based on the provided requirement.txt file and the Azure instructions to setup up a web app
2. Because of the error message below repeated a new install of Saleor into Python Tools for Visual Studio (PTVS) on a local windows machine running windows 10 just to eliminate Azure from the equation.
I have scanned the Internet and found this link: https://github.com/graphql-python/graphene/issues/546

### What I expected to happen
Default saleor web site home page screen
------------------------------------------------
I have limited python programming experience. Using the testing environment I have 1) renamed the Saleor folder named graphql to graphqlOLD 2) alternatively tried renaming Lib/Site- package: graphql folder to graphqlOLD. 
 Is there some guidance on what steps I could go through to narrow down what is causing the  problem.? Any help appreciated  

### Screenshots
Traceback (most recent call last):
      File "run_waitress_server.py", line 9, in <module>
        application = get_wsgi_application()
      File "D:\home\python364x64\Lib\site-packages\django\core\wsgi.py", line 12, in get_wsgi_application
        django.setup(set_prefix=False)
      File "D:\home\python364x64\Lib\site-packages\django\__init__.py", line 24, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "D:\home\python364x64\Lib\site-packages\django\apps\registry.py", line 89, in populate
        app_config = AppConfig.create(entry)
      File "D:\home\python364x64\Lib\site-packages\django\apps\config.py", line 90, in create
        module = import_module(entry)
      File "E:\A\_work\79\b\source_packages\python.3.6.4\tools\Lib\importlib\__init__.py", line 126, in import_module
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "D:\home\python364x64\Lib\site-packages\graphene_django\__init__.py", line 1, in <module>
        from .types import (
      File "D:\home\python364x64\Lib\site-packages\graphene_django\types.py", line 4, in <module>
        from graphene import Field
      File "D:\home\python364x64\Lib\site-packages\graphene\__init__.py", line 3, in <module>
        from .types import (
      File "D:\home\python364x64\Lib\site-packages\graphene\types\__init__.py", line 2, in <module>
        from graphql import ResolveInfo
    ImportError: cannot import name 'ResolveInfo'

**System information**
Operating system: windows 10
Browser:: IE 11

**Comment by YunazGilang** [comment]
I think renaming that directory will make some conflict to the system,  as saleor need to refer to that path and use it for the app name and package. Have you tried upgrading your graphene and graphql?  I am using graphql version 2.0 and it works just fine

**Comment by critiquecom** [comment]
Hello  This is the requirements.txt file that I have used...
[requirements.txt](https://github.com/mirumee/saleor/files/2121881/requirements.txt)

and have followed the instructions. Both the Azure install and the PTVS install produce the same problem. What is common is the PostgreSQL database . I wonder if I have an issue here?  
Some steps to narrow down my problem would be really appreciated

**Comment by NyanKiyoshi** [comment]
Could send us the output of this command:
```
D:\home\python364x64\Scripts\pip.exe freeze
```

**Comment by critiquecom** [comment]
Hello 

FYI: I have gone to my Azure Saleor instance (since the above trace message is from Azure) and captured the output of the command by: 
D:\home\python364x64\Scripts\pip.exe freeze >capture.txt

[capture.txt](https://github.com/mirumee/saleor/files/2125247/capture.txt)
 
Hope this helps

**Comment by NyanKiyoshi** [comment]
The stack you sent us:
```
File "D:\home\python364x64\Lib\site-packages\graphene_django_init.py", line 1, in
from .types import (
File "D:\home\python364x64\Lib\site-packages\graphene_django\types.py", line 4, in
from graphene import Field
File "D:\home\python364x64\Lib\site-packages\graphene_init.py", line 3, in
from .types import (
File "D:\home\python364x64\Lib\site-packages\graphene\types_init.py", line 2, in
from graphql import ResolveInfo
ImportError: cannot import name 'ResolveInfo'
```

> `File "D:\home\python364x64\Lib\site-packages\graphene_init.py", line 3, in`

I wonder where is `graphene_init.py` coming from? That's odd, and I can't find it and reproduce it on Windows. Could you try to rename it?

`D:\home\python364x64\Lib\site-packages\graphene_init.py` -> `D:\home\python364x64\Lib\site-packages\graphene_init.old`

And send us the resulting stack.

**Comment by NyanKiyoshi** [comment]
I'm trying to see where is the possible circular import coming from but that's really odd.

**Comment by critiquecom** [comment]
Hello

Your comments are encouraging indeed! 
I will get back you with the results as soon as I can - within the day. Have some  meeting and project commitments to attend to first .

**Comment by critiquecom** [comment]
Hello 

As requested have changed the graphene   __init__.py  file extension to   __init__.pyOLD

A new  traceback has resulted as below. Hope this helps to narrow the problem down:

Traceback (most recent call last):
  File "run_waitress_server.py", line 9, in <module>
    application = get_wsgi_application()
  File "D:\home\python364x64\Lib\site-packages\django\core\wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "D:\home\python364x64\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\home\python364x64\Lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "D:\home\python364x64\Lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "E:\A\_work\79\b\source_packages\python.3.6.4\tools\Lib\importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\home\python364x64\Lib\site-packages\graphene_django\__init__.py", line 1, in <module>
    from .types import (
  File "D:\home\python364x64\Lib\site-packages\graphene_django\types.py", line 4, in <module>
    from graphene import Field
ImportError: cannot import name 'Field'

**Comment by critiquecom** [comment]
Hello  
In the above trace listing  the reference to E: drive path is interesting. I am not sure what this means.
I plan to repeat your suggested change on the Saleor instance running under PTVS and see what that trace produces as well. 

Not sure if this will help?

**Comment by NyanKiyoshi** [comment]
What is `E:\A_work\79\b\source_packages\`?

**Comment by critiquecom** [comment]
Hello
Have searched he Internet Found this clue on the Azure GitHub. I have installed the latest python as an extension after following the Azure instructions 
https://github.com/Azure/azure-python-siteextensions
 This is the build.bat file
@setlocal
@if "%~1" EQU "" goto usage
@set D=%~dp0
@if not defined OUTDIR set OUTDIR=%D%
@set NUGET="%D%Tools\nuget.exe"
@set CONTENT=%OUTDIR%\%~3\content\python%~3
%NUGET% install %1 -Version %2 -OutputDirectory "%OUTDIR%\source_packages"
@set PY="%OUTDIR%\source_packages\%~1.%~2\tools\python.exe"
@rem For older versions of Python, overwrite bdist_wininst to allow setuptools
@rem to execute its install_scripts command without crashing.
copy /Y "%D%Tools\distutils.command.bdist_wininst.py" "%OUTDIR%\source_packages\%~1.%~2\tools\Lib\distutils\command\bdist_wininst.py"
@rmdir /q /s "%CONTENT%" 2> nul
%PY% -m pip install -U pip setuptools certifi wfastcgi
%PY% "%D%Tools\copy_py.py" %3 "%CONTENT%\\"
@if errorlevel 1 exit /B
@if not exist "%OUTDIR%\Common" mkdir "%OUTDIR%\Common" && copy /Y "%D%Common\*" "%OUTDIR%\Common"
@if not exist "%OUTDIR%\%3\content\install.cmd" copy /Y "%D%%3\content\*" "%OUTDIR%\%3\content"
@if not exist "%OUTDIR%\packages" mkdir "%OUTDIR%\packages"
%NUGET% pack -NoPackageAnalysis "%D%%3\azureappservice-python%~3.nuspec" -OutputDirectory "%OUTDIR%\packages" -BasePath "%OUTDIR%\%3"
@if not errorlevel 1 rmdir /q /s "%CONTENT%"
@exit /B 0
:usage
@echo Usage: build.bat [package name] [package version] [version tag]
@echo.
@echo The package will be installed from Nuget and used to generate the site extension
@echo from itself.
@echo.
@echo Examples:
@echo.
@echo     build.bat python 3.6.4 364x64
@echo     build.bat python2x86 2.7.14 2714x86


Also I ran the PTVS debugger on my local instance of Saleor running on a windows 10 machine (Surface pro 3) after renaming the graphene init.py file. The following is the debugger trace:

pydev debugger: starting

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 111, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\debugger.py", line 36, in debug
    run(address, filename, *args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\_main.py", line 47, in run_file
    run(argv, addr, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\_main.py", line 98, in _run
    _pydevd.main()
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\pydevd\pydevd.py", line 1628, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\pydevd\pydevd.py", line 1035, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\pydevd\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\chris\source\repos\DjangoWebSaleor1\DjangoWebSaleor1\saleor\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\chris\source\repos\DjangoWebSaleor1\DjangoWebSaleor1\saleor\env\Lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Users\chris\source\repos\DjangoWebSaleor1\DjangoWebSaleor1\saleor\env\Lib\site-packages\django\core\management\__init__.py", line 347, in execute
    django.setup()
  File "C:\Users\chris\source\repos\DjangoWebSaleor1\DjangoWebSaleor1\saleor\env\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\chris\source\repos\DjangoWebSaleor1\DjangoWebSaleor1\saleor\env\Lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\chris\source\repos\DjangoWebSaleor1\DjangoWebSaleor1\saleor\env\Lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\chris\source\repos\DjangoWebSaleor1\DjangoWebSaleor1\saleor\env\Lib\site-packages\graphene_django\__init__.py", line 1, in <module>
    from .types import (
  File "C:\Users\chris\source\repos\DjangoWebSaleor1\DjangoWebSaleor1\saleor\env\Lib\site-packages\graphene_django\types.py", line 4, in <module>
    from graphene import Field
ImportError: cannot import name 'Field'

Does this help?

**Comment by critiquecom** [comment]
This is the importlib_init_.py file referenced in the debugger trace listing above

[__init__.txt](https://github.com/mirumee/saleor/files/2129297/__init__.txt)

Note have renamed .py to .txt to upload

**Comment by NyanKiyoshi** [comment]
I don't get what is creating this whole mess of circular imports.

I'm gonna try to reproduce it over an [Azure VM](https://azure.microsoft.com/en-us/free/). Any reasons that you are using a Windows VM instead of Linux? (just curious, as Linux would be much simpler, but Windows is still okay).

Feel free to state how you proceed, that would give a better idea on what is creating this mess.

**Comment by NyanKiyoshi** [comment]
Anyway, it seemed like you were able to reproduce it on desktop?

If you have a few minutes, could you give me the steps to follow to reproduce on desktop? Since I'm not familiar with those technologies, it would save me time before being able to start tracing the issue.

I will take a look when I can, hopefully today.

**Comment by critiquecom** [comment]
Hello
By all means I am indeed extremely appreciative you tasking this effort!. I think the quickest approach is to refer you to the articles that I have used to learn to setup python tools on Visual Studio. There are three key ones as below:
https://docs.microsoft.com/en-us/visualstudio/python/managing-python-environments-in-visual-studio
https://docs.microsoft.com/en-us/visualstudio/python/selecting-a-python-environment-for-a-project
https://docs.microsoft.com/en-us/visualstudio/python/quickstart-03-python-in-visual-studio-project-from-repository

The outcome is a clone install of Saleor packages under a virtual environment with a selected version of python. I used python 364x64. 

Note: I had previously setup a PostgreSQL database noting the URL, database name and password on AZURE  
The extra steps are:
1) editing the SETTING file database entry logiin/password details to point to the PostgreSQL database

2)set up the SECRET_KEY = ' xxxxxx' in the environment multi-text field in the debug settings . I can explain this in detail if required in a later comment.

3) I run "python manage.py  migrate"  from "Open command prompt" (right click on the python project name in bold saleor) to display pull down menu). I recall I may have experienced the "resolveInfo error" here so investigated using the Debug capability of Visual Studio  

Hope the above helps..

**Comment by NyanKiyoshi** [comment]
I cannot manage to reproduce it.

1. Created a python virtual environment through VS;
2. Installed dependencies through the command prompt (`cmd`) using the creation python environment;
3. Applied the migrations to the database using the environment with the command prompt;
4. Ran the project through the run button both with and without debugging.

**Comment by critiquecom** [comment]
Woohoo!  Great news indeed! Thanks for proving this
Can you indulge me a little.. Can you:
1) .Advise wat NPM version you used This is one additional step that I forgot to mention that needs to be installed along with the Python environment
2) Set some breakpoints in the area of code where my solution fails so I know what "should" see. Is this possibe

**Comment by NyanKiyoshi** [comment]
1. I'm using `npm 5.6.0`;
2. I'm not sure what you want.

**Comment by critiquecom** [comment]
Hello
Thanks for the version number of npm.
I no longer need answers to 2).   I have since performed a repeat install under PTVS as you have done.
This time the process worked without error. I have completed the  database migration. I will continue with the rest of the installation steps but see no reason to keep this issue open. Apologies for essentially wasting your time on trivia

**Comment by Pacu2** [comment]
Glad to see this resolved!
