### ISSUE TITLE
"collectstatic" fails on local docker set-up

### ISSUE THREAD

**Issue by dinofizz** [mirumee/saleor#2568]
### What I'm trying to achieve

Trying to get set-up for local dev using Docker.

### Steps to reproduce the problem
1. Cloned the repo. Stay in master branch. I'm on 232a743bc.
2. run `docker-compose build` - this succeeds
3. run `docker-compose run web python3 manage.py migrate` - this succeeds
4. run `docker-compose run web python3 manage.py collectstatic` - this fails with:

```
Starting saleor_search_1 ... done
Starting saleor_redis_1  ... done
Starting saleor_db_1     ... done
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 189, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 105, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/finders.py", line 125, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/utils.py", line 28, in get_files
    directories, files = storage.listdir(location)
  File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 313, in listdir
    for entry in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/app/saleor/static/assets'
```

### What I expected to happen
collectstatic to succeed

### Additional details

This is what I see during the docker-compose build relating to static asset copying:

```
Copying '/app/saleor/static/assets/pass-invisible.d5a74fda0ae925038d3d4a2b9cb030d3.svg'
Copying '/app/saleor/static/assets/insert_photo.497fe7788e4adeb99de29152704b8d32.svg'
Copying '/app/saleor/static/assets/Lato-Regular.183bf2570509b4588f48227a1799c1bc.woff2'
... and many more /assets
```

If I list the contents of the /app/saleor/static directory I see:

```
$ docker-compose run web ls -al /app/saleor/static                              
Starting saleor_redis_1 ... done
Starting saleor_search_1 ... done
total 36 saleor_db_1     ... done
drwxr-xr-x  9 1000 1000 4096 Aug 12 12:12 .
drwxr-xr-x 19 1000 1000 4096 Aug 12 12:12 ..
drwxr-xr-x  5 1000 1000 4096 Aug 12 12:12 dashboard
drwxr-xr-x  2 1000 1000 4096 Aug 12 12:12 favicons
drwxr-xr-x  2 1000 1000 4096 Aug 12 12:12 fonts
drwxr-xr-x  2 1000 1000 4096 Aug 12 12:12 images
drwxr-xr-x  4 1000 1000 4096 Aug 12 12:12 js
drwxr-xr-x  8 1000 1000 4096 Aug 12 12:12 placeholders
drwxr-xr-x  4 1000 1000 4096 Aug 12 12:12 scss
```

No "assets" folder there.

**System information**

```$ uname -a                      
Linux archd 4.17.14-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 9 11:56:50 UTC 2018 x86_64 GNU/Linux
$ docker -v               
Docker version 18.05.0-ce, build f150324782
$ docker-compose -v
docker-compose version 1.22.0, build unknown
```

**Comment by f3n1Xx** [comment]
@dinofizz hey man, you have to use npm run build-assets to initialise it. For docker, i guess you add this command in docker file, maybe it's not included when you composed. 
Hope it works bro, take care :)

**Comment by f3n1Xx** [comment]
npm run build-assets is not running, you need to check when it's being called during build and fix it, i fixed it :D

**Comment by f3n1Xx** [comment]
by chance did you made any changes to Dockerfile?

**Comment by f3n1Xx** [comment]
collectstatic was executed in previous line "docker-compose build"; it's included in Dockerfile, so i guess that line is not getting executing, check logs if it did execute, assets folder will be made at that instance.
