### ISSUE TITLE
AppRegistryNotReady: Apps aren't loaded yet

### ISSUE THREAD

**Issue by tkwon** [mirumee/saleor#2621]
### What I'm trying to achieve
New installation on Windows 10.
Django 2.0.3
Python 3.5.2

### Steps to reproduce the problem
1. follow install steps
2. install postgres 9.6 on windows 10
3. python manage.py migrate

###Traceback
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\core\management\__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\core\management\__init__.py", line 216, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\core\management\__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "C:\Users\Tom\projects\saleor\env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\core\management\commands\migrate.py", line 12, in <module>
    from django.db.migrations.autodetector import MigrationAutodetector
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\db\migrations\autodetector.py", line 11, in <module>
    from django.db.migrations.questioner import MigrationQuestioner
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\db\migrations\questioner.py", line 9, in <module>
    from .loader import MigrationLoader
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\db\migrations\loader.py", line 8, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\db\migrations\recorder.py", line 9, in <module>
    class MigrationRecorder:
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\db\migrations\recorder.py", line 22, in MigrationRecorder
    class Migration(models.Model):
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\db\models\base.py", line 100, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\apps\registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\Tom\projects\saleor\env\lib\site-packages\django\apps\registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by Pacu2** [comment]
Could you check if `SECRET_KEY was set up properly?

**Comment by tkwon** [comment]
I have set SECRET_KEY explicitly inside settings.py.
For example: 
`
SECRET_KEY = 'dksl3l2kcxl..sdlsdl3'`

**Comment by tkwon** [comment]
Ok found out my secret key setting was *before* the os.environ[...].
Sorry for the mistake!
