### ISSUE TITLE
BUG stripe payment: AttributeError: module 'stripe.util' has no attribute 'json'

### ISSUE THREAD

**Issue by xponrails** [mirumee/saleor#2740]
### What I'm trying to achieve
…
I've tried to pay with Stripe (sandbox)
### Steps to reproduce the problem
1. used the Stripe javascript popup connected to a sandbox
2. 

### What I expected to happen
…

### Screenshots

```
ERROR saleor.order.views Error communicating with the payment gateway [PID:2821:Thread-270]
Traceback (most recent call last):
  File "/Users/stefano/Projects/Python/devinterface/saleor/saleor/order/views.py", line 117, in start_payment
    form = payment.get_form(data=request.POST or None)
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/payments/models.py", line 122, in get_form
    return provider.get_form(self, data=data)
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/payments/stripe/__init__.py", line 30, in get_form
    form.save()
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/payments/stripe/forms.py", line 59, in save
    self.payment.attrs.charge = stripe.util.json.dumps(self.charge)
AttributeError: module 'stripe.util' has no attribute 'json'
ERROR saleor.order.views Error communicating with the payment gateway [PID:2821:Thread-270]
Traceback (most recent call last):
  File "/Users/stefano/Projects/Python/devinterface/saleor/saleor/order/views.py", line 117, in start_payment
    form = payment.get_form(data=request.POST or None)
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/payments/models.py", line 122, in get_form
    return provider.get_form(self, data=data)
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/payments/stripe/__init__.py", line 30, in get_form
    form.save()
  File "/Users/stefano/.virtualenvs/saleor/lib/python3.6/site-packages/payments/stripe/forms.py", line 59, in save
    self.payment.attrs.charge = stripe.util.json.dumps(self.charge)
AttributeError: module 'stripe.util' has no attribute 'json'
```

**System information**
Operating system:  OSX
Browser:

**Comment by patrys** [comment]
Are you sure you have the same version of `stripe` installed that is listed in `requirements.txt`? We've only recently merged a pull request that makes `django-payments` compatible with the latest release and it's not released yet.

**Comment by xponrails** [comment]
Yes, stripe-2.5.0

**Comment by xponrails** [comment]
the problem is that stripe 2.5.0 doesn't have a json inside util.py
probably django-payments uses a wrong version of stripe

**Comment by patrys** [comment]
@Pacu2 I think you caused it in a68be9e482 by bumping the Stripe version in `requirements.txt`. We should downgrade Stripe or release a new version of `django-payments` and depend on that.

**Comment by xponrails** [comment]
Is this issue still open?

**Comment by patrys** [comment]
I think nothing changed, @Pacu2 is currently on holiday.

**Comment by Pacu2** [comment]
On it :)

**Comment by Pacu2** [comment]
I've listed an issue to update the stripe version for django-payments in https://github.com/mirumee/django-payments/issues/195
