### ISSUE TITLE
Run NPM run build-assets error

### ISSUE THREAD

**Issue by OneBoYun** [mirumee/saleor#2804]
错误内容“
ERROR in ./saleor/static/js/storefront.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean.
    at validatePlugins (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/parser/lib/index.js:10407:13)
    at getParser (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/parser/lib/index.js:10464:5)
    at parse (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/parser/lib/index.js:10448:12)
    at parser (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
    at runSync (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at transformSync (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transform.js:43:38)
    at Object.transform (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transform.js:22:38)
    at transpile (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/babel-loader/lib/index.js:173:20)

ERROR in ./saleor/static/dashboard/js/dashboard.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean.
    at validatePlugins (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/parser/lib/index.js:10407:13)
    at getParser (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/parser/lib/index.js:10464:5)
    at parse (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/parser/lib/index.js:10448:12)
    at parser (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
    at runSync (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at transformSync (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transform.js:43:38)
    at Object.transform (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transform.js:22:38)
    at transpile (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/babel-loader/lib/index.js:173:20)

ERROR in ./saleor/static/dashboard/js/document.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean.
    at validatePlugins (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/parser/lib/index.js:10407:13)
    at getParser (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/parser/lib/index.js:10464:5)
    at parse (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/parser/lib/index.js:10448:12)
    at parser (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
    at runSync (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at transformSync (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transform.js:43:38)
    at Object.transform (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/@babel/core/lib/transform.js:22:38)
    at transpile (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/allen_by/Desktop/project/myproject/saleor/saleor/node_modules/babel-loader/lib/index.js:173:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! saleor@0.0.0 build-assets: `webpack -p`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the saleor@0.0.0 build-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/allen_by/.npm/_logs/2018-09-08T17_17_54_926Z-debug.log”

node -V 10.10
npm -v 6.4.1

**Comment by mmmcorpsvit** [comment]
i have same errors, for npm build need around 1.2 Gb free RAM!
so i add swap to my 1 Gb VPS

**Comment by maxpaynestory** [comment]
my npm install also work with node version 8, maybe try with that.

**Comment by HardMaxwellRobo** [comment]
I have same error, but I trying add some swapfile with 4G and using "--max-old-space-size=4096" and still have errors. I used nodejs 10.x and 8.x and npm 6.4.1. Here is my log file: 
<img width="712" alt="printscreen1" src="https://user-images.githubusercontent.com/32393876/45819828-fe07df80-bced-11e8-97e2-1906f3f5828c.png">

Thanks for help.

**Comment by ajostergaard** [comment]
I'm not sure it's the same error - mine is a little more explicit:

```
FATAL ERROR: NewSpace::Rebalance Allocation failed - process out of memory
```

But, as you'd expect, adding swap helped. :)
