### ISSUE TITLE
Cannot find module '@babel/preset-es2015' on 'npm run build-assets'

### ISSUE THREAD

**Issue by the-bionic** [mirumee/saleor#2822]
### What I'm trying to achieve
I was trying to build assets so I can start up the web server on an Ubuntu machine and I got this error
```
ERROR in ./saleor/static/js/storefront.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/preset-es2015' from '/home/bionic/coding/OpenSource/saleor'
    at Function.module.exports [as sync] (/home/bionic/coding/OpenSource/saleor/node_modules/resolve/lib/sync.js:43:15)
    at resolveStandardizedName (/home/bionic/coding/OpenSource/saleor/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePreset (/home/bionic/coding/OpenSource/saleor/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
    at loadPreset (/home/bionic/coding/OpenSource/saleor/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
    at createDescriptor (/home/bionic/coding/OpenSource/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/home/bionic/coding/OpenSource/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/home/bionic/coding/OpenSource/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/home/bionic/coding/OpenSource/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/home/bionic/coding/OpenSource/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/home/bionic/coding/OpenSource/saleor/node_modules/@babel/core/lib/config/config-chain.js:315:26)
    at /home/bionic/coding/OpenSource/saleor/node_modules/@babel/core/lib/config/config-chain.js:278:7
    at buildRootChain (/home/bionic/coding/OpenSource/saleor/node_modules/@babel/core/lib/config/config-chain.js:118:22)
    at loadPrivatePartialConfig (/home/bionic/coding/OpenSource/saleor/node_modules/@babel/core/lib/config/partial.js:57:55)
    at Object.loadPartialConfig (/home/bionic/coding/OpenSource/saleor/node_modules/@babel/core/lib/config/partial.js:82:18)
    at Object.<anonymous> (/home/bionic/coding/OpenSource/saleor/node_modules/babel-loader/lib/index.js:105:26)
    at Generator.next (<anonymous>)
    at step (/home/bionic/coding/OpenSource/saleor/node_modules/babel-loader/lib/index.js:3:221)
    at _next (/home/bionic/coding/OpenSource/saleor/node_modules/babel-loader/lib/index.js:3:409)
    at /home/bionic/coding/OpenSource/saleor/node_modules/babel-loader/lib/index.js:3:477
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/bionic/coding/OpenSource/saleor/node_modules/babel-loader/lib/index.js:3:97)
    at Object._loader (/home/bionic/coding/OpenSource/saleor/node_modules/babel-loader/lib/index.js:183:18)
    at Object.loader (/home/bionic/coding/OpenSource/saleor/node_modules/babel-loader/lib/index.js:50:18)
    at Object.<anonymous> (/home/bionic/coding/OpenSource/saleor/node_modules/babel-loader/lib/index.js:45:12)

```

### Steps to reproduce the problem
1 Clone the repo
2 Install dependencies -- npm install
3 Build assets -- npm run build-assets

### What I expected to happen
To start the webpack dev server

**System information**
Operating system: Ubuntu

**Comment by the-bionic** [comment]
After many hours of trial and error, I upgraded npm from 3.x to 6.x and the error disappeared. Closed. It will also help adding this in the docs.
