### ISSUE TITLE
Cant install a fresh copy of saleor if I remove the migrations

### ISSUE THREAD

**Issue by hassanzadeh** [mirumee/saleor#2875]
### What I'm trying to achieve
I'm trying to install a fresh and independent copy of saleor. I removed all the files in the /migrations/ folders and tried to install 

I get the following error which is very weird, does it mean that you are tweaking the migration files in away that now your code is really dependent on them?

(venv) webdev@ip-172-31-38-116:/www/saleor$ python manage.py migrate
Operations to perform:
  Apply all migrations: auth, contenttypes, django_celery_results, django_prices_openexchangerates, django_prices_vatlayer, impersonate, sessions, sites, social_django
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying django_celery_results.0001_initial... OK
  Applying django_prices_openexchangerates.0001_initial... OK
  Applying django_prices_openexchangerates.0002_auto_20160329_0702... OK
  Applying django_prices_openexchangerates.0003_auto_20161018_0707... OK
  Applying django_prices_openexchangerates.0004_auto_20170316_0944... OK
  Applying django_prices_vatlayer.0001_initial... OK
  Applying django_prices_vatlayer.0002_ratetypes... OK
  Applying django_prices_vatlayer.0003_auto_20180316_1053... OK
  Applying impersonate.0001_initial...Traceback (most recent call last):
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "account_user" does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 106, in __exit__
    self.execute(sql)
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/www/rbook.com/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "account_user" does not exist

**Comment by hassanzadeh** [comment]
note that with migration files it all work.
The error appears after I run 
python manage.py migrate

**Comment by Pacu2** [comment]
Could you try squashing the migrations, instead of removing them?

**Comment by hassanzadeh** [comment]
can you explain what is squashing? I found a solution but not sure why it works:
if I run python manage.py makemigrations account, BEFORE manage.py migrate, then it works,
is that a Django bug?

**Comment by Pacu2** [comment]
@hassanzadeh 
Take a look at
https://docs.djangoproject.com/en/2.1/topics/migrations/#migration-squashing

What was the reason in the first place, for removing the migrations?
