### ISSUE TITLE
STRICTNESS does not exist in my Django 2.1.1

### ISSUE THREAD

**Issue by hassanzadeh** [mirumee/saleor#2886]
### What I'm trying to achieve
I'm trying to compile your code with my Django 2.1.1 and python 3.5.2 from the demo branch. In your graphql/core/filters you are trying to import STRICTNESS from Django_filters but that does not exist, probably deprecated.

### What I expected to happen
compilation fails.

### Screenshots

  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_mdule
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/www/rbook.com/rbook/urls.py", line 17, in <module>
    from .graphql.api import schema
  File "/www/rbook.com/rbook/graphql/api.py", line 14, in <module>
    from .menu.mutations import (
  File "/www/rbook.com/rbook/graphql/menu/mutations.py", line 7, in <module>
    from ..product.types import Category, Collection
  File "/www/rbook.com/rbook/graphql/product/types.py", line 13, in <module>
    from ..core.filters import DistinctFilterSet
  File "/www/rbook.com/rbook/graphql/core/filters.py", line 2, in <module>
    from django_filters.constants import STRICTNESS
ImportError: cannot import name 'STRICTNESS'

**Comment by Pacu2** [comment]
Whats the version of django filters youre using?

**Comment by NyanKiyoshi** [comment]
The demo branch is not compatible django 2.1 only master is as of now. You can fix the requirements by doing `pip install -r requirements.txt -U`.

**Comment by hassanzadeh** [comment]
Thanks, are you sure it is not consistent, because I noticed that Django-filters was not installed due to permission issues. Should I not bother to see if it may work?

**Comment by NyanKiyoshi** [comment]
Seems like django-filters is installed but is not the correct version. And still, the demo branch is not compatible django 2.1 as of now. 

This is typically the error you get for that.

Are you sure you didn't install the dependencies (`pip install ...`) on the master branch then switched to the `demo` branch? Anyway, doing `pip install -r requirements.txt -U` should do the trick. If not, please send the output of `pip freeze` below.

**Comment by hassanzadeh** [comment]
no I first switched then installed. Should I do it the other way round?
so what is the latest django I can use with demo?

**Comment by Pacu2** [comment]
@hassanzadeh Probably same as listed inside of requirements.txt of the demo branch, we are always using latest software version available.

**Comment by NyanKiyoshi** [comment]
You should install the requirements from the `requirements.txt` file of the demo branch if you want to use that branch (`pip install -r requirements.txt -U`, so).

As of now, it's the 2.0 branch of django, thus `2.0.8`.

**Comment by hassanzadeh** [comment]
Thanks.

**Comment by hassanzadeh** [comment]
I have a relatively similar issue with the master, IF is remove the provided migrations. I don't understand why those intermediary files have to be there. I need to adapt the code therefore, I assume that the django source code should be self sufficient to start adapting the code. Not sure why I get the following error when I migrate 👍 

Request Method: | GET
-- | --
http://rug-book.com:8000/en/
2.1.1
ProgrammingError
relation "site_sitesettings" does not exist LINE 1: ...", "site_sitesettings"."default_weight_unit" FROM "site_site...                                                              ^
/www/rug-book.com/venv/lib/python3.5/site-packages/django/db/backends/utils.py in _execute, line 85
/www/rug-book.com/venv/bin/python
3.5.2
['/www/saleor',  '/usr/lib/python35.zip',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/usr/lib/python3.5/lib-dynload',  '/www/rug-book.com/venv/lib/python3.5/site-packages',  '/www/saleor']
Mon, 17 Sep 2018 17:50:35 -0500

**Comment by hassanzadeh** [comment]
More detailed error from console:
ERROR django.request Internal Server Error: /en/ [PID:23039:Thread-3]
Traceback (most recent call last):
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "site_sitesettings" does not exist
LINE 1: ...", "site_sitesettings"."default_weight_unit" FROM "site_site...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/www/saleor/saleor/core/middleware.py", line 80, in middleware
    request.site = Site.objects.get_current()
  File "/www/saleor/saleor/site/patch_sites.py", line 24, in new_get_current
    site = self.prefetch_related('settings').filter(pk=site_id)[0]
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/models/query.py", line 302, in __getitem__
    qs._fetch_all()
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1188, in _fetch_all
    self._prefetch_related_objects()
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/models/query.py", line 723, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1569, in prefetch_related_objects
    obj_list, additional_lookups = prefetch_one_level(obj_list, prefetcher, lookup, level)
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1682, in prefetch_one_level
    prefetcher.get_prefetch_queryset(instances, lookup.get_current_queryset(level)))
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 368, in get_prefetch_queryset
    for rel_obj in queryset:
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/models/query.py", line 268, in __iter__
    self._fetch_all()
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/www/r-book.com/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "site_sitesettings" does not exist
LINE 1: ...", "site_sitesettings"."default_weight_unit" FROM "site_site...
      
~                                                                                                                                                                                                                                                                                                                             
~                                                                                                                                                                                                                                                                                                                             
~

**Comment by hassanzadeh** [comment]
Thanks, let me redescribed the problem,
Yes, if I run the migrations that are already there everything work, but if I don't include them and simply make migrations from the source code then even though the migrate command succeeds, the website does not launch and that error is thrown, because your code is contingent upon the preloaded data.

**Comment by Pacu2** [comment]
@hassanzadeh What's the reason for not including the migrations? We are using `SiteSettings` model for setting the dynamic settings (eg. authorization keys configuration).

**Comment by hassanzadeh** [comment]
Nothing, but it's kind of weird that the if we don't have the initial data then the code won't work.

**Comment by Pacu2** [comment]
It's not possible in all the cases. `SiteSettings`(our custom dynamic-settings model) is linked to the `Site` instance (which is part of the Django apps). It needs to be assigned manually. 

If you want to minimize the number of migrations, please squash them instead of removing them and regenerating.

**Comment by hassanzadeh** [comment]
Ok, got you, thanks for the help.
