### ISSUE TITLE
Unable To Start Server On Second Try

### ISSUE THREAD

**Issue by johnchendev** [mirumee/saleor#3332]
### What I'm trying to achieve
…

Start Saleor server on second try.

### Steps to reproduce the problem
1. cd/saleor
2. python manage.py runserver

### What I expected to happen
…server starts as per first run

### Screenshots

**System information**
Operating system: Mac Mojave
Browser: Chrome

### Details

Hi guys, it's funny why this is happening, but I can run Saleor on the browser loading everything as per normal (beautiful store by the way).

However, as soon as I close my terminal, and try to start my server again, it doesn't load at all.

I'm really confused and I hope you guys can help me out.

Here's the Traceback:

(DjangoEnv) johnchen@JMA:~/Desktop/Projects$ cd saleor/
(DjangoEnv) johnchen@JMA:~/Desktop/Projects/saleor$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/johnchen/Desktop/Projects/DjangoEnv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/johnchen/Desktop/Projects/DjangoEnv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/johnchen/Desktop/Projects/DjangoEnv/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/johnchen/Desktop/Projects/DjangoEnv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/Users/johnchen/Desktop/Projects/DjangoEnv/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/Users/johnchen/Desktop/Projects/DjangoEnv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 67, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/Users/johnchen/Desktop/Projects/DjangoEnv/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/Users/johnchen/Desktop/Projects/DjangoEnv/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/johnchen/Desktop/Projects/DjangoEnv/lib/python3.7/site-packages/django/conf/__init__.py", line 126, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")

##Additional Notes

Nothing has been edited at all - everything is a fresh install off Saleor's instructions for MacOs.

I'm really confused, because if it's running well on the **first** try, why isn't it working on the second (and above) try?

Please help, thank you so much in advance!

**Comment by johnchendev** [comment]
Hi @Pacu2 , thanks for the quick reply. Not sure what you mean by that - is there any reference material that you can refer me to, please? Thanks a lot

**Comment by NyanKiyoshi** [comment]
@johnchendev you can refer to the [documentation](http://docs.getsaleor.com/en/latest/gettingstarted.html) in the guide of your according OS.

**Comment by johnchendev** [comment]
@NyanKiyoshi thanks for your reply. However, I follow these instructions (MacOS), and was able to get the server running on the first try. As per my reply to @Pacu2, the problem arises when I close the terminal, reopen a session, and load: 

`python manage.py runserver`

That's where the Traceback above happens :)

**Comment by NyanKiyoshi** [comment]
@johnchendev I guess you did:
1. `export SECRET_KEY='<mysecretkey>'`;
1. Closed your terminal;
1. Opened it back;
1. Ran `runserver` and expected the `SECRET_KEY` to be set?

If so, no, that's not how that works. The environment variables (`SECRET_KEY`) are lost whenever you close your terminal's session. So, whenever you are reopening your terminal, you need to set the `SECRET_KEY` again.

There are multiple ways to counter this issue. Here are some easy ones:
1. Set the secret key as you run `runserver`, like that (on the same single line): `SECRET_KEY='hello' python manage.py runserver`;
1. Create a bash shell script `start.sh`, with the above command or with `export SECRET_KEY=hello`;
1. Create a `.env` file with: `export SECRET_KEY=hello` and whenever you want to run the server, run `source .env` then, `python manage.py runserver`.

**Comment by johnchendev** [comment]
@NyanKiyoshi thanks again! 

I did another method which I think might be wrong - no harm trying though.

1. I went to /saleor/settings.py
2. Added in my secret key beneath : SECRET_KEY = os.environ.get('SECRET_KEY')
3. Ran the server again and it worked! 

@NyanKiyoshi I'm going to try your methods, and report back. But for the sake of helping a newbie out, which one do you think is the most secure and best way?

Thanks again!

**Comment by NyanKiyoshi** [comment]
Whatever you prefer/ are the more comfortable with. The issue with editing the `settings.py` file is that it may create conflict with the git repository. It's easier to manage untracked (or tracked) custom files than a tracked project file that is subject to change.

Then, once you get Saleor into production, you will probably use a file, like `production.env` that you will `source` whenever you start your web server (uwsgi, apache, nginx, ...). That's, for example, the way I deal with environment variables in production.

**Comment by johnchendev** [comment]
@NyanKiyoshi i hear you. 

Assuming I were to follow point 2 (Create a .env file with: export SECRET_KEY=hello and whenever you want to run the server, run source .env then, python manage.py runserver.) 

What are some references would you recommend (if you had the time) for me to go about create these Env files?

**Comment by NyanKiyoshi** [comment]
What do you mean by 'references'?

**Comment by johnchendev** [comment]
References as in - tutorials, step by steps 🍡

**Comment by NyanKiyoshi** [comment]
Alright. That doesn't really need any tutorial. Here are some explanations:

- First of all, you create a file, let's say: `development.env`, in the Saleor project directory;
- Then, in it, you put:
  ```bash
  export SECRET_KEY='development mode!'
  export WHATEVER_ENVIRONMENT_VARIABLE_I_WANT_TOO='True'
  ```
- Whenever you open a terminal, you will do a `source development.env` (or `. development.env`, that's the short hand for `source`). Now you can run whatever you want with `python manage.py`.

So, now, explanation time. You are on MacOS. MacOS is a Unix based OS, which uses `bash` as a terminal interpreter (🎉). You have your file `environment.env` that contains `bash` code, this code sets the environment variables (you can put anything you want though, but that would make little to no sense).
Then, you have the `source <file>` command (or the short-hand command: `. <file>`), this tells your bash terminal session to run the `<file>` directly into your bash session (terminal). It's just as if you were copy/pasting the content of this file into your bash session. It's just that.

That's it. It runs everything in the given file into your terminal session.

If you were, for example, to run the `sh` (or `bash`) command instead of `source` (or `.`), it would create a new sub-shell session, child of your terminal's bash session, and would run the file's content into this child session. So, it would be equal to open a new terminal, doing a `source` a closing it. Thus, you lose the environment variables, as the session is destroyed (and not the current one).

You can give it a try. Doing something like that for example:
1. `sh development.env && env | grep SECRET_KEY`, that will create a sub-shell and not add the environment variable `SECRET_KEY` into your current session;
1. Now, do `source development.env && env | grep SECRET_KEY`, that will run into your current shell session, and set environment variable `SECRET_KEY` into your current session.

You can also do that into your shell: `echo $$`, that will show your shell's PID (Process ID). Then, in `environment.env`, you can put `echo $$`. And then try to run the file with both `sh` and `source`. You should get that:
1. Run `echo $$`, e.g. outputs: 1234, you current shell session's PID;
1. `sh environment.env`, outputs: 2345, its shell session's PID;
1. `source environment.env`, outputs: 1234, you current shell session's PID.
