### ISSUE TITLE
Elastic Search missing root certificates

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#3354]
### What I'm trying to achieve
I'm trying to integrate elastic search into a saleor app on Heroku. Following the instructions on the saleor docs, I ran `heroku run python manage.py search_index --create`.

### Steps to reproduce the problem
1. Deploy a saleor app on heroku
2. Run `heroku addons:create bonsai:sandbox-6 --version=5.4`
3. Run `heroku run python manage.py search_index --create`

### What I expected to happen
I expected the search index to be created.

### Screenshots
```
heroku run python manage.py search_index --create -a
Running python manage.py search_index --create on ⬢ saleor-tmp-9fc86b... up, run.5535 (Free)
Creating index 'users'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python3.6/site-packages/django_elasticsearch_dsl/management/commands/search_index.py", line 128, in handle
    self._create(models, options)
  File "/app/.heroku/python/lib/python3.6/site-packages/django_elasticsearch_dsl/management/commands/search_index.py", line 84, in _create
    index.create()
  File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch_dsl/index.py", line 203, in create
    self.connection.indices.create(index=self._name, body=self.to_dict(), **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch_dsl/index.py", line 41, in _get_connection
    return connections.get_connection(self._using)
  File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch_dsl/connections.py", line 91, in get_connection
    return self.create_connection(alias, **self._kwargs[alias])
  File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch_dsl/connections.py", line 66, in create_connection
    conn = self._conns[alias] = Elasticsearch(**kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 170, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch/transport.py", line 108, in __init__
    self.set_connections(hosts)
  File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch/transport.py", line 157, in set_connections
    connections = list(zip(connections, hosts))
  File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch/transport.py", line 154, in _create_connection
    return self.connection_class(**kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 91, in __init__
    raise ImproperlyConfigured("Root certificates are missing for certificate "
elasticsearch.exceptions.ImproperlyConfigured: Root certificates are missing for certificate validation. Either pass them in using the ca_certs parameter or install certifi to use it automatically.
```

### Guesses
This appears to be a bug in elastic search (https://github.com/elastic/elasticsearch-py/issues/669), but it would seem other saleor users have been using elastic search successfully. Perhaps I missed a step?
Additionally, the error says to install `certify`, but I already have `certify` in my pipfile lock, so it's definitely installed.

**Comment by NyanKiyoshi** [comment]
Hi, can you try updating the `elasticsearch` package through `pip`? (`pip install -U elasticsearch`) In the issue you linked, there was a fix release in 6.1.0, Saleor is using 6.0.0 as I can see: https://github.com/mirumee/saleor/blob/d23535ccb32bfad8876c4234c528cf1600d64de7/requirements.txt#L52

That could fix your issue, let us know.

**Comment by khalibloo** [comment]
I tried with 6.1.1 (there's no 6.1.0 on pip) as well as with the latest, 6.3.1. The issue still persists.

**Comment by khalibloo** [comment]
Tried again with a fresh new app. 6.0.0 reproduced the error. Upgrading to 6.1.1 fixed it. I found another issue with uwsgi on windows that I suspect interfered with my earlier attempt. Thanks.
