### ISSUE TITLE
uwsgi build error prevents pipenv locking

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#3355]
### What I'm trying to achieve
I'm simply trying to lock pipfile dependencies. I know uwsgi has issues with windows, but what puzzles me here is that the pipfile clearly says to only install on non-windows platforms. Yet for whatever reason, uwsgi is still being built. I followed the saleor docs on windows installations and installed GTK+ and Windows Build Tools, but that didn't help.

### Steps to reproduce the problem
1. Run `pipenv install` on a saleor app after adding/removing a package (Windows 10)

### What I expected to happen
I expected pipfile lock to be updated.

### Screenshots
```
Creating a virtualenv for this project…
Pipfile: C:\Blah\Blah\Blah\saleor\Pipfile
Using C:/Blah Blah/Python36/python.exe (3.6.7) to create virtualenv…
[ ===] Creating virtual environment...Using base prefix 'C:\\Program Files\\Python36'
New python executable in C:\Users\Someone\.virtualenvs\saleor-Piw0X_d-\Scripts\python.exe
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter C:/Blah Blah/Python36/python.exe

Successfully created virtual environment!
Virtualenv location: C:\Users\Someone\.virtualenvs\saleor-Piw0X_d-
Locking [dev-packages] dependencies…
Success!
Locking [packages] dependencies…
Locking Failed!
Traceback (most recent call last):
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "c:\program files\python36\lib\site-packages\pipenv\utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "c:\program files\python36\lib\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "c:\program files\python36\lib\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_internal\req\req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_internal\utils\misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Someone\AppData\Local\Temp\tmpl28qg6p3build\uwsgi\
File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "c:\program files\python36\lib\site-packages\pipenv\utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "c:\program files\python36\lib\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "c:\program files\python36\lib\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_internal\req\req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_internal\utils\misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Someone\AppData\Local\Temp\tmpl28qg6p3build\uwsgi\
```

**System information**
Operating system: Windows 10 (64 bit)
Browser: Firefox 63

**Comment by jxltom** [comment]
Thanks for sharing!
