### ISSUE TITLE
Service 'web' failed to build prevent pipenv locking

### ISSUE THREAD

**Issue by ndh150** [mirumee/saleor#3546]
### What I'm trying to achieve
+ build and run the containers using docker-compose

### Steps to reproduce the problem
1. Set up and test Saleor.
2. For Customization, I am at the step creating Containers but stuck with this error. 
I am using Windows 10 Home so I just install Docker Toolbox. I ran the following commands:
$ docker-machine start defaults 
$ docker-machine env
$ docker-compose build
db uses an image, skipping
redis uses an image, skipping
Building web
Step 1/35 : FROM python:3.6 as build-python
 ---> 749d36d00e00
Step 2/35 : RUN   apt-get -y update &&   apt-get install -y gettext &&   apt-get clean &&   rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 0be5112659a0
Step 3/35 : RUN pip install pipenv
 ---> Using cache
 ---> 5101633966a2
Step 4/35 : ADD Pipfile /app/
 ---> cca51e3534d6
Step 5/35 : ADD Pipfile.lock /app/
 ---> 223a1b554ecd
Step 6/35 : WORKDIR /app
 ---> Running in d36119b76e5d
Removing intermediate container d36119b76e5d
 ---> 716397cd0b49
Step 7/35 : RUN pipenv install --system --deploy --dev
 ---> Running in 9c3a4696ac24
Your Pipfile.lock (95ca32) is out of date. Expected: (0a753c).
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1874, in do_install
    keep_outdated=keep_outdated
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1192, in do_init
    raise exceptions.DeployException
  File "/usr/local/lib/python3.6/site-packages/pipenv/exceptions.py", line 168, in __init__
    PipenvUsageError.__init__(message=fix_utf8(message), extra=extra, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'self'
ERROR: Service 'web' failed to build: The command '/bin/sh -c pipenv install --system --deploy --dev' returned a non-zero code: 1
a non-zero code: 1

3. I suppose this error occur as "Pipfile.lock (95ca32) is out of date. Expected: (0a753c)." I tried to create a new Pipfile and Pipfile.lock as follows:
$ venv\Scripts\activate 
$ pipenv install -r requirements.txt
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that end. You can set PIPENV_VERBOSITY=-1 to suppress this wvironment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Requirements file provided! Importing into Pipfile…
Pipfile.lock (3de21f) out of date, updating to (95ca32)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Locking Failed!
Traceback (most recent call last):
  File "c:/users/trang/appdata/local/programs/python/python37-32/lib/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "c:/users/trang/appdata/local/programs/python/python37-32/lib/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "c:/users/trang/appdata/local/programs/python/python37-32/lib/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "c:/users/trang/appdata/local/programs/python/python37-32/lib/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\utils.py", line 726,
in resolve_deps
    req_dir=req_dir,
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\utils.py", line 480,
in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\utils.py", line 385,
in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\req\req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\utils\misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\trang\AppData\Local\Temp\tmpl9qz2wyjbuild\uwsgi\
File "c:/users/trang/appdata/local/programs/python/python37-32/lib/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "c:/users/trang/appdata/local/programs/python/python37-32/lib/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "c:/users/trang/appdata/local/programs/python/python37-32/lib/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "c:/users/trang/appdata/local/programs/python/python37-32/lib/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\utils.py", line 726,
in resolve_deps
    req_dir=req_dir,
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\utils.py", line 480,
in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\utils.py", line 385,
in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolvelver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()                                                      lver.py", line 206, in _resolve_one_round
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round                                                                      lver.py", line 301, in _iter_dependencies
    for dep in self._iter_dependencies(best_match):
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\resositories\pypi.py", line 234, in get_dependencieslver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)                                                      sitories\pypi.py", line 426, in get_legacy_dependenci  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)                                                        sitories\pypi.py", line 297, in resolve_reqs
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependencies                                                        nal\resolve.py", line 260, in _resolve_one
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\reponal\resolve.py", line 213, in _get_abstract_dist_forsitories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)                                                              nal\operations\prepare.py", line 294, in prepare_link  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)                                                nal\operations\prepare.py", line 127, in prep_for_dis  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes                                                                                        nal\req\req_install.py", line 474, in run_egg_info
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 294, in prepare_linked_requirement                                            nal\utils\misc.py", line 705, in call_subprocess
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_interror code 1 in C:\Users\trang\AppData\Local\Temp\tmpl9nal\operations\prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\req\req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\users\trang\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\utils\misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\trang\AppData\Local\Temp\tmpl9qz2wyjbuild\uwsgi\

### What I expected to happen
+ Pipfile and Pipfile.lock is updated
+ [dev-packages] dependencies & Locking [packages] dependencies should be successfully locked.
+ build and run the containers

### Screenshots
![image](https://user-images.githubusercontent.com/30888959/50688854-45d12d80-1077-11e9-8774-922993a39ae2.png)
![image](https://user-images.githubusercontent.com/30888959/50688904-7ca74380-1077-11e9-8c02-f354881eefe2.png)

**System information**
Operating system: Windows 10 Home
Browser: Chrome

**Comment by jxltom** [comment]
I would suggest update your Pipfile.lock by ```pipenv lock``` or ```pipenv lock --clear``` which disable the caches, instead of deleting the Pipfile and import it from ```requirements.txt```

**Comment by ndh150** [comment]
Thank you @ixltom. I did try those commands, but It did not work for me.

**Comment by jxltom** [comment]
Why not working, please show the output of docker compose?

**Comment by ndh150** [comment]
Yes. As kombu = "==4.2.2" does not exist, I adjusted to kombu = "==4.2.2.post1" in `saleor/settings.py`. Then, I update `Pipfile` by the commands:
$ pipenv install -r requirements.txt
$ pipenv lock
But the `pipenv lock` failed as mentioned above.

**Comment by jxltom** [comment]
Please pull the latest commit of saleor, this kombu issue has already been solved in a PR.

Plus, please don't ```pipenv install -r requirements.txt```, all the requirements are already defined in Pipfile, a simple ```pipenv lock``` will be fine. Also, adjust ```kombu = "==4.2.2.post1"``` in Pipfile, don't edit it in requirements.
