### ISSUE TITLE
Error on initial migrate on account models

### ISSUE THREAD

**Issue by stepacool** [mirumee/saleor#3586]
### What I'm trying to achieve
…
I want to start saleor locally, I followed the linux saleor setup guide
### Steps to reproduce the problem
1. I followed every setup step, as of Jan 11 2018
2. On stage 7, when it says "python manage.py migrate" I get the following error:
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying account.0001_initial... OK
  Applying account.0002_auto_20150907_0602...Traceback (most recent call last):
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: syntax error at or near "WITH ORDINALITY"
LINE 6:                     FROM unnest(c.conkey) WITH ORDINALITY co...

### What I expected to happen
…
I expected saleor initial migrations to run without any sort of trouble

### What I tried

I re-created databases from scratch, tried to set it up to the default values(saleo:saleor@saleor), still drops the same mistake. 

**System information**
Ubuntu 18.04 LTS
My settings.py database sections looks like this:

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'saleor',
        'USER': 'saleor',
        'PASSWORD': 'saleor',
        'HOST': "127.0.0.1",
        'PORT': '5432',
    },

}

With default 

DATABASES = {
    'default': dj_database_url.config(
        default='postgres://saleor:saleor@localhost:5432/saleor',
        conn_max_age=600)}

it gives the same result.

### Full traceback:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 216, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 508, in alter_field
    return self._alter_many_to_many(model, old_field, new_field, strict)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 861, in _alter_many_to_many
    new_field.remote_field.through._meta.get_field(new_field.m2m_reverse_field_name()),
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 523, in alter_field
    old_db_params, new_db_params, strict)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/backends/postgresql/schema.py", line 122, in _alter_field
    new_db_params, strict,
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 531, in _alter_field
    fk_names = self._constraint_names(model, [old_field.column], foreign_key=True)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 1029, in _constraint_names
    constraints = self.connection.introspection.get_constraints(cursor, model._meta.db_table)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/backends/postgresql/introspection.py", line 158, in get_constraints
    """, ["public", table_name])
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/stephen/Code/Work/saleor/saleor-venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: syntax error at or near "WITH ORDINALITY"
LINE 6:                     FROM unnest(c.conkey) WITH ORDINALITY co...

**Comment by stepacool** [comment]
I had two postgres instances running, switching to 5433 port worked for me, although why I have two postgres'es is still yet to be discovered.

**Comment by maarcingebala** [comment]
This must be a problem with your local environment. Make sure that you have single Postgres instance running. Saleor uses the default 5432 port. I'm closing this issue as it seems not related to Saleor.
