### ISSUE TITLE
ValueError when loading fixture.

### ISSUE THREAD

**Issue by raybesiga** [mirumee/saleor#3662]
### What I'm trying to achieve

I am trying to load a fixture from `db.json` on heroku but it throws a ValueError when it tries to convert from string to float. 

### Steps to reproduce the problem
I run the following command: `heroku run python manage.py loaddata db.json`

I get the following output:

```bash 
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1746, in to_python
    return float(value)
ValueError: could not convert string to float: '1.0 kg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/serializers/python.py", line 135, in Deserializer
    data[field.name] = field.to_python(field_value)
  File "/app/.heroku/python/lib/python3.6/site-packages/django_measurement/models.py", line 94, in to_python
    value = super(MeasurementField, self).to_python(value)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1751, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ["'1.0 kg' value must be a float."]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 113, in loaddata
    self.load_label(fixture_label)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 168, in load_label
    for obj in objects:
  File "/app/saleor/core/utils/json_serializer.py", line 42, in Deserializer
    yield from PythonDeserializer(objects, **options)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/serializers/python.py", line 137, in Deserializer
    raise base.DeserializationError.WithData(e, d['model'], d.get('pk'), field_value)
django.core.serializers.base.DeserializationError: Problem installing fixture '/app/db.json': ["'1.0 kg' value must be a float."]: (product.producttype:pk=1) field_value was '1.0 kg'
```

It seems to me that there is an issue with the shipping weight value when specifying the details of a `Product Type`. 

![screen shot 2019-01-28 at 17 15 53](https://user-images.githubusercontent.com/405697/51841793-77f54880-2320-11e9-9e64-ad2887b5d019.png)

The `kg` is somehow getting concatenated to the specified value and thus the string cannot be converted to a float. Any idea why?

### Screenshots

**System information**
Operating system: MacOS
Browser: Chrome

**Comment by Pacu2** [comment]
<img width="85" alt="screenshot 2019-01-28 at 15 47 47" src="https://user-images.githubusercontent.com/21290461/51843823-17600e80-2314-11e9-8d67-c2ca3861a2b7.png">
Weight is saved as a space-separated `value unit` (eg. `10 kg`) and it seems that default `loaddata` function does not handle it properly.

**Comment by raybesiga** [comment]
Any advice regarding how to deal with it? I'm guessing the simplest way right now is editing it to say `"weight": "1.0"`?

**Comment by Pacu2** [comment]
In `populatedb` command we are parsing this string to `Weight(unit=value)`.  As far as I remember one should not assign other values, than `Weight` instances, to `MeasurementField`. Not sure what could be the consequences, can't you use `populatedb` instead? It loads all the products data.

**Comment by raybesiga** [comment]
Thanks @Pacu2 for this idea. Would the command look something like this?

`heroku run python manage.py populatedb`

How does it know to pick up the `db.json` file?

**Comment by raybesiga** [comment]
Hi @Pacu2 @patrys I run the `heroku run python manage.py populatedb` command and instead of loading data from my `db.json` it auto-populated with data from the demo website. How do I work around this?

**Comment by maarcingebala** [comment]
@raybesiga Did you manage to resolve this issue?

**Comment by raybesiga** [comment]
@maarcingebala I did not. I had to populate from scratch sadly.
