### ISSUE TITLE
Problems with Local Docker Development on my Mac

### ISSUE THREAD

**Issue by opticrew** [mirumee/saleor#3676]
### What I'm trying to achieve

Saleor development with Docker but impossible for me to 

### Steps to reproduce the problem
1. Install Docker and docker compose 
2. Build the containers using docker-compose
$ docker-compose build

### What I expected to happen
To prepare the database and start my development server at http://0.0.0.0:8000/ but I have 96 unapplied migration(django_celery_results, django_prices_vatlayer, menu, order, page, payment, product, shipping, site) and it is impossible for me to run successufully web python3 manage.py migrate

### Screenshots

$ docker-compose run web python3 manage.py migrate
Starting saleor_db_1 ... done
Starting saleor_redis_1 ... done
Operations to perform:
  Apply all migrations: account, auth, checkout, contenttypes, discount, django_celery_results, django_prices_openexchangerates, django_prices_vatlayer, impersonate, menu, order, page, payment, product, sessions, shipping, site, sites, social_django
Running migrations:
  Applying product.0059_generate_variant_name_from_attrs...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/app/saleor/product/migrations/0059_generate_variant_name_from_attrs.py", line 20, in create_variant_name_based_on_attributes
    new_name = get_name_from_attributes(variant)
  File "/app/saleor/product/migrations/0059_generate_variant_name_from_attrs.py", line 9, in get_name_from_attributes
    values = get_attributes_display_map(variant, attributes)
  File "/app/saleor/product/utils/attributes.py", line 31, in get_attributes_display_map
    choices = {str(a.pk): a.translated for a in attribute.values.all()}
  File "/app/saleor/product/utils/attributes.py", line 31, in <dictcomp>
    choices = {str(a.pk): a.translated for a in attribute.values.all()}
AttributeError: 'AttributeChoiceValue' object has no attribute 'translated'

**System information**
Operating system: MacOS Mojave 10.14
Browser:

**Comment by Pacu2** [comment]
Are you using the latest version of Saleor?

**Comment by opticrew** [comment]
Today,
1 :  I made git clone https://github.com/mirumee/saleor.git 
2 : I made cd saleor
3 I made docker-compose up

**Comment by opticrew** [comment]
I found my mistake, I had an older installation of saleor with docker. I made `$ docker-compose down --volumes` and it works now !

**Comment by Pacu2** [comment]
Glad to see this resolved
