### ISSUE TITLE
firebase deploy --only functions An unexpected error has occurred.

### ISSUE THREAD

**Issue by Robjnoble** [mirumee/saleor#3713]
### What I'm trying to achieve
Firebase CLI function deployment from Mac

### Steps to reproduce the problem
1. firebase deploy --only functions

like: https://github.com/mirumee/saleor/issues/1631

### What I expected to happen
Same as my Linux machine, happily installs the Firebase functions (I set both up together, both with Node 8, both following the same instructions).

### Screenshots
[debug] [2019-02-12T19:27:23.563Z] TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:389:11)
    at Object.exports.spawn (child_process.js:502:38)
    at /usr/local/lib/node_modules/firebase-tools/lib/deploy/lifecycleHooks.js:21:27
    at initializePromise (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:1039:33)
    at /usr/local/lib/node_modules/firebase-tools/lib/deploy/lifecycleHooks.js:20:12
    at _chain (/usr/local/lib/node_modules/firebase-tools/lib/deploy/index.js:23:45)
    at deploy (/usr/local/lib/node_modules/firebase-tools/lib/deploy/index.js:76:10)
    at Command._action (/usr/local/lib/node_modules/firebase-tools/commands/deploy.js:47:12)
    at /usr/local/lib/node_modules/firebase-tools/lib/command.js:176:29
[error] 
[error] Error: An unexpected error has occurred.

**System information**
Operating system: Mac OS 10.14.3
Browser:NA, command line issue.

**Comment by maarcingebala** [comment]
Please upgrade your Node version to 10.x.

http://docs.getsaleor.com/en/latest/gettingstarted/installation-macos.html#node-js
