### ISSUE TITLE
error while running migrations 

### ISSUE THREAD

**Issue by steph9600** [mirumee/saleor#3746]
### What I'm trying to achieve
I'm pretty new to programming in django.  So after installation, while running manage.py migrate for the first time, i keep getting an error code. i don't know what i'm doing wrong

### Steps to reproduce the problem
1. followed the saleor installation docs
2. installed postgresSQL and other apps
3. created the user, database and granted my user superuser privileges
4. set the SECRET_KEY environment variable
5. ran python.py migrate

### What I expected to happen

successful migration

**System information**
Operating system: 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\BELINDA\saleor\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command
_line
    utility.execute()
  File "C:\Users\BELINDA\saleor\lib\site-packages\django\core\management\__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "C:\Users\BELINDA\saleor\lib\site-packages\django\conf\__init__.py", line 57, in __getattr__
    self._setup(name)
  File "C:\Users\BELINDA\saleor\lib\site-packages\django\conf\__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\BELINDA\saleor\lib\site-packages\django\conf\__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\BELINDA\saleor\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\BELINDA\saleor\saleor\settings.py", line 55, in <module>
    conn_max_age=600)}
  File "C:\Users\BELINDA\saleor\lib\site-packages\dj_database_url.py", line 55, in config
    config = parse(s, engine, conn_max_age, ssl_require)
  File "C:\Users\BELINDA\saleor\lib\site-packages\dj_database_url.py", line 103, in parse
    engine = SCHEMES[url.scheme] if engine is None else engine
KeyError: ''
Browser:

**Comment by jxltom** [comment]
It looks like you forget to set ```DATABASE_URL``` environment variable.

**Comment by steph9600** [comment]
@jxltom
> It looks like you forget to set `DATABASE_URL` environment variable.

i did that and set it to     'postgres://saleor:saleor@localhost:5432/saleor'
still getting the same error code

**Comment by NyanKiyoshi** [comment]
1. Did you make any edits in the `settings.py` file? If you did, please show us the `settings.py` from the line 50 to 60.
1. Can you send us the list of your environment variables? By running the `set` command on `cmd.exe` or `Get-ChildItem Env:` in powershell.

**Comment by steph9600** [comment]
After I restarted my PC a couple of times it works now. I don't normally have to do that to get an environment variable to work but in this case I did. Thank you
