### ISSUE TITLE
WebpackError at /en/

### ISSUE THREAD

**Issue by AnkitKundariya** [mirumee/saleor#3995]
### What I'm trying to achieve

Trying to build-assets

### Steps to reproduce the problem
1. 
2. 

### What I expected to happen
…

### Screenshots

WebpackError at /en/
            ModuleBuildError in 
            Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/home/b12/work/saleor/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.sassLoader (/home/b12/work/saleor/node_modules/sass-loader/lib/loader.js:46:72)
    at runLoaders (/home/b12/work/saleor/node_modules/webpack/lib/NormalModule.js:301:20)
    at /home/b12/work/saleor/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/b12/work/saleor/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/home/b12/work/saleor/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/home/b12/work/saleor/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/home/b12/work/saleor/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/home/b12/work/saleor/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/home/b12/work/saleor/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /home/b12/work/saleor/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

**System information**

Operating system: Ubuntu 18.04
Browser: Chrome

**Comment by NyanKiyoshi** [comment]
Hi, can you provide the steps to reproduce your issue?

Also, did you install the dependencies? Try running `npm i` as `node-sass` should have been installed from there.

**Comment by AnkitKundariya** [comment]
> Hi, can you provide the steps to reproduce your issue?
> 
> Also, did you install the dependencies? Try running `npm i` as `node-sass` should have been installed from there.

yes i checked there are some issues with `node-sass` package which not get installed in a normal way so there is a way to install it `sudo npm install --save-dev  --unsafe-perm node-sass`

**Comment by AnkitKundariya** [comment]
it's resolved you can close this issue. @NyanKiyoshi
