### ISSUE TITLE
Issue: Connecting with default postgresql credentials

### ISSUE THREAD

**Issue by vihit22** [mirumee/saleor#4026]
OS = Ubuntu 18.04
Python = 3.6.7
PIP =  9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

Here's what I've done:

1). sudo apt-get install build-essential python3-dev python3-pip python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info postgresql postgresql-contrib

2).  git clone https://github.com/mirumee/saleor.git

3). cd saleor

4).  pip install -r requirements.txt 

5). Created a user with password and database (other then saleor) in PostgreSQL and attached it to the database with all privileges. 

6). Edited common.env  (cat ./common.env = 
```
DATABASE_URL=postgresql://user:password@127.0.0.1:5432/userdatabase
DEFAULT_FROM_EMAIL=noreply@example.com
OPENEXCHANGERATES_API_KEY
CACHE_URL=redis://redis:6379/0
CELERY_BROKER_URL=redis://redis:6379/1
SECRET_KEY=32 character key
JWT_VERIFY_EXPIRATION=True
VATLAYER_ACCESS_KEY)
```

7). Run 'python manage.py migrate' and got the following error:

```
Traceback (most recent call last):
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/vihit/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "saleor"
FATAL:  password authentication failed for user "saleor"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vihit/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/vihit/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vihit/.local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vihit/.local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/vihit/.local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/vihit/.local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 87, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/vihit/.local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/vihit/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "saleor"
FATAL:  password authentication failed for user "saleor"
```

Output of command 
```
psql ppostgresql::/user:password@127.0.0.1:5432/userdatabase
```

```

psql (10.7 (Ubuntu 10.7-0ubuntu0.18.04.1))
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

userdatabase=>
```

**Comment by vihit22** [comment]
All except for the first and fifth steps are done as non-root.

**Comment by NyanKiyoshi** [comment]
Hi,

`common.env` is not used by `manage.py`. Instead you would set your variable environments into a shell script or manually enter them.

For example, here, you would do:
```bash
export DATABASE_URL=postgresql://user:password@127.0.0.1:5432/userdatabase
```

**Comment by vihit22** [comment]
Thank you, exporting DATABASE_URL and SECRET_KEY (just to be safe) worked like a charm.
