### ISSUE TITLE
Docker compose build fails on webpack

### ISSUE THREAD

**Issue by sGerli** [mirumee/saleor#4053]
### What I'm trying to achieve
Build using docker compose.

### Steps to reproduce the problem
1. Clone from master
2. run `docker-compose build`

### What I expected to happen
Build successfully but it fails on step 15/34. A few days ago it completed the build but then all web requests would always timeout.

### Screenshots
```
Step 15/34 : RUN STATIC_URL=${STATIC_URL} npm run build-assets --production   && npm run build-emails --production
 ---> Running in c2839b3e32b1

> saleor@0.0.0 build-assets /app
> webpack -p

Starting type checking and linting service...
(node:18) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Using 1 worker with 2048MB memory limit
st Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! saleor@0.0.0 build-assets: `webpack -p`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the saleor@0.0.0 build-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-01T13_46_17_940Z-debug.log
ERROR: Service 'celery' failed to build: The command '/bin/sh -c STATIC_URL=${STATIC_URL} npm run build-assets --production   && npm run build-emails --production' returned a non-zero code: 137
```

Full log:
```
# cat /root/.npm/_logs/2019-05-01T13_46_17_940Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build-assets',
1 verbose cli   '--production' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prebuild-assets', 'build-assets', 'postbuild-assets' ]
5 info lifecycle saleor@0.0.0~prebuild-assets: saleor@0.0.0
6 info lifecycle saleor@0.0.0~build-assets: saleor@0.0.0
7 verbose lifecycle saleor@0.0.0~build-assets: unsafe-perm in lifecycle true
8 verbose lifecycle saleor@0.0.0~build-assets: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle saleor@0.0.0~build-assets: CWD: /app
10 silly lifecycle saleor@0.0.0~build-assets: Args: [ '-c', 'webpack -p' ]
11 silly lifecycle saleor@0.0.0~build-assets: Returned: code: 137  signal: null
12 info lifecycle saleor@0.0.0~build-assets: Failed to exec build-assets script
13 verbose stack Error: saleor@0.0.0 build-assets: `webpack -p`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid saleor@0.0.0
15 verbose cwd /app
16 verbose Linux 4.18.0-18-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build-assets" "--production"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 137
22 error saleor@0.0.0 build-assets: `webpack -p`
22 error Exit status 137
23 error Failed at the saleor@0.0.0 build-assets script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

**System information**
Operating system: Ubuntu 18.04
Docker version: 18.09.5
Docker-compose version: 1.24.0
Browser: N/A

**Comment by NyanKiyoshi** [comment]
Hi,

Looks like your instance does not have enough memory (ram) to compile the assets.

**Comment by sGerli** [comment]
Thanks, I gave it 2 more GB (4GB total) and now it does compile, thanks.
