### ISSUE TITLE
Send order confirmation does not check for null addresses

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4056]
### Steps to reproduce the problem
1. Create a digital order 
2. Send the order confirmation email

```
.ERROR celery.app.trace Task saleor.order.emails.send_order_confirmation[6b5284db-234a-4afd-96c6-2d384b9192de] raised unexpected: AttributeError("'NoneType' object has no attribute 'as_data'") [PID:3810:MainThread]
Traceback (most recent call last):
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/mikailkocak/Development/saleor/saleor/order/emails.py", line 60, in send_order_confirmation
    send_templated_mail(**email_data)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/templated_email/__init__.py", line 70, in send_templated_mail
    headers=headers, create_link=create_link, **kwargs)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/templated_email/backends/vanilla_django.py", line 258, in send
    create_link=create_link)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/templated_email/backends/vanilla_django.py", line 134, in get_email_message
    template_suffix or file_extension)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/templated_email/backends/vanilla_django.py", line 106, in _render_email
    response[part] = render_block_to_string(full_template_names, part, render_context)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/render_block/base.py", line 39, in render_block_to_string
    return django_render_block(t, block_name, context)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/render_block/django.py", line 27, in django_render_block
    return _render_template_block(template, block_name, context_instance)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/render_block/django.py", line 70, in _render_template_block
    return _render_template_block_nodelist(template.nodelist, block_name, context)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/render_block/django.py", line 85, in _render_template_block_nodelist
    return node.render(context)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mikailkocak/Development/saleor-venv/lib/python3.7/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/mikailkocak/Development/saleor/saleor/account/templatetags/i18n_address_tags.py", line 10, in format_address
    address_data = address.as_data()
AttributeError: 'NoneType' object has no attribute 'as_data'
```

**Comment by NyanKiyoshi** [comment]
Also note that the test that triggered this error did not catch that the email actually failed to be sent.
