### ISSUE TITLE
"BLOB/TEXT column 'service' used in key specification without a key length"

### ISSUE THREAD

**Issue by kphretiq** [mirumee/saleor#418]
Setting up saleor using virtualenv, using the recommended module mysqlclient==1.3.7 on an ubuntu 15.10 system.

```bash
(venv)doug@ookla:~/Projects/saleor$ git rev-list --count HEAD
1586
```
I have created a db "saleor", a db user "foobar" and granted that user full control over the "saleor" database.

When running migrate on newly created db.
```bash
python manage.py migrate
```
I get the following error:
```bash
  Applying order.0009_auto_20151201_0820... OK
  Applying registration.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 359, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 324, in alter_unique_together
    self.execute(self._create_unique_sql(model, columns))
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/home/doug/NSixty/saleor/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'service' used in key specification without a key length")
```

Apologies in advance: I am a django noob and lack the brains to know if this is an error in saleor's setup, or a problem in django.

**Comment by patrys** [comment]
This is indeed a problem on our side. MySQL is a bit… special and needs special treatment. We usually test with PostgreSQL and sqlite so we did not catch that.

**Comment by kphretiq** [comment]
I agree that it's . . . special. (It's almost a double-elipsis special!), but unfortunately I'm stuck with it for this project. I'm digging around looking for schema, so I can attempt a fix.

**Comment by patrys** [comment]
You may want to see #368 for some pointers.

**Comment by kphretiq** [comment]
Attempted the fix outlined in [#368](https://github.com/mirumee/saleor/issues/368)

```python
class ExternalUserData(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='external_ids')
    service = models.CharField(db_index=True, max_length=255)
    username = models.CharField(db_index=True, max_length=255)
```

to no avail. 

```bash
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'service' used in key specification without a key length")
```

The lack of any difference leads me to believe it's failing elsewhere, but I'm probably hallucinating.

**Comment by patrys** [comment]
You may need to also fix the initial migration if any. We'll look at it tomorrow.

**Comment by kphretiq** [comment]
Thanks for looking at this so quickly!

**Comment by kphretiq** [comment]
Thanks folks! Installation works as expected with mysql.
