### ISSUE TITLE
'npm run build-assets' failure: "Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`"

### ISSUE THREAD

**Issue by JedMeister** [mirumee/saleor#4297]
### What I'm trying to achieve

Trying to install saleor (Debian Stretch with Python3.7 installed from Buster)

### Steps to reproduce the problem
1. Follow instructions as per https://saleor.readthedocs.io/en/latest/gettingstarted/installation-linux.html#installation
2. All works fine until "step 9":

```
$ npm run build-assets

> saleor@0.0.0 build-assets /var/www/saleor
> webpack -p

Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
(node:24262) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! saleor@0.0.0 build-assets: `webpack -p`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the saleor@0.0.0 build-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/saleor/.npm/_logs/2019-06-15T14_45_49_534Z-debug.log
```
I tried following the instructions, (i.e. ran `npm update caniuse-lite browserslist`) but that didn't help. I also tried removing them and reinstalling them but same result.

I found [someone else hitting this same issue](https://superuser.com/questions/1440742/saleor-when-i-ran-the-docker-compose-up-d-i-got-this-error-message) but no resolution. 

I did find other people with similar issues (although not specifically related to saleor) and they all seemed somehow related to Visual Studio?!

### Full log

```
cat /home/saleor/.npm/_logs/2019-06-15T14_45_49_534Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build-assets' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prebuild-assets', 'build-assets', 'postbuild-assets' ]
5 info lifecycle saleor@0.0.0~prebuild-assets: saleor@0.0.0
6 info lifecycle saleor@0.0.0~build-assets: saleor@0.0.0
7 verbose lifecycle saleor@0.0.0~build-assets: unsafe-perm in lifecycle true
8 verbose lifecycle saleor@0.0.0~build-assets: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/saleor/node_modules/.bin:/var/www/saleor/bin:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle saleor@0.0.0~build-assets: CWD: /var/www/saleor
10 silly lifecycle saleor@0.0.0~build-assets: Args: [ '-c', 'webpack -p' ]
11 silly lifecycle saleor@0.0.0~build-assets: Returned: code: 137  signal: null
12 info lifecycle saleor@0.0.0~build-assets: Failed to exec build-assets script
13 verbose stack Error: saleor@0.0.0 build-assets: `webpack -p`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid saleor@0.0.0
15 verbose cwd /var/www/saleor
16 verbose Linux 4.9.0-8-amd64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build-assets"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 137
22 error saleor@0.0.0 build-assets: `webpack -p`
22 error Exit status 137
23 error Failed at the saleor@0.0.0 build-assets script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

**System information**
Operating system: Debian Stretch with Python3.7 installed from Buster

**Comment by NyanKiyoshi** [comment]
Hi! How much RAM does the machine or instance has? The process got killed by the system it looks like. Most likely because there is not enough available memory.

**Comment by JedMeister** [comment]
@NyanKiyoshi - You my friend are a champion! :smile: 

My dev VM only had 512MB RAM. I bumped that to 2GB and it all works!

**Comment by meettingthespam** [comment]
Hey, maybe this is too n00b, but how do you increase the ram in the virtual environment?

**Comment by JedMeister** [comment]
@meettingthespam - I didn't increase the RAM in my virtual env, just on the system itself. I was running in Virtual Box which made it easy. If you are running in a VPS, then you might need to upgrade your plan to get more RAM...

**Comment by tong900801** [comment]
Thanks! Increasing VM's memory worked for me.
