### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'available_currencies'

### ISSUE THREAD

**Issue by chetabahana** [mirumee/saleor#4350]
### Typical Error: missing argument
Typical Error happen since the [last commit](https://github.com/mirumee/saleor/commit/8afc4b979ac076fd8e875bed3155b06311ae5fbb)
```
TypeError: __init__() missing 1 required positional argument: 'available_currencies'
unable to load app 0 (mountpoint='') (callable not found or import error)
```

### Steps to reproduce the problem
1. python3 manage.py migrate
2. python3 manage.py populatedb
3. uwsgi --ini saleor/wsgi/uwsgi.ini 

### Complete Logs
```
Step #2: LOGS
Step #2: 
Step #2: [uWSGI] getting INI configuration from /app/saleor/wsgi/uwsgi.ini
Step #2: [uwsgi-static] added mapping for /static => /app/static
Step #2: *** Starting uWSGI 2.0.18 (64bit) on [Tue Jun 25 22:35:14 2019] ***
Step #2: compiled with version: 6.3.0 20170516 on 25 June 2019 14:34:11
Step #2: os: Linux-4.15.0-1034-gcp #36-Ubuntu SMP Thu Jun 6 14:47:38 UTC 2019
Step #2: nodename: 0b2a6e322fe8
Step #2: machine: x86_64
Step #2: clock source: unix
Step #2: pcre jit disabled
Step #2: detected number of CPU cores: 1
Step #2: current working directory: /app
Step #2: detected binary path: /usr/local/bin/uwsgi
Step #2: your memory page size is 4096 bytes
Step #2: detected max file descriptor number: 1048576
Step #2: building mime-types dictionary from file /etc/mime.types...554 entry found
Step #2: lock engine: pthread robust mutexes
Step #2: thunder lock: disabled (you can enable it with --thunder-lock)
Step #2: uwsgi socket 0 bound to TCP address :8000 fd 3
Step #2: Python version: 3.7.3 (default, Jun 11 2019, 01:11:15)  [GCC 6.3.0 20170516]
Step #2: *** Python threads support is disabled. You can enable it with --enable-threads ***
Step #2: Python main interpreter initialized at 0x55f6c156f440
Step #2: your server socket listen backlog is limited to 100 connections
Step #2: your mercy for graceful operations on workers is 60 seconds
Step #2: mapped 364600 bytes (356 KB) for 4 cores
Step #2: *** Operational MODE: preforking ***
Step #2: Traceback (most recent call last):
Step #2:   File "./saleor/wsgi/__init__.py", line 25, in <module>
Step #2:     application = get_wsgi_application()
Step #2:   File "/usr/local/lib/python3.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
Step #2:     return WSGIHandler()
Step #2:   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 135, in __init__
Step #2:     self.load_middleware()
Step #2:   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 37, in load_middleware
Step #2:     mw_instance = middleware(handler)
Step #2:   File "./saleor/core/middleware.py", line 48, in wrapped
Step #2:     return django_only_request_handler(get_response, handler)
Step #2:   File "./saleor/core/middleware.py", line 33, in django_only_request_handler
Step #2:     api_path = reverse("api")
Step #2:   File "/usr/local/lib/python3.7/site-packages/django/urls/base.py", line 90, in reverse
Step #2:     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
Step #2:   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 608, in _reverse_with_prefix
Step #2:     self._populate()
Step #2:   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 446, in _populate
Step #2:     for url_pattern in reversed(self.url_patterns):
Step #2:   File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
Step #2:     res = instance.__dict__[self.name] = self.func(instance)
Step #2:   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 579, in url_patterns
Step #2:     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
Step #2:   File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
Step #2:     res = instance.__dict__[self.name] = self.func(instance)
Step #2:   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 572, in urlconf_module
Step #2:     return import_module(self.urlconf_name)
Step #2:   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
Step #2:     return _bootstrap._gcd_import(name[level:], package, level)
Step #2:   File "./saleor/urls.py", line 14, in <module>
Step #2:     from .dashboard.urls import urlpatterns as dashboard_urls
Step #2:   File "./saleor/dashboard/urls.py", line 8, in <module>
Step #2:     from .discount.urls import urlpatterns as discount_urls
Step #2:   File "./saleor/dashboard/discount/urls.py", line 3, in <module>
Step #2:     from . import views
Step #2:   File "./saleor/dashboard/discount/views.py", line 16, in <module>
Step #2:     from . import forms
Step #2:   File "./saleor/dashboard/discount/forms.py", line 22, in <module>
Step #2:     "Apply only if the purchase value is greater than or equal to",
Step #2: TypeError: __init__() missing 1 required positional argument: 'available_currencies'
Step #2: unable to load app 0 (mountpoint='') (callable not found or import error)
Step #2: *** no app loaded. going in full dynamic mode ***
Step #2: *** uWSGI is running in multiple interpreter mode ***
Step #2: spawned uWSGI master process (pid: 1)
Step #2: spawned uWSGI worker 1 (pid: 8, cores: 1)
Step #2: spawned uWSGI worker 2 (pid: 9, cores: 1)
Step #2: spawned uWSGI worker 3 (pid: 10, cores: 1)
Step #2: spawned uWSGI worker 4 (pid: 11, cores: 1)
```

**System information**
OS (1): Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1034-gcp x86_64)
OS (2): Linux-4.15.0-1034-gcp#36-Ubuntu
PG_VERSION: 11.4-1.pgdg90+1
REDIS_VERSION: 5.0.5
Python 3.7.1

DOCKER:
```
$ docker --version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false

$ docker-compose --version
docker-compose version 1.24.1, build 4667896b
```

**Comment by korycins** [comment]
Did you update django-prices to the newest version (2.0.0)? We haven't changed saleor's source code yet
We haven't been compatible with 2.0.0 yet. Here is the issue for that: https://github.com/mirumee/saleor/issues/4337

**Comment by chetabahana** [comment]
Can we update it from the [requirements.txt](https://github.com/mirumee/saleor/blob/6c26a7537d90c911bbf9ff09e826383173883242/requirements.txt)? It shows still in version 1.0.4
```
django-prices-openexchangerates==1.0.1
django-prices-vatlayer==1.0.2
django-prices==1.0.4
```

**Comment by korycins** [comment]
It shows 1.0.4 because it is the latest version of django-prices that is compatible with saleor. We haven't migrated our "Money" logic to the newest version of django-prices yet.

**Comment by chetabahana** [comment]
So how to update it. Do I need to install version 2.0.0 separately?

**Comment by korycins** [comment]
@chetabahana  As I said. **Saleor is not compatible with django-prices 2.0.0**. If you upgrade django-prices to 2.0.0 separately, you will get the same error as in your logs (`__init__() missing 1 required positional argument: 'available_currencies'`) .

**Comment by chetabahana** [comment]
Understood. Thanks for the explanation.
