### ISSUE TITLE
Model with 'ManyToManyField' and 'TaxedMoneyField' raise error

### ISSUE THREAD

**Issue by kswiatek92** [mirumee/saleor#4378]
### Steps to reproduce the problem
1.  Clone saleor (branch master)
2. install requirements (pipenv install)
3. docker-compose build
4. docker-compose up
5. add two fields saleor/order/models.py Order
i.e. 
- sped_label = models.FileField(upload_to="sped_label", blank=True)
- xaxa = models.CharField(max_length=255, default="", blank=True)
6. run manage.py
i.e. ./manage.py migrate

### Traceback
```─➤  ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/django/urls/resolvers.py", line 579, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/django/urls/resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/kswiatek/.pyenv/versions/3.6.7/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kswiatek/workspace/saleor/saleor/saleor/urls.py", line 16, in <module>
    from .graphql.api import schema
  File "/Users/kswiatek/workspace/saleor/saleor/saleor/graphql/api.py", line 3, in <module>
    from .account.schema import AccountMutations, AccountQueries
  File "/Users/kswiatek/workspace/saleor/saleor/saleor/graphql/account/schema.py", line 6, in <module>
    from ..descriptions import DESCRIPTIONS
  File "/Users/kswiatek/workspace/saleor/saleor/saleor/graphql/descriptions.py", line 4, in <module>
    from .order.resolvers import ORDER_SEARCH_FIELDS
  File "/Users/kswiatek/workspace/saleor/saleor/saleor/graphql/order/resolvers.py", line 10, in <module>
    from .types import Order
  File "/Users/kswiatek/workspace/saleor/saleor/saleor/graphql/order/types.py", line 255, in <module>
    class Order(CountableDjangoObjectType):
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/graphene/utils/subclass_with_meta.py", line 52, in __init_subclass__
    super_class.__init_subclass_with_meta__(**options)
  File "/Users/kswiatek/workspace/saleor/saleor/saleor/graphql/core/connection.py", line 56, in __init_subclass_with_meta__
    super().__init_subclass_with_meta__(*args, connection=countable_conn, **kwargs)
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/graphene_django/types.py", line 83, in __init_subclass_with_meta__
    construct_fields(model, registry, only_fields, exclude_fields), _as=Field
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/graphene_django/types.py", line 22, in construct_fields
    _model_fields = get_model_fields(model)
  File "/Users/kswiatek/.pyenv/versions/3.6.7/envs/saleor/lib/python3.6/site-packages/graphene_django/utils/utils.py", line 39, in get_model_fields
    list(model._meta.fields) + list(model._meta.local_many_to_many)
TypeError: '<' not supported between instances of 'ManyToManyField' and 'TaxedMoneyField'
```

**Comment by NyanKiyoshi** [comment]
Hi,

Could you provide more steps and information about what you did so we can understand better what's wrong. It looks like there is an issue with your `Order` GraphQL object but I couldn't say what is causing it and the line you are providing us seems unrelated.

Also, to make code readable you can use:

> \`\`\`
> your code...
> \`\`\`

**Comment by kswiatek92** [comment]
sorry about formatting. 
About what I did
1. Cloned saleor
2. Install requirements 
3. build docker image
4. run docker image
5. add 2 fields to Order model
6. run  `/manage.py makemigrations`

**Comment by korycins** [comment]
Issue fixed in https://github.com/mirumee/django-prices/pull/75
