### ISSUE TITLE
Looking a way to solve: 'Connection reset by peer'

### ISSUE THREAD

**Issue by chetabahana** [mirumee/saleor#4407]
### What I'm trying to achieve
Some times Saleor pages came in my browser with error  like shown on the screenshot attached. I just simply refresh the browser and the requested page will come up again. 

The log report (see below) says that this error caused by 'Connection reset by peer'. So I don't think this is a problem with Saleor. Therefore I put this issue as a feature request.

### Describe a proposed solution
I would propose in order so that instead of raising an error, this problem can be resolved on server side before Saleor sending the output to browser. 

If not possible then as alternative it might be put as javascript code that making the page to be automatically refreshed on client side each time this problem happen.

### Other solutions I've tried and won't work
I have been looking a python method to detect this error and put the code in Saleor but couldn't find the right way to do it.

### Details found in Compose Logs

While doing compose some times it happen in celery.
 It is also rare but when it comes the error is reported like this:
```
Error while reading from socket: (104, 'Connection reset by peer')
```
Complete logs:
```
Step #2: celery_1    | INFO saleor.core.utils Created 6 thumbnails [PID:8:MainThread]
Step #2: celery_1    | [2019-07-04 21:34:13,134: INFO/ForkPoolWorker-1] Created 6 thumbnails
Step #2: celery_1    | [2019-07-04 21:34:13,134: INFO/ForkPoolWorker-1] Task saleor.product.thumbnails.create_product_thumbnails[6e18b741-2419-4359-8c5a-cd9791e0a18e] succeeded in 3.779323505999855s: None
Step #2: celery_1    | INFO saleor.core.utils Creating thumbnails for  50 [PID:8:MainThread]
Step #2: celery_1    | [2019-07-04 21:34:13,591: INFO/ForkPoolWorker-1] Creating thumbnails for  50
Step #2: celery_1    | 
Step #2: celery_1    | INFO saleor.core.utils Created 6 thumbnails [PID:8:MainThread]
Step #2: celery_1    | [2019-07-04 21:34:16,144: INFO/ForkPoolWorker-1] Created 6 thumbnails
Step #2: celery_1    | [2019-07-04 21:34:16,144: INFO/ForkPoolWorker-1] Task saleor.product.thumbnails.create_product_thumbnails[fb2bc680-9a6d-4fa8-915e-c5b60bbefeae] succeeded in 2.556264849999934s: None
Step #2: celery_1    | INFO saleor.core.utils Creating thumbnails for  1 [PID:8:MainThread]
Step #2: celery_1    | [2019-07-04 21:34:16,649: INFO/ForkPoolWorker-1] Creating thumbnails for  1
Step #2: celery_1    | 
Step #2: celery_1    | worker: Warm shutdown (MainProcess)
Step #2: celery_1    | 
Step #2: celery_1    | [2019-07-04 21:34:17,341: ERROR/ForkPoolWorker-1] Thumbnail generation failed
Step #2: celery_1    | Traceback (most recent call last):
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/django_redis/cache.py", line 32, in _decorator
Step #2: celery_1    |     return method(self, *args, **kwargs)
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/django_redis/cache.py", line 81, in get
Step #2: celery_1    |     client=client)
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/django_redis/client/default.py", line 205, in get
Step #2: celery_1    |     raise ConnectionInterrupted(connection=client, parent=e)
Step #2: celery_1    | django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
Step #2: celery_1    | 
Step #2: celery_1    | During handling of the above exception, another exception occurred:
Step #2: celery_1    | 
Step #2: celery_1    | Traceback (most recent call last):
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/versatileimagefield/image_warmer.py", line 117, in _prewarm_versatileimagefield
Step #2: celery_1    |     url = get_url_from_image_key(versatileimagefieldfile, size_key)
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/versatileimagefield/utils.py", line 216, in get_url_from_image_key
Step #2: celery_1    |     img_url = img_url[size_key].url
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/versatileimagefield/datastructures/sizedimage.py", line 136, in __getitem__
Step #2: celery_1    |     if cache.get(resized_url) and resized_url is not None:
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/django_redis/cache.py", line 39, in _decorator
Step #2: celery_1    |     raise e.parent
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/django_redis/client/default.py", line 203, in get
Step #2: celery_1    |     value = client.get(key)
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1264, in get
Step #2: celery_1    |     return self.execute_command('GET', name)
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 775, in execute_command
Step #2: celery_1    |     return self.parse_response(connection, command_name, **options)
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 789, in parse_response
Step #2: celery_1    |     response = connection.read_response()
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 637, in read_response
Step #2: celery_1    |     response = self._parser.read_response()
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 290, in read_response
Step #2: celery_1    |     response = self._buffer.readline()
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 224, in readline
Step #2: celery_1    |     self._read_from_socket()
Step #2: celery_1    |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 199, in _read_from_socket
Step #2: celery_1    |     (e.args,))
Step #2: celery_1    | redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
Step #2: celery_1    | ERROR saleor.core.utils Failed to generate thumbnails [PID:8:MainThread]
Step #2: celery_1    | [2019-07-04 21:34:17,917: ERROR/ForkPoolWorker-1] Failed to generate thumbnails
Step #2: celery_1    | [2019-07-04 21:34:17,918: INFO/ForkPoolWorker-1] Task saleor.product.thumbnails.create_collection_background_image_thumbnails[b262ef82-5c7b-4893-b4de-555984c3c0fb] succeeded in 1.7701049249999414s: None
Step #2: celery_1    |  
Step #2: celery_1    |  -------------- celery@c58f97249fd2 v4.3.0 (rhubarb)
Step #2: celery_1    | ---- **** ----- 
Step #2: celery_1    | --- * ***  * -- Linux-4.15.0-1036-gcp-x86_64-with-debian-9.9 2019-07-04 21:36:38
Step #2: celery_1    | -- * - **** --- 
Step #2: celery_1    | - ** ---------- [config]
Step #2: celery_1    | - ** ---------- .> app:         saleor:0x7f4cf12c7f98
Step #2: celery_1    | - ** ---------- .> transport:   redis://redis:6379/1
Step #2: celery_1    | - ** ---------- .> results:     disabled://
Step #2: celery_1    | - *** --- * --- .> concurrency: 1 (prefork)
Step #2: celery_1    | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
Step #2: celery_1    | --- ***** ----- 
Step #2: celery_1    |  -------------- [queues]
Step #2: celery_1    |                 .> celery           exchange=celery(direct) key=celery
Step #2: celery_1    |                 
Step #2: celery_1    | 
Step #2: celery_1    | [tasks]
Step #2: celery_1    |   . saleor.account.emails.send_account_delete_confirmation_email
Step #2: celery_1    |   . saleor.account.emails.send_password_reset_email
Step #2: celery_1    |   . saleor.account.thumbnails.create_user_avatar_thumbnails
Step #2: celery_1    |   . saleor.core.analytics.ga_report
Step #2: celery_1    |   . saleor.core.utils.update_conversion_rates_from_openexchangerates
Step #2: celery_1    |   . saleor.dashboard.emails.send_promote_customer_to_staff_email
Step #2: celery_1    |   . saleor.dashboard.emails.send_set_password_customer_email
Step #2: celery_1    |   . saleor.dashboard.emails.send_set_password_staff_email
Step #2: celery_1    |   . saleor.order.emails.send_fulfillment_confirmation
Step #2: celery_1    |   . saleor.order.emails.send_fulfillment_update
Step #2: celery_1    |   . saleor.order.emails.send_order_confirmation
Step #2: celery_1    |   . saleor.order.emails.send_payment_confirmation
Step #2: celery_1    |   . saleor.product.tasks.update_variants_names
Step #2: celery_1    |   . saleor.product.thumbnails.create_category_background_image_thumbnails
Step #2: celery_1    |   . saleor.product.thumbnails.create_collection_background_image_thumbnails
Step #2: celery_1    |   . saleor.product.thumbnails.create_product_thumbnails
Step #2: celery_1    | 
Step #2: celery_1    | [2019-07-04 21:36:39,795: INFO/MainProcess] Connected to redis://redis:6379/1
Step #2: celery_1    | [2019-07-04 21:36:39,825: INFO/MainProcess] mingle: searching for neighbors
Step #2: celery_1    | [2019-07-04 21:36:40,915: INFO/MainProcess] mingle: all alone
Step #2: celery_1    | [2019-07-04 21:36:40,930: INFO/MainProcess] celery@c58f97249fd2 ready.
Step #2: celery_1    | 
Step #2: celery_1    | worker: Warm shutdown (MainProcess
```
### Screenshots or mockups

On browser : 

![screencapture-chetabahana-en-2019-07-05-21_43_33](https://user-images.githubusercontent.com/36441664/60730001-48510900-9f6e-11e9-909e-04933c712efd.png)

Log report:

![screencapture-console-cloud-google-logs-viewer-2019-07-05-21_51_10](https://user-images.githubusercontent.com/36441664/60731330-83087080-9f71-11e9-82b1-fae372792750.png)

**Comment by NyanKiyoshi** [comment]
> ```
> Step #2: celery_1    | django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error while reading from socket: (104, 'Connection reset by peer') ```

Might be an issue of communication with Redis on your end?

**Comment by chetabahana** [comment]
Here is the warning log during compose from redis
```
Step #0: LOGS
Step #0: 
Step #0: Attaching to compose_celery_1, compose_redis_1, compose_postgres_1
Step #0: redis_1     | 1:C 06 Jul 2019 15:17:46.149 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
Step #0: redis_1     | 1:C 06 Jul 2019 15:17:46.151 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
Step #0: redis_1     | 1:C 06 Jul 2019 15:17:46.151 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
Step #0: redis_1     | 1:M 06 Jul 2019 15:17:46.158 * Running mode=standalone, port=6379.
Step #0: redis_1     | 1:M 06 Jul 2019 15:17:46.159 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
Step #0: redis_1     | 1:M 06 Jul 2019 15:17:46.159 # Server initialized
Step #0: redis_1     | 1:M 06 Jul 2019 15:17:46.159 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
Step #0: redis_1     | 1:M 06 Jul 2019 15:17:46.159 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
Step #0: redis_1     | 1:M 06 Jul 2019 15:17:46.160 * Ready to accept connections
Step #0: redis_1     | 1:M 06 Jul 2019 15:22:47.151 * 100 changes in 300 seconds. Saving...
Step #0: redis_1     | 1:M 06 Jul 2019 15:22:47.526 * Background saving started by pid 10
Step #0: redis_1     | 10:C 06 Jul 2019 15:22:47.655 * DB saved on disk
Step #0: redis_1     | 10:C 06 Jul 2019 15:22:47.655 * RDB: 0 MB of memory used by copy-on-write
Step #0: redis_1     | 1:M 06 Jul 2019 15:22:47.893 * Background saving terminated with success

```
