### ISSUE TITLE
Initial migration failed

### ISSUE THREAD

**Issue by paulon-zervoulakus** [mirumee/saleor#4478]
### What I'm trying to achieve
Deploy on Dev environment

### Steps to reproduce the problem
1. git clone https://github.com/mirumee/saleor.git
2. cd saleor/
3. virtualenv store
4. activate the virtual environment [store\Scripts\activate.bat]
5. set SECRET_KEY
6. Create a PostgreSQL user
7. Create a PostgreSQL database
8. python manage.py migrate

### What I expected to happen
…

### Screenshots

`(store) D:\Trends\virtual_env\bupharco\saleor>python manage.py migrate
Operations to perform:
  Apply all migrations: account, auth, checkout, contenttypes, discount, django_prices_openexchangerates, django_prices_vatlayer, giftcard, impersonate, menu, order, page, payment, product, sessions, shipping, site, sites, social_django
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_content_type" does not exist
LINE 1: ..."."app_label", "django_content_type"."model" FROM "django_co...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\core\management\commands\migrate.py", line 257, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\core\management\sql.py", line 51, in emit_post_migrate_signal
    **kwargs
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\dispatch\dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\dispatch\dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\contrib\contenttypes\management\__init__.py", line 118, in create_contenttypes
    content_types, app_models = get_contenttypes_and_models(app_config, using, ContentType)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\contrib\contenttypes\management\__init__.py", line 95, in get_contenttypes_and_models
    for ct in ContentType.objects.using(using).filter(app_label=app_config.label)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\db\models\query.py", line 274, in __iter__
    self._fetch_all()
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\db\models\query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\db\models\query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\db\models\sql\compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Trends\virtual_env\bupharco\saleor\store\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_content_type" does not exist
LINE 1: ..."."app_label", "django_content_type"."model" FROM "django_co...`
**System information**
Operating system: Windows 10
Browser:

**Comment by paulon-zervoulakus** [comment]
issue arises when i use to fake the migration. i had to remove all the rows from table django_migrations and do a **manage.py migrate** again without --fake parameter.
