### ISSUE TITLE
raw_html_to_json migration fails when product description is empty

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#4567]
### What I'm trying to achieve
I'm running the migrate command.

### Steps to reproduce the problem
1. Have a product without any text in the description
2. Run migrate

### What I expected to happen
I expected the migrations to apply successfully. But it fails on https://github.com/mirumee/saleor/blob/master/saleor/product/migrations/0096_raw_html_to_json.py when processing a product without a description. It fails on the `html_to_draftjs()` call.
I fixed it by modifying the conditions slightly.
```diff
...
-if not description_raw.strip():
+if product.description.strip() and not description_raw.strip():
```

### Trace
```
remote: Traceback (most recent call last):
remote:   File "manage.py", line 10, in <module>
remote:     execute_from_command_line(sys.argv)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
remote:     utility.execute()
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
remote:     self.fetch_command(subcommand).run_from_argv(self.argv)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
remote:     self.execute(*args, **cmd_options)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
remote:     output = self.handle(*args, **options)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
remote:     res = handle_func(*args, **kwargs)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
remote:     fake_initial=fake_initial,
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
remote:     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
remote:     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
remote:     state = migration.apply(state, schema_editor)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
remote:     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
remote:   File "/app/saleor/product/migrations/0096_raw_html_to_json.py", line 24, in convert_products_html_to_json
remote:     product.description_json = html_to_draftjs(product.description)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/html_to_draftjs/__init__.py", line 8, in html_to_draftjs
remote:     return SoupConverter(strict=strict).convert(soup).to_dict()
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/html_to_draftjs/converter.py", line 340, in convert
remote:     self.build_block(body)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/html_to_draftjs/converter.py", line 180, in build_block
remote:     element_name = element.name.lower()
remote: AttributeError: 'NoneType' object has no attribute 'name'
```

**System information**
Operating system: Windows 10 x64
Browser: Firefox 68

**Comment by NyanKiyoshi** [comment]
Thanks for the finding! But the issue is at the library itself, the migration is fine as it is. It's better to just try to parse the HTML and decide where to go from there, it's safer/easier that way.
