### ISSUE TITLE
gunicorn status error for request.country

### ISSUE THREAD

**Issue by sdnnet3** [mirumee/saleor#4893]
### What I'm trying to achieve
Trying to connect gunicorn to handle socket connections. 

### Steps to reproduce the problem
1. spin up server on digital ocean, follow initiation outline for both saleor documentation and [digital ocean](https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-18-04).

2. sudo systemctl status gunicorn results in this error.

### What I expected to happen

gunicorn.service - gunicorn daemon
   Loaded: loaded (/etc/systemd/system/gunicorn.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-07-09 20:00:40 UTC; 4s ago
 Main PID: 1157 (gunicorn)
    Tasks: 4 (limit: 1153)
   CGroup: /system.slice/gunicorn.service
           ├─1157 /home/sammy/myprojectdir/myprojectenv/bin/python3 /home/sammy/myprojectdir/myprojectenv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock myproject.wsgi:application
           ├─1178 /home/sammy/myprojectdir/myprojectenv/bin/python3 /home/sammy/myprojectdir/myprojectenv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock myproject.wsgi:application
           ├─1180 /home/sammy/myprojectdir/myprojectenv/bin/python3 /home/sammy/myprojectdir/myprojectenv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock myproject.wsgi:application
           └─1181 /home/sammy/myprojectdir/myprojectenv/bin/python3 /home/sammy/myprojectdir/myprojectenv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock myproject.wsgi:application

Jul 09 20:00:40 django1 systemd[1]: Started gunicorn daemon.
Jul 09 20:00:40 django1 gunicorn[1157]: [2018-07-09 20:00:40 +0000] [1157] [INFO] Starting gunicorn 19.9.0
Jul 09 20:00:40 django1 gunicorn[1157]: [2018-07-09 20:00:40 +0000] [1157] [INFO] Listening at: unix:/run/gunicorn.sock (1157)
Jul 09 20:00:40 django1 gunicorn[1157]: [2018-07-09 20:00:40 +0000] [1157] [INFO] Using worker: sync
Jul 09 20:00:40 django1 gunicorn[1157]: [2018-07-09 20:00:40 +0000] [1178] [INFO] Booting worker with pid: 1178
Jul 09 20:00:40 django1 gunicorn[1157]: [2018-07-09 20:00:40 +0000] [1180] [INFO] Booting worker with pid: 1180
Jul 09 20:00:40 django1 gunicorn[1157]: [2018-07-09 20:00:40 +0000] [1181] [INFO] Booting worker with pid: 1181
Jul 09 20:00:41 django1 gunicorn[1157]:  - - [09/Jul/2018:20:00:41 +0000] "GET / HTTP/1.1" 200 16348 "-" "curl/7.58.0"

### Screenshots

Hoping to see the standard message for the gunicorn status.

![Capture](https://user-images.githubusercontent.com/9749815/67519909-b116db00-f65c-11e9-8e2f-24408cd97ffa.PNG)
gunicorn.service - gunicorn daemon
   Loaded: loaded (/etc/systemd/system/gunicorn.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-10-24 18:38:22 UTC; 2min 38s ago
 Main PID: 1352 (gunicorn)
    Tasks: 4 (limit: 1152)
   CGroup: /system.slice/gunicorn.service
           ├─1352 /home/clayton/.venv/bin/python3 /home/clayton/.venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock saleor.wsgi:applicat
           ├─1371 /home/clayton/.venv/bin/python3 /home/clayton/.venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock saleor.wsgi:applicat
           ├─1373 /home/clayton/.venv/bin/python3 /home/clayton/.venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock saleor.wsgi:applicat
           └─1374 /home/clayton/.venv/bin/python3 /home/clayton/.venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock saleor.wsgi:applicat

Oct 24 18:38:29 webdev gunicorn[1352]:     if not request.country:
Oct 24 18:38:29 webdev gunicorn[1352]: AttributeError: 'WSGIRequest' object has no attribute 'country'
Oct 24 18:38:29 webdev gunicorn[1352]: ERROR django.request Internal Server Error: / [PID:1373:MainThread]
Oct 24 18:38:29 webdev gunicorn[1352]: Traceback (most recent call last):
Oct 24 18:38:29 webdev gunicorn[1352]:   File "/home/clayton/.venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
Oct 24 18:38:29 webdev gunicorn[1352]:     response = get_response(request)
Oct 24 18:38:29 webdev gunicorn[1352]:   File "/home/clayton/saleor/saleor/core/middleware.py", line 65, in middleware
Oct 24 18:38:29 webdev gunicorn[1352]:     if not request.country:
Oct 24 18:38:29 webdev gunicorn[1352]: AttributeError: 'WSGIRequest' object has no attribute 'country'
Oct 24 18:38:29 webdev gunicorn[1352]:  - - [24/Oct/2019:13:38:29 -0500] "GET / HTTP/1.1" 500 63415 "-" "curl/7.58.0"

**System information**
Operating system: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-66-generic x86_64)

**Comment by sdnnet3** [comment]
One thing I noticed, not sure if I'm correct in this, but in the middleware.py file it's 'from django_countries' though in pypi i've only found 'django-countries' with a hyphen instead of an underscore.
