### ISSUE TITLE
Heroku Demo App creation failed.

### ISSUE THREAD

**Issue by afarntrog** [mirumee/saleor#5024]
### Trying to deploy the demo to Heroku.

I get the following error: "There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again."

Thank You

**Comment by maarcingebala** [comment]
Hey, which version of Saleor do you use? It should work on `2.9` and on latest `master`. I also have a staging environment that gets deployed on every change to `master` and it's running sucessfully. Do you have any changes in `app.json` file?

**Comment by afarntrog** [comment]
I clicked the Deploy To Heroku button that is in the README. Thanks

**Comment by karolkielecki** [comment]
@afarntrog Hi there! Thanks for letting us know. We need some time to find out what is causing this error. If I have any news, I'll let you know.

**Comment by rafitamolin** [comment]
Same error here with the button.

**Comment by maarcingebala** [comment]
The `app.json` file is valid and I cannot recreate the original issue. There is however a different issue now with the `ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL` env variable which we'll try to fix as soon as we can.

**Comment by heyAyushh** [comment]
1.3.0 weasyprint-51 webencodings-0.5.1
-----> $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 224, in fetch_command
           app_name = commands[subcommand]
       KeyError: 'collectstatic'
       During handling of the above exception, another exception occurred:
       Traceback (most recent call last):
         File "manage.py", line 10, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 231, in fetch_command
           settings.INSTALLED_APPS
         File "/app/.heroku/python/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
           self._setup(name)
         File "/app/.heroku/python/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
           self._wrapped = Settings(settings_module)
         File "/app/.heroku/python/lib/python3.8/site-packages/django/conf/__init__.py", line 142, in __init__
           mod = importlib.import_module(self.SETTINGS_MODULE)
         File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
         File "<frozen importlib._bootstrap>", line 991, in _find_and_load
         File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
         File "<frozen importlib._bootstrap_external>", line 783, in exec_module
         File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
         File "/tmp/build_36e5ba474014cfaab92fc18da310c984/saleor/settings.py", line 52, in <module>
           raise ImproperlyConfigured(
       django.core.exceptions.ImproperlyConfigured: ALLOWED_CLIENT_HOSTS environment variable must be set when DEBUG=False.
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by maarcingebala** [comment]
@heyAyushh You need to set `ALLOWED_CLIENT_HOSTS` environment variable if you're running Saleor in DEBUG=False mode. As a value, you should provide the hostname of your storefront, e.g for our [demo](http://demo.saleor.io/) instance it is: `https://demo.saleor.io`

**Comment by heyAyushh** [comment]
Thankyou @maarcingebala

**Comment by KojoHero** [comment]
Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 224, in fetch_command
           app_name = commands[subcommand]
       KeyError: 'collectstatic'
       During handling of the above exception, another exception occurred:
       Traceback (most recent call last):
         File "manage.py", line 22, in <module>
           main()
         File "manage.py", line 18, in main
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 231, in fetch_command
           settings.INSTALLED_APPS
         File "/app/.heroku/python/lib/python3.8/site-packages/django/conf/__init__.py", line 83, in __getattr__
           self._setup(name)
         File "/app/.heroku/python/lib/python3.8/site-packages/django/conf/__init__.py", line 70, in _setup
           self._wrapped = Settings(settings_module)
         File "/app/.heroku/python/lib/python3.8/site-packages/django/conf/__init__.py", line 177, in __init__
           mod = importlib.import_module(self.SETTINGS_MODULE)
         File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
         File "<frozen importlib._bootstrap>", line 991, in _find_and_load
         File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
       ModuleNotFoundError: No module named 'Hero.settings'
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed

how do i solve this
