### ISSUE TITLE
AttributeError: module 'saleor' has no attribute 'discount'

### ISSUE THREAD

**Issue by samadak06** [mirumee/saleor#5026]
![Screenshot from 2019-12-02 22-14-24](https://user-images.githubusercontent.com/49633408/69977671-39887580-1551-11ea-8c9e-f811bc4e212a.png)
### What I'm trying to achieve
…
Hi,

I'm new to here and happy to see such a great project saleor,
i was trying setup it in my local env, while running migrate command as per installation
doc, its throws the error mentioned in the screenshot.
Thanks in advance.

### Screenshots

System information**
Operating system: 
Browser:

**Comment by maarcingebala** [comment]
Hey @samadak06, I see on the screenshot that you're running Saleor with Python 3.6. Saleor doesn't work with that version anymore, you need to run it in at least Python 3.7, but we really recommend Python 3.8.

**Comment by wbfiretoss** [comment]
PLEASE UPDATE YOUR INSTALL DOCS!!!! Install docs still say python 3.6

**Comment by maarcingebala** [comment]
If you're using the unreleased version from the `master` branch, please refer to the `next` version of the docs: https://docs.getsaleor.com/docs/next/getting-started/installation-macos/.
Be default docs refer to the latest released version `2.9.0` where Python 3.6 was used.

**Comment by hetendra** [comment]
I have updated python3.6 to 3.8 but now its saying no module named celery
`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/johny/django/saleor-master/saleor/__init__.py", line 1, in <module>
    from .celeryconf import app as celery_app
  File "/home/johny/django/saleor-master/saleor/celeryconf.py", line 3, in <module>
    from celery import Celery
ModuleNotFoundError: No module named 'celery'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/johny/django/saleor-master/saleor/__init__.py", line 1, in <module>
    from .celeryconf import app as celery_app
  File "/home/johny/django/saleor-master/saleor/celeryconf.py", line 3, in <module>
    from celery import Celery
ModuleNotFoundError: No module named 'celery'`

**Comment by youngheart12** [comment]
pip install celery

**Comment by abbykdd** [comment]
Hey @youngheart12 
I am having the exact same problem.  

AttributeError: module 'saleor.core' has no attribute 'logging'

Did you figure out how to solve this?

**Comment by 64bits** [comment]
`pip install python-json-logger` would work. This means you have not installed all the dependencies.
