### ISSUE TITLE
Error installing Python requirements on Ubuntu

### ISSUE THREAD

**Issue by hjek** [mirumee/saleor#511]
`$ pip install -r requirements.txt` fails on Ubuntu Wily 64-bit. Last chunk of the log:

```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

In file included from src/lxml/lxml.etree.c:323:0:

src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory

compilation terminated.

Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1

creating tmp

cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitz83yIe.c -o tmp/xmlXPathInitz83yIe.o

/tmp/xmlXPathInitz83yIe.c:1:26: fatal error: libxml/xpath.h: No such file or directory

compilation terminated.

*********************************************************************************

Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?

*********************************************************************************

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Y_GUYD/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JKuqbw-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-build-Y_GUYD/lxml
Storing debug log for failure in /home/pelle/.pip/pip.log

```

**Comment by patrys** [comment]
The clue is in the error message: it looks like you need to install the `-dev` package for `libxml2`.

**Comment by hjek** [comment]
Thanks. Did `apt-get install libxml2-dev`, and now I get a new error. (Sorry, this is not just "being lazy" about looking up the error messages. I just want to notify you that the install instructions in the wiki don't work currently on Ubuntu, instead of me just ignoring it and using something else.)

```
running build_ext

building 'lxml.etree' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

creating build/temp.linux-x86_64-2.7/src/lxml

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

In file included from src/lxml/lxml.etree.c:323:0:

src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory

compilation terminated.

Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1

creating tmp

cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitmg0M7r.c -o tmp/xmlXPathInitmg0M7r.o

/tmp/xmlXPathInitmg0M7r.c:2:1: warning: return type defaults to ‘int’ [-Wimplicit-int]

 main (int argc, char **argv) {

 ^

cc tmp/xmlXPathInitmg0M7r.o -lxml2 -o a.out

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-GXEtM6/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-T002YQ-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-build-GXEtM6/lxml
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 68: ordinal not in range(128)
```

**Comment by wanghaisheng** [comment]
add prerequirement fix this 
```
apt-get install -y libxml2-dev libxslt1-dev
```

**Comment by hjek** [comment]
yay, thanks.
