### ISSUE TITLE
Creating a product type fails when valid/invalid, or empty attributes were provided

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#5129]
### Steps to reproduce the problem
Invoke `createProductType` with `productAttributes` supplied, empty or invalid.

Query:
```gql
    mutation createProductType($name: String!, $attributesIDs: [ID!]) {
      productTypeCreate(input: {name: $name, hasVariants: false, productAttributes: $attributesIDs}) {
        productType {
          id
          name
        }

        errors {
          field
          message
        }
      }
    }
```

Variables:
```json
{
  "name": "Storage",
  "attributeIDs": [
    "Q29sbGVjdGlvbjo1NA==",
    "Q29sbGVjdGlvbjo1NQ==",
    "Q29sbGVjdGlvbjo1Ng==",
  ]
}
```

Instead I got:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "./saleor/graphql/core/mutations.py", line 279, in mutate
    response = cls.perform_mutation(root, info, **data)
  File "./saleor/graphql/core/mutations.py", line 452, in perform_mutation
    cls._save_m2m(info, instance, cleaned_input)
  File "./saleor/graphql/product/mutations/products.py", line 1283, in _save_m2m
    instance.product_attributes.set(cleaned_data["product_attributes"])
  File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 975, in set
    objs = tuple(objs)
TypeError: 'NoneType' object is not iterable
```

**Comment by kswiatek92** [comment]
couldn't reproduce
got proper error:
```
      "errors": [
        {
          "field": "productAttributes",
          "message": "Could not resolve to a node with the global id list of '['Q29sbGVjdGlvbjo1NA==', 'Q29sbGVjdGlvbjo1NQ==', 'Q29sbGVjdGlvbjo1Ng==']'."
        }
      ]
```
