### ISSUE TITLE
Creating a product with a non-existing attribute value crashes

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#5130]
## Steps
Invoke `productCreate` with: 
```
attributes: [{"id": "validAttrID", values: ["totally invalid input, expects existing AttributeValue ID/slug"]}
```

This will cause the following:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "./saleor/graphql/core/mutations.py", line 279, in mutate
    response = cls.perform_mutation(root, info, **data)
  File "./saleor/graphql/core/mutations.py", line 448, in perform_mutation
    cleaned_input = cls.clean_input(info, instance, data)
  File "./saleor/graphql/product/mutations/products.py", line 792, in clean_input
    attributes, product_type
  File "./saleor/graphql/product/mutations/products.py", line 754, in clean_attributes
    attributes, attributes_qs, is_variant=False
  File "./saleor/graphql/product/mutations/products.py", line 718, in clean_input
    cls._validate_input(cleaned_input, attributes_qs, is_variant)
  File "./saleor/graphql/product/mutations/products.py", line 663, in _validate_input
    return cls._check_input_for_product(cleaned_input, attribute_qs)
  File "./saleor/graphql/product/mutations/products.py", line 621, in _check_input_for_product
    validate_attribute_input_for_product(attribute, values)
  File "./saleor/graphql/product/utils.py", line 27, in validate_attribute_input_for_product
    if not value.strip():
```

**Comment by maarcingebala** [comment]
I think it was supposed to create new values from there if the slug or ID wasn't found in the database. Anyway, it shouldn't crash. We'll investigate the issue.

**Comment by NyanKiyoshi** [comment]
The issue seems to have been fixed.
