### ISSUE TITLE
Errors occur when update a page

### ISSUE THREAD

**Issue by gsoec** [mirumee/saleor#5157]
### What I'm trying to achieve
Update a `Page`

### Steps to reproduce the problem
1.  Call `Mutation.pageUpdate ` with `input: {}`
```bash
web_1     | ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:8:Thread-52]
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.8/site-packages/promise/promise.py", line 489, in _resolve_from_executor
web_1     |     executor(resolve, reject)
web_1     |   File "/usr/local/lib/python3.8/site-packages/promise/promise.py", line 756, in executor
web_1     |     return resolve(f(*args, **kwargs))
web_1     |   File "/usr/local/lib/python3.8/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
web_1     |     return next(*args, **kwargs)
web_1     |   File "/app/saleor/graphql/core/mutations.py", line 279, in mutate
web_1     |     response = cls.perform_mutation(root, info, **data)
web_1     |   File "/app/saleor/graphql/core/mutations.py", line 448, in perform_mutation
web_1     |     cleaned_input = cls.clean_input(info, instance, data)
web_1     |   File "/app/saleor/graphql/page/mutations.py", line 43, in clean_input
web_1     |     cleaned_input["slug"] = slugify(cleaned_input["title"])
web_1     | KeyError: 'title'
```

### What I expected to happen
should update a `Page` without error

**Comment by maarcingebala** [comment]
Thanks for reporting, that's clearly a bug. This error also appears for the `pageCreate` mutation. Now the code assumes that `title` is always present while it's not required by the schema. It should be required when creating new pages and optional when updating existing ones.
