### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### ISSUE THREAD

**Issue by sreerajmp** [mirumee/saleor#5218]
### What I'm trying to achieve
i was trying to populate my db

### Steps to reproduce the problem
using "python populate_first_app.py"

### What I expected to happen
Traceback (most recent call last):
  File "populate_first_app.py", line 6, in <module>
    from first_app.models import Webpage,AccessRecords,Topic
  File "C:\Users\SREERAJ\Documents\My_Django_Project\first_project\first_app\models.py", line 4, in <module>
    class Topic(models.Model):
  File "C:\Users\SREERAJ\Anaconda3\envs\mydjangoenv\lib\site-packages\django\db\models\base.py", line 103, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\SREERAJ\Anaconda3\envs\mydjangoenv\lib\site-packages\django\apps\registry.py", line 252, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\SREERAJ\Anaconda3\envs\mydjangoenv\lib\site-packages\django\apps\registry.py", line 135, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### Screenshots

**System information**
Operating system: windows

**Comment by maarcingebala** [comment]
It doesn't seem like a Saleor-related problem.
