### ISSUE TITLE
Issue with running manage.py migrate on Windows 10

### ISSUE THREAD

**Issue by tbaynes** [mirumee/saleor#5271]
### What I'm trying to achieve
Setup new installation of Saleor on Windows 10. Specifically, want to successfully run the command "python manage.py migrate".

### Steps to reproduce the problem
1. Buy a Windows 10 machine.
2. Install Python 3.7 and ensure it is first in path and executing from command line. (I tried with both 3.7.6 as well as 3.8.1)
3. Install Node.js version 10 or later (I'm using 12.14.1)
4. Install PostreSQL version 9.4 or later (I'm using 10.12)
5. Install GTK+ (I'm using GTK3+ for Win64)
6. Install Visual Studio Build Tools (I'm using Build Tools 2017 v 15.9.19)
7. Clone saleor repository, cd to saleor directory
8. Install dependencies: python -m pip install -r requirements.txt
9. set env vars: SECRET_KEY=<mykey>, DATABASE_URL=saleor,API_URI=http://localhost:8000/graphql
10. Create PostgresSQL user: "saleor" with pwd "saleor" and Superuser rights
11. Create PostgreSQL database "saleor" with owner "saleor". Verify access to saleor db from command line with user/pwd saleor/saleor
12. Prepare the database:  python manage.py migrate
### What I expected to happen
Step 12, I expected the command to run successfully. Instead it fails with output below.

### Screenshots
d:\dev\saleor>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Packages\Python38-32\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Packages\Python38-32\lib\site-packages\django\core\management\__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "C:\Packages\Python38-32\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "C:\Packages\Python38-32\lib\site-packages\django\conf\__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Packages\Python38-32\lib\site-packages\django\conf\__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Packages\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\dev\saleor\saleor\settings.py", line 51, in <module>
    "default": dj_database_url.config(
  File "C:\Packages\Python38-32\lib\site-packages\dj_database_url.py", line 55, in config
    config = parse(s, engine, conn_max_age, ssl_require)
  File "C:\Packages\Python38-32\lib\site-packages\dj_database_url.py", line 103, in parse
    engine = SCHEMES[url.scheme] if engine is None else engine
KeyError: ''

**System information**
Operating system: Windows 10.0.19041

**Comment by tbaynes** [comment]
I rolled back to python 3.7, getting slightly different error:

d:\dev\saleor>python manage.py migrate
d:\dev\saleor\saleor\urls.py:31: UserWarning: The debug toolbar was not installed. Ignore the error.             settings.py should already have warned the user about it.
  settings.py should already have warned the user about it."
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Packages\Python37\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Packages\Python37\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Packages\Python37\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Packages\Python37\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Packages\Python37\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Packages\Python37\lib\site-packages\django\core\management\commands\migrate.py", line 87, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "C:\Packages\Python37\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "C:\Packages\Python37\lib\site-packages\django\db\migrations\loader.py", line 49, in __init__
    self.build_graph()
  File "C:\Packages\Python37\lib\site-packages\django\db\migrations\loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "C:\Packages\Python37\lib\site-packages\django\db\migrations\recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "C:\Packages\Python37\lib\site-packages\django\db\migrations\recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "C:\Packages\Python37\lib\site-packages\django\db\backends\base\base.py", line 256, in cursor
    return self._cursor()
  File "C:\Packages\Python37\lib\site-packages\django\db\backends\dummy\base.py", line 20, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

settings.py DATABASES looks like this:
DATABASES = {
    "default": dj_database_url.config(
        default="postgres://saleor:saleor@localhost:5432/saleor", conn_max_age=600
    )
}

I can run this command and it connects to saleor db and logs in ok:
c:> psql postgres://saleor:saleor@localhost:5432/saleor

**Comment by NyanKiyoshi** [comment]
Hi, `DATABASE_URL` should be `postgres://saleor:saleor@localhost:5432/saleor` not `saleor`, retry with that value instead

**Comment by gabernalt** [comment]
Hi, I'm getting a similar error. Also on Windows 10 and have pretty done much done exactly all 12 steps as tbaynes (except that I'm using Visual Studio Build Tools v.14.24)

**Log:**

(Saleor) C:\Users\Tavo\Dev\Saleor\saleor>python manage.py migrate
C:\Users\Tavo\Dev\Saleor\saleor\saleor\urls.py:29: UserWarning: The debug toolbar was not installed. Ignore the error.             settings.py should already have warned the user about it.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\backends\base\base.py", line 217, in ensure_connection
    self.connect()
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\backends\base\base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\backends\postgresql\base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\psycopg2\__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\core\management\commands\migrate.py", line 87, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\migrations\loader.py", line 49, in __init__
    self.build_graph()
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\migrations\loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\migrations\recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\migrations\recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\backends\base\base.py", line 256, in cursor
    return self._cursor()
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\backends\base\base.py", line 233, in _cursor
    self.ensure_connection()
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\backends\base\base.py", line 217, in ensure_connection
    self.connect()
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\backends\base\base.py", line 217, in ensure_connection
    self.connect()
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\backends\base\base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\django\db\backends\postgresql\base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Users\Tavo\.virtualenvs\Saleor\lib\site-packages\psycopg2\__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError


Any ideas? Thanks

**Comment by NyanKiyoshi** [comment]
Hi, please check the value of `DATABASE_URL` and that the database is running, the user is created, etc.
Also, after `psycopg2.OperationalError`, you do not have a short message? That would have been very useful.

**Comment by gabernalt** [comment]
Hi Nyan, in my settings.py I have defined DATABASE_URL = "postgres://saleor:saleor@localhost:5432/saleor". I have created the user "saleor" as Superuser. And no short message after psycopg2.OperationalError... just the long info after:

"The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "manage.py", line 10, in ...."

**Comment by NyanKiyoshi** [comment]
The database `saleor` exists as well?

**Comment by gabernalt** [comment]
The active database was named postgres... Created a new one named saleor and python manage.py migrate worked. Thanks

**Comment by OtmaneM** [comment]
python manage.py migrate
Traceback (most recent call last):
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\postgresql\base.py", line 25, in <module>
    import psycopg as Database
ModuleNotFoundError: No module named 'psycopg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\postgresql\base.py", line 27, in <module>
    import psycopg2 as Database
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\psycopg2\__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
    ...<10 lines>...
    )
ImportError: DLL load failed while importing _psycopg: Le module spécifié est introuvable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\otman\OneDrive\Bureau\djan\myproject\manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "C:\Users\otman\OneDrive\Bureau\djan\myproject\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
    ~~~~~~~~~~~~^^
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\apps\registry.py", line 116, in populate       
    app_config.import_models()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\apps\config.py", line 269, in import_models    
    self.models_module = import_module(models_module_name)
                         ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\models.py", line 5, in <module>   
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\base_user.py", line 40, in <module>
    class AbstractBaseUser(models.Model):
    ...<123 lines>...
            )
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\base.py", line 143, in __new__       
    new_class.add_to_class("_meta", Options(meta, app_label))
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\base.py", line 371, in add_to_class  
    value.contribute_to_class(cls, name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\options.py", line 231, in contribute_to_class
    self.db_table, connection.ops.max_name_length()
                   ^^^^^^^^^^^^^^
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\connection.py", line 15, in __getattr__  
    return getattr(self._connections[self._alias], item)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\connection.py", line 62, in __getitem__  
    conn = self.create_connection(alias)
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 193, in create_connection   
    backend = load_backend(db["ENGINE"])
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 113, in load_backend        
    return import_module("%s.base" % backend_name)
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\otman\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\postgresql\base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 or psycopg module")
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 or psycopg module
