### ISSUE TITLE
Default page redirect to graphql 

### ISSUE THREAD

**Issue by egyping** [mirumee/saleor#5273]
### What I'm trying to achieve
…
trying to open the home page post-deployment 
### Steps to reproduce the problem
1. python manage.py runserver
2. access http://127.0.0.1:8000/

### What I expected to happen
…
it should open the store front but its not happening and the url auto redirect to /graphql
### Screenshots

**System information**
Operating system:
macos

**Comment by karolkielecki** [comment]
@egyping Hey! We've dropped Storefront 1.0 (django views and templates). We don't maintain it anymore.

Currently, the core itself is just the GraphQL API. The core, storefront and dashboard are in the separate repos right now. Check the links below and if you need any help, just let us know. 

https://github.com/mirumee/saleor/releases/tag/2.9.1
https://github.com/mirumee/saleor-storefront/releases/tag/v0.7.0
https://github.com/mirumee/saleor-dashboard/releases/tag/v2.0.0

**Comment by egyping** [comment]
So it seems three instance must be running to get the entire stack up and running, graphql, storefront and dashboard "8000 - 3000 - 9000"

Do you have any kind of tutorial on how to get all these staffs up and running?

**Comment by karolkielecki** [comment]
We'll be working on the installation guidance and FAQ section. We are aware that our docs need improvements. Please follow the instructions from the links below: 
https://github.com/mirumee/saleor#installation
https://github.com/mirumee/saleor-storefront#getting-started
https://github.com/mirumee/saleor-dashboard#getting-started

**Comment by egyping** [comment]
fine may help me in this issue
when i run npm start its not starting and give this output

    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor-dashboard@2.0.0 start: `webpack-dev-server --open -d`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saleor-dashboard@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fahd/.npm/_logs/2020-02-19T10_37_50_346Z-debug.log

**Comment by karolkielecki** [comment]
Could you please write all the steps you have taken so far?

**Comment by egyping** [comment]
- git clone <dashboard repo>
- cd saleor-dashboard
- in the app.json i changed the API_URI value to  "http://localhost:8000/graphql/" 
- npm install
- npm start

**Comment by egyping** [comment]
exactly same happening with saleor-storefront
graphql http://localhost:8000/graphql/ is up and running

**Comment by egyping** [comment]
(saleor) (base) OfficeMM:saleor-dashboard user$ npm start

> saleor-dashboard@2.0.0 start /Users/user/Desktop/projects/saleor/saleor-dashboard
> webpack-dev-server --open -d

/Users/user/Desktop/projects/saleor/saleor-dashboard/webpack.config.js:39
    throw new Error("Environment variable API_URI not set")
    ^

Error: Environment variable API_URI not set
    at module.exports (/Users/user/Desktop/projects/saleor/saleor-dashboard/webpack.config.js:39:11)
    at handleFunction (/Users/user/Desktop/projects/saleor/saleor-dashboard/node_modules/webpack-cli/bin/utils/prepareOptions.js:21:13)
    at prepareOptions (/Users/user/Desktop/projects/saleor/saleor-dashboard/node_modules/webpack-cli/bin/utils/prepareOptions.js:9:5)
    at requireConfig (/Users/user/Desktop/projects/saleor/saleor-dashboard/node_modules/webpack-cli/bin/utils/convert-argv.js:117:14)
    at /Users/user/Desktop/projects/saleor/saleor-dashboard/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/user/Desktop/projects/saleor/saleor-dashboard/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at Object.<anonymous> (/Users/user/Desktop/projects/saleor/saleor-dashboard/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor-dashboard@2.0.0 start: `webpack-dev-server --open -d`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saleor-dashboard@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-02-19T10_37_50_346Z-debug.log
(saleor) (base) OfficeMM:saleor-dashboard fahd$ npm start

> saleor-dashboard@2.0.0 start /Users/user/Desktop/projects/saleor/saleor-dashboard
> webpack-dev-server --open -d

/Users/user/Desktop/projects/saleor/saleor-dashboard/webpack.config.js:39
    throw new Error("Environment variable API_URI not set")
    ^

Error: Environment variable API_URI not set
    at module.exports (/Users/user/Desktop/projects/saleor/saleor-dashboard/webpack.config.js:39:11)
    at handleFunction (/Users/user/Desktop/projects/saleor/saleor-dashboard/node_modules/webpack-cli/bin/utils/prepareOptions.js:21:13)
    at prepareOptions (/Users/user/Desktop/projects/saleor/saleor-dashboard/node_modules/webpack-cli/bin/utils/prepareOptions.js:9:5)
    at requireConfig (/Users/user/Desktop/projects/saleor/saleor-dashboard/node_modules/webpack-cli/bin/utils/convert-argv.js:117:14)
    at /Users/user/Desktop/projects/saleor/saleor-dashboard/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/user/Desktop/projects/saleor/saleor-dashboard/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at Object.<anonymous> (/Users/user/Desktop/projects/saleor/saleor-dashboard/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor-dashboard@2.0.0 start: `webpack-dev-server --open -d`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saleor-dashboard@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-02-19T10_46_17_034Z-debug.log

**Comment by karolkielecki** [comment]
There is an error - you haven't set API_URI:
https://github.com/mirumee/saleor-storefront#prerequisites
https://github.com/mirumee/saleor-dashboard#configuration

**Comment by egyping** [comment]
If you are running Saleor locally with the default settings, set API_URI to: http://localhost:8000/graphql/.

in which file(s)?

**Comment by karolkielecki** [comment]
For running Saleor with all components, I recommend you to use Docker Compose. You can find the details here: https://saleor.io/blog/running-saleor-with-docker-compose-125/

**Comment by egyping** [comment]
fine 

But kindly let me know which files exactly the API_URI i should change for both storefront and dashboard is it app.json only of both repos or there are other files too?

**Comment by karolkielecki** [comment]
Please follow the instructions from the article. There is a step by step guidance on how to run Saleor with Docker, including info about API_URI

**Comment by egyping** [comment]
@karolkielecki thank you very much 
im very much impressed by the new architecture
without docker i was able to start the three applications  but it needs very powerfull local PC to run
