### ISSUE TITLE
unable to install saleor on redhat linux, keep getting Building wheel for uwsgi (setup.py) ... error

### ISSUE THREAD

**Issue by onelsonic** [mirumee/saleor#5289]
I created a Python virtual environment with version 3.7.3, and also tested with Python version 3.6.8
then I updated pip
`install python -m pip install -U pip`
and also install cairocffi and measurement
```
pip install cairocffi
pip install measurement
```
but I keep getting the wheel  error when installing saleor with this command:
`pip install -r requirements.txt`

below is the detailed error log, any ideas what I am missing?

```
Building wheel for uwsgi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/webroser/virtualenv/saleor/3.7/bin/python3.7_bin -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1z2lkygu/uwsgi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1z2lkygu/uwsgi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mc4lmcjr
       cwd: /tmp/pip-install-1z2lkygu/uwsgi/
  Complete output (38 lines):
  /opt/alt/python37/lib64/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'descriptions'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying uwsgidecorators.py -> build/lib
  installing to build/bdist.linux-x86_64/wheel
  running install
  using profile: buildconf/default.ini
  detected include path: ['/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include', '/usr/include']
  Patching "bin_name" to properly install_scripts dir
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-1z2lkygu/uwsgi/setup.py", line 138, in <module>
      'Programming Language :: Python :: 3.6',
    File "/home/webroser/virtualenv/saleor/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/opt/alt/python37/lib64/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/webroser/virtualenv/saleor/3.7/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "/opt/alt/python37/lib64/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-1z2lkygu/uwsgi/setup.py", line 79, in run
      uc.build_uwsgi(conf)
    File "/tmp/pip-install-1z2lkygu/uwsgi/uwsgiconfig.py", line 276, in build_uwsgi
      t.start()
    File "/opt/alt/python37/lib64/python3.7/threading.py", line 847, in start
      _start_new_thread(self._bootstrap, ())
  RuntimeError: can't start new thread
  ----------------------------------------
  ERROR: Failed building wheel for uwsgi
  Running setup.py clean for uwsgi
Failed to build uwsgi
Installing collected packages: uwsgi, weasyprint
    Running setup.py install for uwsgi ... error
    ERROR: Command errored out with exit status 1:
     command: /home/webroser/virtualenv/saleor/3.7/bin/python3.7_bin -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1z2lkygu/uwsgi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1z2lkygu/uwsgi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uwt4a0jj/install-record.txt --single-version-externally-managed --compile --install-headers /home/webroser/virtualenv/saleor/3.7/include/site/python3.7/uwsgi
         cwd: /tmp/pip-install-1z2lkygu/uwsgi/
    Complete output (25 lines):
    /opt/alt/python37/lib64/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'descriptions'
      warnings.warn(msg)
    running install
    using profile: buildconf/default.ini
    detected include path: ['/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include', '/usr/include']
    Patching "bin_name" to properly install_scripts dir
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1z2lkygu/uwsgi/setup.py", line 138, in <module>
        'Programming Language :: Python :: 3.6',
      File "/home/webroser/virtualenv/saleor/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/opt/alt/python37/lib64/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/alt/python37/lib64/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-1z2lkygu/uwsgi/setup.py", line 79, in run
        uc.build_uwsgi(conf)
      File "/tmp/pip-install-1z2lkygu/uwsgi/uwsgiconfig.py", line 276, in build_uwsgi
        t.start()
      File "/opt/alt/python37/lib64/python3.7/threading.py", line 847, in start
        _start_new_thread(self._bootstrap, ())
    RuntimeError: can't start new thread
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/webroser/virtualenv/saleor/3.7/bin/python3.7_bin -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1z2lkygu/uwsgi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1z2lkygu/uwsgi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uwt4a0jj/install-record.txt --single-version-externally-managed --compile --install-headers /home/webroser/virtualenv/saleor/3.7/include/site/python3.7/uwsgi Check the logs for full command output.
```

**Comment by Labohkip81** [comment]
Have you tried installing locally using docker?  Could be a better way to run the same on redhat.
