### ISSUE TITLE
manage.py migrate failed due to libmagic on MacOS

### ISSUE THREAD

**Issue by xu4wang** [mirumee/saleor#5329]
### What I'm trying to achieve

Following https://docs.saleor.io/docs/getting-started/installation-macos/ to install saleor on MacOS

### Steps to reproduce the problem

1. Install the required lib using pip3, it says python-magic-bin dont match MacOS, ignored

```

WangXus-MacBook-Pro:saleor wangxu$ pip3 install -r requirements.txt --user
Ignoring python-magic-bin: markers 'sys_platform == "win32"' don't match your environment
```

2. python3 manage.py migrate failed to find libmagic

```
WangXus-MacBook-Pro:saleor wangxu$ python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/wangxu/Documents/github/saleor/saleor/extensions/models.py", line 5, in <module>
    from saleor.core.utils.json_serializer import CustomJsonEncoder
  File "/Users/wangxu/Documents/github/saleor/saleor/core/utils/__init__.py", line 17, in <module>
    from versatileimagefield.image_warmer import VersatileImageFieldWarmer
  File "/usr/local/lib/python3.7/site-packages/versatileimagefield/image_warmer.py", line 11, in <module>
    from .utils import (
  File "/usr/local/lib/python3.7/site-packages/versatileimagefield/utils.py", line 7, in <module>
    import magic
  File "/Users/wangxu/Library/Python/3.7/lib/python/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
WangXus-MacBook-Pro:saleor wangxu$

```

### What I expected to happen

manage.py migrate should prepare the database for MacOS too.

**System information**
Operating system: MacOS Catalina Version 10.15.3

**Comment by xu4wang** [comment]
tried to manually install libmagic by pip3 and brew, with no luck

```
 2690  pip3 uninstall python-magic
 2692  pip3 install python-magic-bin==0.4.14
```

```
 2698  brew install libmagic
```

**Comment by xu4wang** [comment]
After upgrade python to 3.8. issue was solved.

on MacOS, ``` brew install python``` will install python 3.7 at the time being.

**Comment by david-daming** [comment]
I meet with the same issue on macbook pro 16inch 2.3 64GB, with python 3.8.2. 
after I installed the missed package with homebrew:
`brew install libmagic`
then the issue was fixed.

I don't think it's associated with your python 3.8.

**Comment by xu4wang** [comment]
OK. based on the information from you and myself:
