### ISSUE TITLE
Uncaught (in promise) Error: GraphQL error: 'list' object has no attribute 'lower'

### ISSUE THREAD

**Issue by appleyuchi** [mirumee/saleor#5349]
### What I'm trying to achieve
…
IN VPS deployment

### Steps to reproduce the problem
1. register new account after I input mail and password
2. press"register "button

F12 web page said:

```
bundle.esm.js:63 Uncaught (in promise) Error: GraphQL error: 'list' object has no attribute 'lower'
    at new ApolloError (bundle.esm.js:63)
    at Object.next (bundle.esm.js:1004)
    at notifySubscription (Observable.js:135)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.next (Observable.js:235)
    at bundle.esm.js:866
    at Set.forEach (<anonymous>)
    at Object.next (bundle.esm.js:866)
    at notifySubscription (Observable.js:135)
    at onNotify (Observable.js:179)
```

<details>
<summary>My pip dependencies for python3.6 is:</summary>

```
alabaster==0.7.12
amqp==2.5.2
aniso8601==7.0.0
apipkg==1.5
appdirs==1.4.3
asgiref==3.2.3
aspy.yaml==1.3.0
astroid==2.3.3
attrs==19.3.0
autopep8==1.5
Babel==2.7.0
backcall==0.1.0
beautifulsoup4==4.7.1
beautifultable==0.7.0
billiard==3.6.2.0
black==19.10b0
bleach==2.1.4
boto3==1.12.3
botocore==1.15.3
braintree==3.49.0
cachetools==4.0.0
cairocffi==1.1.0
CairoSVG==2.4.2
celery==4.4.0
certifi==2019.11.28
cffi==1.14.0
cfgv==3.0.0
chardet==3.0.4
Click==7.0
codecov==2.0.15
colorama==0.4.3
coverage==4.5.4
cryptography==2.8
cssselect2==0.2.2
dataclasses==0.7
decorator==4.4.1
defusedxml==0.6.0
distlib==0.3.0
dj-database-url==0.5.0
dj-email-url==0.2.0
Django==3.0.4
django-appconf==1.0.3
django-countries==5.5
django-debug-toolbar==2.2
django-debug-toolbar-request-history==0.1.1
django-environ==0.4.5
django-extensions==2.2.8
django-extra-views==0.11.0
django-filter==2.2.0
django-graphiql-debug-toolbar==0.1.4
django-graphql-jwt==0.3.0
django-haystack==2.8.1
django-js-asset==1.2.2
django-localflavor==3.0
django-measurement==3.2.0
django-mptt==0.11.0
django-oscar==2.0.4
# Editable install with no version control (django-oscar-paypal==2.0.0)
-e /root/.virtualenvs/python3.6/lib/python3.6/site-packages
django-phonenumber-field==2.4.0
django-prices==2.2.0
django-prices-openexchangerates==1.1.0
django-prices-vatlayer==1.0.2
django-redis==4.11.0
django-render-block==0.6
django-silk==2.0.0
django-storages==1.9.1
django-stubs==1.2.0
django-tables2==1.21.2
django-templated-email==2.3.0
django-treebeard==4.3.1
django-versatileimagefield==2.0
django-webtest==1.9.7
django-widget-tweaks==1.4.5
docutils==0.15.2
draftjs-sanitizer==1.0.0
easy-thumbnails==2.7
enmerkar==0.7.1
entrypoints==0.3
execnet==1.7.1
factory-boy==2.12.0
Faker==2.0.5
filelock==3.0.12
flake8==3.7.9
flake8-blind-except==0.1.1
flake8-debugger==3.2.1
Flask==1.1.1
freezegun==0.3.15
google-api-core==1.16.0
google-auth==1.11.2
google-cloud-core==1.3.0
google-cloud-storage==1.26.0
google-i18n-address==2.3.5
google-measurement-protocol==1.0.0
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0
gprof2dot==2016.10.13
graphene==2.1.8
graphene-django==2.8.2
graphene-django-optimizer==0.6.1
graphene-federation==0.0.3
graphql-core==2.3.1
graphql-relay==2.0.1
html-to-draftjs==1.0.1
html5lib==1.0.1
identify==1.4.11
idna==2.9
imagesize==1.2.0
importlib-metadata==1.5.0
importlib-resources==1.0.2
ipdb==0.12.3
ipython==7.12.0
ipython-genutils==0.2.0
isort==4.3.21
itsdangerous==1.1.0
jaeger-client==4.3.0
jedi==0.16.0
Jinja2==2.11.1
jmespath==0.9.4
jsonfield==3.0.0
kombu==4.6.7
lazy-object-proxy==1.4.3
lxml==4.5.0
Markdown==3.2.1
MarkupSafe==1.1.1
maxminddb==1.5.2
maxminddb-geolite2==2018.703
mccabe==0.6.1
measurement==3.2.0
more-itertools==8.2.0
mpmath==1.1.0
multidict==4.7.4
mypy==0.740
mypy-extensions==0.4.3
nodeenv==1.3.5
oauthlib==3.1.0
opentracing==2.3.0
packaging==20.1
parso==0.6.2
pathspec==0.7.0
pbr==5.4.4
pexpect==4.8.0
phonenumbers==8.11.4
phonenumberslite==8.11.4
pickleshare==0.7.5
Pillow==7.0.0
pkg-resources==0.0.0
pluggy==0.13.1
pre-commit==1.21.0
prices==1.0.0
promise==2.3
prompt-toolkit==3.0.3
protobuf==3.11.3
psycopg2-binary==2.8.4
ptyprocess==0.6.0
purl==1.5
py==1.8.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.5.0
pycountry==19.8.18
pycparser==2.19
pycryptodomex==3.9.4
pydocstyle==4.0.1
pyflakes==2.1.1
Pygments==2.5.2
PyJWT==1.7.1
pylint==2.4.4
pylint-celery==0.3
pylint-django==2.0.13
pylint-plugin-utils==0.6
pyOpenSSL==19.1.0
pyparsing==2.4.6
Pyphen==0.9.5
pyprof2calltree==1.4.4
pysolr==3.8.1
pytest==5.3.5
pytest-cov==2.8.1
pytest-django==3.8.0
pytest-django-queries==1.1.0
pytest-forked==1.1.3
pytest-mock==1.13.0
pytest-runner==5.2
pytest-vcr==1.0.2
pytest-xdist==1.31.0
python-alipay-sdk==2.0.1
python-dateutil==2.8.1
python-magic==0.4.15
python-slugify==1.2.6
python-stdnum==1.13
pytz==2019.3
PyYAML==5.3
razorpay==1.2.0
redis==3.4.1
regex==2020.2.18
requests==2.23.0
rsa==4.0
Rx==1.6.1
s3transfer==0.3.3
sentry-sdk==0.14.1
setuptools-scm==3.5.0
singledispatch==3.4.0.3
six==1.14.0
snowballstemmer==2.0.0
sorl-thumbnail==12.6.3
soupsieve==1.9.5
Sphinx==2.4.4
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sqlparse==0.3.0
stripe==2.42.0
sympy==1.5.1
text-unidecode==1.3
threadloop==1.0.2
thrift==0.13.0
tinycss2==1.0.2
toml==0.10.0
tornado==6.0.3
tox==3.14.5
tqdm==4.43.0
traitlets==4.3.3
transifex-client==0.13.7
typed-ast==1.4.1
typing==3.7.4.1
typing-extensions==3.7.4.1
Unidecode==1.1.1
urllib3==1.25.8
uWSGI==2.0.18
vcrpy==4.0.2
vine==1.3.0
virtualenv==20.0.4
waitress==1.4.3
wcwidth==0.1.8
WeasyPrint==51
webencodings==0.5.1
WebOb==1.8.6
WebTest==2.0.34
Werkzeug==1.0.0
whitenoise==5.0.1
Whoosh==2.7.4
wrapt==1.11.2
yarl==1.4.2
zipp==3.0.0
```

</details>

### What I expected to happen
…

### Screenshots

![bug](https://user-images.githubusercontent.com/27613483/76499781-58fd3b80-647a-11ea-856a-5ccbd9526753.png)

**System information**
Operating system:
Ubuntu19.10

Could anyone help me?
Thanks for your help~

**Comment by appleyuchi** [comment]
error in terminal is:

ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:27664:Thread-9]
Traceback (most recent call last):
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/promise/promise.py", line 489, in _resolve_from_executor
    executor(resolve, reject)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/promise/promise.py", line 756, in executor
    return resolve(f(*args, **kwargs))
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
    return next(*args, **kwargs)
  File "/root/saleor_rawstone/saleor/saleor/graphql/account/mutations/account.py", line 55, in mutate
    response = super().mutate(root, info, **data)
  File "/root/saleor_rawstone/saleor/saleor/graphql/core/mutations.py", line 282, in mutate
    response = cls.perform_mutation(root, info, **data)
  File "/root/saleor_rawstone/saleor/saleor/graphql/core/mutations.py", line 451, in perform_mutation
    cleaned_input = cls.clean_input(info, instance, data)
  File "/root/saleor_rawstone/saleor/saleor/graphql/account/mutations/account.py", line 73, in clean_input
    validate_storefront_url(data["redirect_url"])
  File "/root/saleor_rawstone/saleor/saleor/core/utils/url.py", line 23, in validate_storefront_url
    if not validate_host(domain, settings.ALLOWED_CLIENT_HOSTS):
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/django/http/request.py", line 611, in validate_host
    return any(pattern == '*' or is_same_domain(host, pattern) for pattern in allowed_hosts)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/django/http/request.py", line 611, in <genexpr>
    return any(pattern == '*' or is_same_domain(host, pattern) for pattern in allowed_hosts)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/django/utils/http.py", line 294, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'list' object has no attribute 'lower'

**Comment by maarcingebala** [comment]
@appleyuchi If you're running Saleor core from `master`, please use Python 3.8 and let me know if this issue happens then as well.

**Comment by appleyuchi** [comment]
> ase use Python 3.8 and let me know if this issue happens then as well.

Thanks for your replies,
I have solved it,
the solution is:

#ALLOWED_CLIENT_HOSTS =[get_list(
#   os.environ.get("ALLOWED_CLIENT_HOSTS", _DEFAULT_CLIENT_HOSTS)
#),"106.14.24.151"]

ALLOWED_CLIENT_HOSTS=["localhost","127.0.0.1","106.14.24.151"]
