### ISSUE TITLE
raise exceptions.JSONWebTokenError(_('User is disabled'))

### ISSUE THREAD

**Issue by appleyuchi** [mirumee/saleor#5356]
### What I'm trying to achieve
python 3.6
node 10.15.2
saleor
saleor-storefront
ubuntu 18.04

### Steps to reproduce the problem
1. when I try to login/register
2. I get the log:
pattern= 106.14.24.151
INFO django.server "OPTIONS /graphql/ HTTP/1.1" 200 0 [PID:20634:Thread-5]
INFO django.server "OPTIONS /graphql/ HTTP/1.1" 200 0 [PID:20634:Thread-5]
INFO django.server "OPTIONS /graphql/ HTTP/1.1" 200 0 [PID:20634:Thread-5]
pattern= 106.14.24.151
pattern= 106.14.24.151
user= None
pattern= 106.14.24.151
INFO celery.app.trace Task saleor.account.emails._send_account_confirmation_email[209f805b-8223-421b-8af4-6514eec57203] succeeded in 4.563294419000158s: None [PID:20634:Thread-5]
INFO celery.app.trace Task saleor.extensions.plugins.webhook.tasks.trigger_webhooks_for_event[bda3bc85-c445-4905-acd4-2d1b1ca9b273] succeeded in 0.007309742999495938s: None [PID:20634:Thread-5]
user= appleyuchi@163.com
ERROR graphql.execution.executor An error occurred while resolving field AccountRegister.errors [PID:20634:Thread-5]
Traceback (most recent call last):
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/root/saleor_docker/saleor/saleor/graphql/middleware.py", line 60, in service_account_middleware
    return next(root, info, **kwargs)
  File "/root/saleor_docker/saleor/saleor/graphql/middleware.py", line 22, in resolve
    return super().resolve(next, root, info, **kwargs)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/middleware.py", line 72, in resolve
    user = authenticate(request=context, **kwargs)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/backends.py", line 14, in authenticate
    return get_user_by_token(token, request)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/shortcuts.py", line 21, in get_user_by_token
    return get_user_by_payload(payload)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/utils.py", line 113, in get_user_by_payload
    raise exceptions.JSONWebTokenError(_('User is disabled'))
graphql_jwt.exceptions.JSONWebTokenError: User is disabled
ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:20634:Thread-5]
Traceback (most recent call last):
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/root/saleor_docker/saleor/saleor/graphql/middleware.py", line 60, in service_account_middleware
    return next(root, info, **kwargs)
  File "/root/saleor_docker/saleor/saleor/graphql/middleware.py", line 22, in resolve
    return super().resolve(next, root, info, **kwargs)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/middleware.py", line 72, in resolve
    user = authenticate(request=context, **kwargs)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/backends.py", line 14, in authenticate
    return get_user_by_token(token, request)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/shortcuts.py", line 21, in get_user_by_token
    return get_user_by_payload(payload)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/utils.py", line 113, in get_user_by_payload
    raise exceptions.JSONWebTokenError(_('User is disabled'))
graphql_jwt.exceptions.JSONWebTokenError: User is disabled
ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:20634:Thread-5]
Traceback (most recent call last):
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/root/saleor_docker/saleor/saleor/graphql/middleware.py", line 60, in service_account_middleware
    return next(root, info, **kwargs)
  File "/root/saleor_docker/saleor/saleor/graphql/middleware.py", line 22, in resolve
    return super().resolve(next, root, info, **kwargs)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/middleware.py", line 72, in resolve
    user = authenticate(request=context, **kwargs)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/backends.py", line 14, in authenticate
    return get_user_by_token(token, request)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/shortcuts.py", line 21, in get_user_by_token
    return get_user_by_payload(payload)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/utils.py", line 113, in get_user_by_payload
    raise exceptions.JSONWebTokenError(_('User is disabled'))
graphql_jwt.exceptions.JSONWebTokenError: User is disabled
ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:20634:Thread-5]
Traceback (most recent call last):
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/root/saleor_docker/saleor/saleor/graphql/middleware.py", line 60, in service_account_middleware
    return next(root, info, **kwargs)
  File "/root/saleor_docker/saleor/saleor/graphql/middleware.py", line 22, in resolve
    return super().resolve(next, root, info, **kwargs)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/middleware.py", line 72, in resolve
    user = authenticate(request=context, **kwargs)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/backends.py", line 14, in authenticate
    return get_user_by_token(token, request)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/shortcuts.py", line 21, in get_user_by_token
    return get_user_by_payload(payload)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/utils.py", line 113, in get_user_by_payload
    raise exceptions.JSONWebTokenError(_('User is disabled'))
graphql_jwt.exceptions.JSONWebTokenError: User is disabled
INFO django.server "POST /graphql/ HTTP/1.1" 200 1887 [PID:20634:Thread-5]
INFO django.server "POST /graphql/ HTTP/1.1" 200 1887 [PID:20634:Thread-5]
INFO django.server "POST /graphql/ HTTP/1.1" 200 1887 [PID:20634:Thread-5]

### What I expected to happen
…

### Screenshots

![后端报错](https://user-images.githubusercontent.com/27613483/76724678-bfd66980-6786-11ea-94b0-030cd86f7672.png)

**System information**
Operating system:

**Comment by appleyuchi** [comment]
![网页报错](https://user-images.githubusercontent.com/27613483/76726736-075ff400-678d-11ea-9b76-35f2ce3aec96.png)

**Comment by appleyuchi** [comment]
the start command is:
#python manage.py runserver  0.0.0.0:8000
INFO django.utils.autoreload Watching for file changes with StatReloader [PID:24598:MainThread]
INFO django.utils.autoreload Watching for file changes with StatReloader [PID:24598:MainThread]
Performing system checks...

/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphene_django/types.py:95: UserWarning: Field name "namepermissions" doesn't exist on Django model "account.ServiceAccount". Consider removing the field from the "fields" list of DjangoObjectType "ServiceAccount" because it has no effect.
  type_=type_,
/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphene_django/types.py:95: UserWarning: Field name "token" doesn't exist on Django model "account.User". Consider removing the field from the "fields" list of DjangoObjectType "User" because it has no effect.
  type_=type_,
System check identified no issues (0 silenced).
March 16, 2020 - 01:59:56
Django version 3.0.4, using settings 'saleor.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

**Comment by appleyuchi** [comment]
I set following setences in my .bashrc
export APP_MOUNT_URI="/dashboard/"
export API_URI="http://106.14.24.151:8000/graphql/"

**Comment by maarcingebala** [comment]
@appleyuchi From what I see in the source code the error `User is disabled` is thrown by the JWT library that we use: https://github.com/flavors/django-graphql-jwt/blob/49826780881ede1554c265fab1b3b41a4c038d05/graphql_jwt/utils.py#L113

How did you create the user that you're trying to log in? With one of the commands like `python manage.py populatedb --createsuperuser` or `python manage.py createsuperuser`? These commands should create the admin user properly. In your case, it seems that the `is_active` flag is `False`, but this should throw a different error saying that your credentials are wrong.

**Comment by maarcingebala** [comment]
Also please use Python 3.8.

**Comment by appleyuchi** [comment]
> Also please use Python 3.8.
Thanks for your replies....@maarcingebala
It's my fault that I did not tell it clearly~

`python manage.py populatedb --createsuperuser` is used and
dashboard is OK to login(http://106.14.24.151:9000/).
but saleor-storefront fail to login/register.
could you click

#-----------------------------------------------------------------
I have read saleor document and got that python 3.8 is recommended,
the reason why I did not use python3.8 is that:
after  I create virtualenv for python3.8 and use `pip install -r requirements.txt`
it will need me to install"apt install python3-dev"(version 3.8),
otherwise it will say“Python.h not found”
but the VPS default is python3-dev(version 3.6)
if I install python3-dev(version 3.8) by force,I worry that the system will become unstable.

I did not find a stable way to install python3-dev(version 3.8) in ubuntu18.04.

**Comment by maarcingebala** [comment]
@appleyuchi I personally use [pyenv](https://github.com/pyenv/pyenv) for managing Python versions and it works great for me.

**Comment by appleyuchi** [comment]
> @appleyuchi I personally use [pyenv](https://github.com/pyenv/pyenv) for managing Python versions and it works great for me.

@maarcingebala 
the name of virtual environment I use is :"virtualenv",
although more than 90% can be installed with pip when I' m in "virtualenv".
but sometimes, it need the support from the system,
only after system component is installed,then can `pip install xxxx` be successful

**Comment by appleyuchi** [comment]
@maarcingebala 
The reason why I did not use the stable version of saleor-storefront is that:
I have a same error as follows:
mirumee/saleor-storefront#570

**Comment by appleyuchi** [comment]
@maarcingebala 
is it possbile to  replicate the same error with 106.14.24.151:8000/graphql only?
I mean if there's a way to emulate such behavior register/login
in GraphQL webpage.

**Comment by venkat402** [comment]
Still i had same the problem 
raise exceptions.JSONWebTokenError(_('User is disabled'))
How to resolve this one
