### ISSUE TITLE
Error: permission denied for table product_product occures after delete product call

### ISSUE THREAD

**Issue by PiotrLaszczyk** [mirumee/saleor#5412]
### Steps to reproduce the problem
1. My script was creating/updating products according to actual business offer. It works in some continues loop for some days.. was correct
2. Yesterday I implemented deleting discontinued products.. 
3. Today what I see is that privileges in database are broken on products. Cannot create new product.. 

I was using only /graphql endpoint. Without dashboard... so it should not happen I guess .. 

### Error:
query which fails:
```
mutation createProduct($productTypeId: ID!, $categoryId: ID!, $name: String!, $sku: String, $quantity: Int, $trackInventory: Boolean, $isPublished: Boolean!, $chargeTaxes: Boolean!, $taxCode: String!, $basePrice: Decimal!, $descriptionJson: JSONString!, $attributes: [AttributeValueInput!]) {
 productCreate(input: {category: $categoryId, productType: $productTypeId, name: $name, basePrice: $basePrice, sku: $sku, quantity: $quantity, trackInventory: $trackInventory, chargeTaxes: $chargeTaxes, isPublished: $isPublished, taxCode: $taxCode, descriptionJson: $descriptionJson, attributes: $attributes}) {
```

variables:
` {'productTypeId': 'UHJvZHVjdFR5cGU6MTMw', 'categoryId': 'Q2F0ZWdvcnk6MTY5', 'name': 'ProductName', 'basePrice': '53.25', 'sku': '30010198', 'quantity': 3, 'trackInventory': True, 'isPublished': True, 'chargeTaxes': True, 'taxCode': 'STANDARD', 'descriptionJson': '{"blocks": [{"key": "", "data": {}, "text": "Some description", "type": "unstyled", "depth": 0, "entityRanges": [], "inlineStyleRanges": []}, {"key": "", "data": {}, "text": " ", "type": "unstyled", "depth": 0, "entityRanges": [], "inlineStyleRanges": []}], "entityMap": {"0": {"data": {"href": "https://github.com/mirumee/saleor"}, "type": "LINK", "mutability": "MUTABLE"}}}', 'attributes': [{'id': 'QXR0cmlidXRlOjM=', 'values': ['some-attribute']}]}`

And till yesterday it worked fine... but now now after product delete call I receive:
```
2020-03-30T13:47:31.717166+00:00 app[web.1]: ERROR graphql.execution.utils Traceback (most recent call last):
2020-03-30T13:47:31.717169+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/promise/promise.py", line 487, in _resolve_from_executor
2020-03-30T13:47:31.717170+00:00 app[web.1]: executor(resolve, reject)
2020-03-30T13:47:31.717171+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/promise/promise.py", line 754, in executor
2020-03-30T13:47:31.717171+00:00 app[web.1]: return resolve(f(*args, **kwargs))
2020-03-30T13:47:31.717172+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
2020-03-30T13:47:31.717172+00:00 app[web.1]: return next(*args, **kwargs)
2020-03-30T13:47:31.717173+00:00 app[web.1]: File "./saleor/graphql/core/mutations.py", line 279, in mutate
2020-03-30T13:47:31.717173+00:00 app[web.1]: response = cls.perform_mutation(root, info, **data)
2020-03-30T13:47:31.717174+00:00 app[web.1]: File "./saleor/graphql/core/mutations.py", line 451, in perform_mutation
2020-03-30T13:47:31.717174+00:00 app[web.1]: cls.save(info, instance, cleaned_input)
2020-03-30T13:47:31.717175+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/contextlib.py", line 74, in inner
2020-03-30T13:47:31.717175+00:00 app[web.1]: return func(*args, **kwds)
2020-03-30T13:47:31.717175+00:00 app[web.1]: File "./saleor/graphql/product/mutations/products.py", line 852, in save
2020-03-30T13:47:31.717176+00:00 app[web.1]: instance.save()
2020-03-30T13:47:31.717176+00:00 app[web.1]: File "./saleor/product/models.py", line 318, in save
2020-03-30T13:47:31.717178+00:00 app[web.1]: return super().save(force_insert, force_update, using, update_fields)
2020-03-30T13:47:31.717179+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
2020-03-30T13:47:31.717179+00:00 app[web.1]: force_update=force_update, update_fields=update_fields)
2020-03-30T13:47:31.717185+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
2020-03-30T13:47:31.717185+00:00 app[web.1]: force_update, using, update_fields,
2020-03-30T13:47:31.717186+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
2020-03-30T13:47:31.717186+00:00 app[web.1]: result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
2020-03-30T13:47:31.717186+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
2020-03-30T13:47:31.717187+00:00 app[web.1]: using=using, raw=raw)
2020-03-30T13:47:31.717187+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
2020-03-30T13:47:31.717188+00:00 app[web.1]: return getattr(self.get_queryset(), name)(*args, **kwargs)
2020-03-30T13:47:31.717188+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
2020-03-30T13:47:31.717188+00:00 app[web.1]: return query.get_compiler(using=using).execute_sql(return_id)
2020-03-30T13:47:31.717189+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
2020-03-30T13:47:31.717189+00:00 app[web.1]: cursor.execute(sql, params)
2020-03-30T13:47:31.717190+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/graphene_django/debug/sql/tracking.py", line 155, in execute
2020-03-30T13:47:31.717190+00:00 app[web.1]: return self._record(self.cursor.execute, sql, params)
2020-03-30T13:47:31.717190+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/graphene_django/debug/sql/tracking.py", line 101, in _record
2020-03-30T13:47:31.717191+00:00 app[web.1]: return method(sql, params)
2020-03-30T13:47:31.717191+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
2020-03-30T13:47:31.717191+00:00 app[web.1]: return super().execute(sql, params)
2020-03-30T13:47:31.717192+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
2020-03-30T13:47:31.717192+00:00 app[web.1]: return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2020-03-30T13:47:31.717193+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
2020-03-30T13:47:31.717193+00:00 app[web.1]: return executor(sql, params, many, context)
2020-03-30T13:47:31.717193+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
2020-03-30T13:47:31.717193+00:00 app[web.1]: return self.cursor.execute(sql, params)
2020-03-30T13:47:31.717194+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
2020-03-30T13:47:31.717194+00:00 app[web.1]: raise dj_exc_value.with_traceback(traceback) from exc_value
2020-03-30T13:47:31.717194+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
2020-03-30T13:47:31.717195+00:00 app[web.1]: return self.cursor.execute(sql, params)
2020-03-30T13:47:31.717195+00:00 app[web.1]: graphql.error.located_error.GraphQLLocatedError: permission denied for table product_product
2020-03-30T13:47:31.717196+00:00 app[web.1]: 
2020-03-30T13:47:31.717196+00:00 app[web.1]: [PID:16151:uWSGIWorker1Core0]
2020-03-30T13:47:31.723206+00:00 app[web.1]: ERROR saleor.graphql.views Exception information: [PID:16151:uWSGIWorker1Core0]
2020-03-30T13:47:31.723207+00:00 app[web.1]: Traceback (most recent call last):
2020-03-30T13:47:31.723208+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
2020-03-30T13:47:31.723208+00:00 app[web.1]: return self.cursor.execute(sql, params)
2020-03-30T13:47:31.723209+00:00 app[web.1]: psycopg2.errors.InsufficientPrivilege: permission denied for table product_product
2020-03-30T13:47:31.723209+00:00 app[web.1]: 
2020-03-30T13:47:31.723209+00:00 app[web.1]: 
2020-03-30T13:47:31.723210+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2020-03-30T13:47:31.723210+00:00 app[web.1]: 
2020-03-30T13:47:31.723211+00:00 app[web.1]: Traceback (most recent call last):
2020-03-30T13:47:31.723211+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/promise/promise.py", line 487, in _resolve_from_executor
2020-03-30T13:47:31.723212+00:00 app[web.1]: executor(resolve, reject)
2020-03-30T13:47:31.723212+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/promise/promise.py", line 754, in executor
2020-03-30T13:47:31.723212+00:00 app[web.1]: return resolve(f(*args, **kwargs))
2020-03-30T13:47:31.723213+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
2020-03-30T13:47:31.723213+00:00 app[web.1]: return next(*args, **kwargs)
2020-03-30T13:47:31.723213+00:00 app[web.1]: File "./saleor/graphql/core/mutations.py", line 279, in mutate
2020-03-30T13:47:31.723214+00:00 app[web.1]: response = cls.perform_mutation(root, info, **data)
2020-03-30T13:47:31.723214+00:00 app[web.1]: File "./saleor/graphql/core/mutations.py", line 451, in perform_mutation
2020-03-30T13:47:31.723215+00:00 app[web.1]: cls.save(info, instance, cleaned_input)
2020-03-30T13:47:31.723215+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/contextlib.py", line 74, in inner
2020-03-30T13:47:31.723215+00:00 app[web.1]: return func(*args, **kwds)
2020-03-30T13:47:31.723216+00:00 app[web.1]: File "./saleor/graphql/product/mutations/products.py", line 852, in save
2020-03-30T13:47:31.723216+00:00 app[web.1]: instance.save()
2020-03-30T13:47:31.723217+00:00 app[web.1]: File "./saleor/product/models.py", line 318, in save
2020-03-30T13:47:31.723217+00:00 app[web.1]: return super().save(force_insert, force_update, using, update_fields)
2020-03-30T13:47:31.723218+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
2020-03-30T13:47:31.723218+00:00 app[web.1]: force_update=force_update, update_fields=update_fields)
2020-03-30T13:47:31.723218+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
2020-03-30T13:47:31.723219+00:00 app[web.1]: force_update, using, update_fields,
2020-03-30T13:47:31.723219+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
2020-03-30T13:47:31.723220+00:00 app[web.1]: result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
2020-03-30T13:47:31.723220+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
2020-03-30T13:47:31.723220+00:00 app[web.1]: using=using, raw=raw)
2020-03-30T13:47:31.723221+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
2020-03-30T13:47:31.723221+00:00 app[web.1]: return getattr(self.get_queryset(), name)(*args, **kwargs)
2020-03-30T13:47:31.723221+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
2020-03-30T13:47:31.723222+00:00 app[web.1]: return query.get_compiler(using=using).execute_sql(return_id)
2020-03-30T13:47:31.723222+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
2020-03-30T13:47:31.723222+00:00 app[web.1]: cursor.execute(sql, params)
2020-03-30T13:47:31.723223+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/graphene_django/debug/sql/tracking.py", line 155, in execute
2020-03-30T13:47:31.723223+00:00 app[web.1]: return self._record(self.cursor.execute, sql, params)
2020-03-30T13:47:31.723223+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/graphene_django/debug/sql/tracking.py", line 101, in _record
2020-03-30T13:47:31.723224+00:00 app[web.1]: return method(sql, params)
2020-03-30T13:47:31.723224+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
2020-03-30T13:47:31.723224+00:00 app[web.1]: return super().execute(sql, params)
2020-03-30T13:47:31.723225+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
2020-03-30T13:47:31.723225+00:00 app[web.1]: return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2020-03-30T13:47:31.723225+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
2020-03-30T13:47:31.723226+00:00 app[web.1]: return executor(sql, params, many, context)
2020-03-30T13:47:31.723226+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
2020-03-30T13:47:31.723226+00:00 app[web.1]: return self.cursor.execute(sql, params)
2020-03-30T13:47:31.723227+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
2020-03-30T13:47:31.723227+00:00 app[web.1]: raise dj_exc_value.with_traceback(traceback) from exc_value
2020-03-30T13:47:31.723227+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
2020-03-30T13:47:31.723228+00:00 app[web.1]: return self.cursor.execute(sql, params)
2020-03-30T13:47:31.723228+00:00 app[web.1]: django.db.utils.ProgrammingError: permission denied for table product_product
2020-03-30T13:47:31.723228+00:00 app[web.1]: 
2020-03-30T13:47:31.723654+00:00 app[web.1]: ERROR saleor.graphql.views Exception information: [PID:16151:uWSGIWorker1Core0]
2020-03-30T13:47:31.723655+00:00 app[web.1]: Traceback (most recent call last):
2020-03-30T13:47:31.723655+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
2020-03-30T13:47:31.723656+00:00 app[web.1]: return self.cursor.execute(sql, params)
2020-03-30T13:47:31.723656+00:00 app[web.1]: psycopg2.errors.InsufficientPrivilege: permission denied for table product_product
2020-03-30T13:47:31.723656+00:00 app[web.1]: 
2020-03-30T13:47:31.723657+00:00 app[web.1]: 
2020-03-30T13:47:31.723657+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2020-03-30T13:47:31.723657+00:00 app[web.1]: 
2020-03-30T13:47:31.723658+00:00 app[web.1]: Traceback (most recent call last):
2020-03-30T13:47:31.723673+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/promise/promise.py", line 487, in _resolve_from_executor
2020-03-30T13:47:31.723674+00:00 app[web.1]: executor(resolve, reject)
2020-03-30T13:47:31.723674+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/promise/promise.py", line 754, in executor
2020-03-30T13:47:31.723674+00:00 app[web.1]: return resolve(f(*args, **kwargs))
2020-03-30T13:47:31.723675+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
2020-03-30T13:47:31.723675+00:00 app[web.1]: return next(*args, **kwargs)
2020-03-30T13:47:31.723675+00:00 app[web.1]: File "./saleor/graphql/core/mutations.py", line 279, in mutate
2020-03-30T13:47:31.723676+00:00 app[web.1]: response = cls.perform_mutation(root, info, **data)
2020-03-30T13:47:31.723676+00:00 app[web.1]: File "./saleor/graphql/core/mutations.py", line 451, in perform_mutation
2020-03-30T13:47:31.723677+00:00 app[web.1]: cls.save(info, instance, cleaned_input)
2020-03-30T13:47:31.723677+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/contextlib.py", line 74, in inner
2020-03-30T13:47:31.723677+00:00 app[web.1]: return func(*args, **kwds)
2020-03-30T13:47:31.723678+00:00 app[web.1]: File "./saleor/graphql/product/mutations/products.py", line 852, in save
2020-03-30T13:47:31.723678+00:00 app[web.1]: instance.save()
2020-03-30T13:47:31.723678+00:00 app[web.1]: File "./saleor/product/models.py", line 318, in save
2020-03-30T13:47:31.723679+00:00 app[web.1]: return super().save(force_insert, force_update, using, update_fields)
2020-03-30T13:47:31.723679+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
2020-03-30T13:47:31.723679+00:00 app[web.1]: force_update=force_update, update_fields=update_fields)
2020-03-30T13:47:31.723680+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
2020-03-30T13:47:31.723680+00:00 app[web.1]: force_update, using, update_fields,
2020-03-30T13:47:31.723680+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
2020-03-30T13:47:31.723680+00:00 app[web.1]: result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
2020-03-30T13:47:31.723681+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
2020-03-30T13:47:31.723681+00:00 app[web.1]: using=using, raw=raw)
2020-03-30T13:47:31.723681+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
2020-03-30T13:47:31.723682+00:00 app[web.1]: return getattr(self.get_queryset(), name)(*args, **kwargs)
2020-03-30T13:47:31.723682+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
2020-03-30T13:47:31.723682+00:00 app[web.1]: return query.get_compiler(using=using).execute_sql(return_id)
2020-03-30T13:47:31.723683+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
2020-03-30T13:47:31.723683+00:00 app[web.1]: cursor.execute(sql, params)
2020-03-30T13:47:31.723683+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/graphene_django/debug/sql/tracking.py", line 155, in execute
2020-03-30T13:47:31.723684+00:00 app[web.1]: return self._record(self.cursor.execute, sql, params)
2020-03-30T13:47:31.723684+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/graphene_django/debug/sql/tracking.py", line 101, in _record
2020-03-30T13:47:31.723684+00:00 app[web.1]: return method(sql, params)
2020-03-30T13:47:31.723685+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
2020-03-30T13:47:31.723685+00:00 app[web.1]: return super().execute(sql, params)
2020-03-30T13:47:31.723685+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
2020-03-30T13:47:31.723686+00:00 app[web.1]: return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2020-03-30T13:47:31.723686+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
2020-03-30T13:47:31.723686+00:00 app[web.1]: return executor(sql, params, many, context)
2020-03-30T13:47:31.723687+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
2020-03-30T13:47:31.723687+00:00 app[web.1]: return self.cursor.execute(sql, params)
2020-03-30T13:47:31.723687+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
2020-03-30T13:47:31.723688+00:00 app[web.1]: raise dj_exc_value.with_traceback(traceback) from exc_value
2020-03-30T13:47:31.723688+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
2020-03-30T13:47:31.723689+00:00 app[web.1]: return self.cursor.execute(sql, params)
2020-03-30T13:47:31.723689+00:00 app[web.1]: django.db.utils.ProgrammingError: permission denied for table product_product
```

Operating system:
Heroku, saleor 2.9.0

**Comment by PiotrLaszczyk** [comment]
Ehh... its issue generated by heroku postgres db and its hobby plan:
https://help.heroku.com/JIFZYOSR/write-access-revoked-on-postgres-hobby-databases

I will live this hint as maybe would be helpfull to someone.
