### ISSUE TITLE
 Please Help! The SECRET_KEY setting must not be empty. Ubuntu 18.04

### ISSUE THREAD

**Issue by NIKITAdotONE** [mirumee/saleor#5448]
Hello,

I'm trying to install saleor on local server with Ubuntu 18.04 for first time, Pyenv and Poetry with python 3.8.2
Get an error when run python manage.py migrate in poetry shell with pyenv 3.8.2.
I'm newbie and i need your help.
Think Saleor is the best but i can't install it. Please help me.

I have only two changes in stock saleor. 

Only in settings.py:

DATABASES = {
    "default": dj_database_url.config(
        default="postgres://postgres:420420420@localhost:5432/postgres", conn_max_age=600
    )
}

and

SECRET_KEY = os.environ.get("MY SECRET KEY")

Issue #517 doesn't work and I have already PATH.
[https://github.com/mirumee/saleor/issues/517#issuecomment-202768642](url)

Best wishes!
Nikita

PYTHON MANAGE.PY MIGRATE
And i see this in terminal:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 63, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/checks/database.py", line 9, in check_database_backends
    for conn in connections.all():
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/db/utils.py", line 222, in all
    return [self[alias] for alias in self]
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/db/utils.py", line 219, in __iter__
    return iter(self.databases)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/conf/__init__.py", line 161, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
(danafamed-TfFNHDqU-py3.8) n1k1ta@n3p:~/Документы/DEV/saleor/danafamed.shop$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 63, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/core/checks/database.py", line 9, in check_database_backends
    for conn in connections.all():
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/db/utils.py", line 222, in all
    return [self[alias] for alias in self]
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/db/utils.py", line 219, in __iter__
    return iter(self.databases)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/n1k1ta/.cache/pypoetry/virtualenvs/danafamed-TfFNHDqU-py3.8/lib/python3.8/site-packages/django/conf/__init__.py", line 161, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by NyanKiyoshi** [comment]
Hi, whether you set the `SECRET_KEY` by exporting `SECRET_KEY='something'` or remove `SECRET_KEY = os.environ.get('your key')` to `SECRET_KEY = 'your key'`

**Comment by NIKITAdotONE** [comment]
I did this:
1) Add SECRET_KEY to /root/.profile
    export SECRET_KEY='15+n96&r%)n47of%6f(5#mjh2y)syma#n^1+=qp+3larhra=vn'

2) Reboot server and notice that SECRET_KEY is already added successfully.
    [root@localhost ~]# echo $SECRET_KEY
       15+n96&r%)n47of%6f(5#mjh2y)syma#n^1+=qp+3larhra=vn
3) Add SECRET_KEY to settings.py
    SECRET_KEY= '15+n96&r%)n47of%6f(5#mjh2y)syma#n^1+=qp+3larhra=vn'

Sorry i didn't quite understand, I must remove 'os.environ.get' from settings.py in 
SECRET_KEY = os.environ.get("MY SECRET KEY")?

**Comment by NIKITAdotONE** [comment]
Yeah it work!
I remove 'os.environ.get' from settings.py in
SECRET_KEY = os.environ.get("MY SECRET KEY")
