### ISSUE TITLE
frozen importlib._bootstrap

### ISSUE THREAD

**Issue by Coeur-Digital** [mirumee/saleor#5461]
### What I'm trying to achieve
Installation on linux 18.04 LTS

### Steps to reproduce the problem
1. I follow all the instruction from you doc until :
2. 7 Prepare the database

### What I expected to happen
```
(.venv) root@scw-magical-torvalds-sylius:/var/www/saleor# python manage.py migrate
Traceback (most recent call last):
  File "/var/www/saleor/.venv/lib/python3.6/site-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'saleor' has no attribute 'discount'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/saleor/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/var/www/saleor/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/var/www/saleor/.venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/saleor/.venv/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/var/www/saleor/.venv/lib/python3.6/site-packages/django/apps/config.py", line 136, in create
    import_module(entry)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/saleor/saleor/discount/__init__.py", line 1, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
### Screenshots
<!-- If applicable, add screenshots to help explain your problem. -->
```

**System information**
Operating system: linux 18.04 lts

**Comment by Coeur-Digital** [comment]
I fix it by installing dataclasses
