### ISSUE TITLE
unable to install Saleor on A2hosted shared (with Python 3.7.3, Node.js 12.9.0, PostgreSQL  9.6.16)

### ISSUE THREAD

**Issue by onelsonic** [mirumee/saleor#5497]
when installing saleor with this command:
`pip install -r requirements.txt`

The installation failed : 
```
Building wheels for collected packages: uwsgi
  Building wheel for uwsgi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/webroser/virtualenv/envirpit/3.6/bin/python3.6_bin -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d0405479/uwsgi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d0405479/uwsgi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5te9vlal
       cwd: /tmp/pip-install-d0405479/uwsgi/
  Complete output (38 lines):
  /opt/alt/python36/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'descriptions'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying uwsgidecorators.py -> build/lib
  installing to build/bdist.linux-x86_64/wheel
  running install
  using profile: buildconf/default.ini
  detected include path: ['/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include', '/usr/include']
  Patching "bin_name" to properly install_scripts dir
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-d0405479/uwsgi/setup.py", line 138, in <module>
      'Programming Language :: Python :: 3.6',
    File "/home/webroser/virtualenv/envirpit/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/opt/alt/python36/lib64/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/alt/python36/lib64/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/opt/alt/python36/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/webroser/virtualenv/envirpit/3.6/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "/opt/alt/python36/lib64/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/alt/python36/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-d0405479/uwsgi/setup.py", line 79, in run
      uc.build_uwsgi(conf)
    File "/tmp/pip-install-d0405479/uwsgi/uwsgiconfig.py", line 276, in build_uwsgi
      t.start()
    File "/opt/alt/python36/lib64/python3.6/threading.py", line 846, in start
      _start_new_thread(self._bootstrap, ())
  RuntimeError: can't start new thread
  ----------------------------------------
  ERROR: Failed building wheel for uwsgi
  Running setup.py clean for uwsgi
Failed to build uwsgi
Installing collected packages: uwsgi, weasyprint
    Running setup.py install for uwsgi ... error
    ERROR: Command errored out with exit status 1:
     command: /home/webroser/virtualenv/envirpit/3.6/bin/python3.6_bin -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d0405479/uwsgi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d0405479/uwsgi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-i69v16rg/install-record.txt --single-version-externally-managed --compile --install-headers /home/webroser/virtualenv/envirpit/3.6/include/site/python3.6/uwsgi
         cwd: /tmp/pip-install-d0405479/uwsgi/
    Complete output (25 lines):
    /opt/alt/python36/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'descriptions'
      warnings.warn(msg)
    running install
    using profile: buildconf/default.ini
    detected include path: ['/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include', '/usr/include']
    Patching "bin_name" to properly install_scripts dir
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d0405479/uwsgi/setup.py", line 138, in <module>
        'Programming Language :: Python :: 3.6',
      File "/home/webroser/virtualenv/envirpit/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/opt/alt/python36/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/alt/python36/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/alt/python36/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-d0405479/uwsgi/setup.py", line 79, in run
        uc.build_uwsgi(conf)
      File "/tmp/pip-install-d0405479/uwsgi/uwsgiconfig.py", line 276, in build_uwsgi
        t.start()
      File "/opt/alt/python36/lib64/python3.6/threading.py", line 846, in start
        _start_new_thread(self._bootstrap, ())
    RuntimeError: can't start new thread
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/webroser/virtualenv/envirpit/3.6/bin/python3.6_bin -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d0405479/uwsgi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d0405479/uwsgi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-i69v16rg/install-record.txt --single-version-externally-managed --compile --install-headers /home/webroser/virtualenv/envirpit/3.6/include/site/python3.6/uwsgi Check the logs for full command output.
```

**Comment by maarcingebala** [comment]
I haven't seen this error before, seems like related to your environment. Saleor requires Python 3.8, can you upgrade your version and try again?

**Comment by patrys** [comment]
It seems that the shared hosting option of A2hosted limits the number of threads a process can spawn. There is nothing we can do as the problem is not specific to Saleor.

You may be able to progress further by asking https://github.com/unbit/uwsgi developers for help with debugging.
