### ISSUE TITLE
Cannot return null for non-nullable field CreateToken.token.

### ISSUE THREAD

**Issue by elcolie** [mirumee/saleor#5544]
### What I'm trying to achieve
Prepare `saleor` for `storefront`

### Steps to reproduce the problem
1. Checkout `master` commit `9f7e0381159cbdc88ff2a0bfe4fcf1e2e50a1c2e`
2. `migrate`
3. `runserver`

### What I expected to happen
Python console not raises any error

### Screenshots
```
web_1         | ERROR saleor.graphql.errors.handled A query had an error [PID:33:MainThread]
web_1         | Traceback (most recent call last):
web_1         |   File "/usr/local/lib/python3.8/site-packages/promise/promise.py", line 87, in try_catch
web_1         |     return (handler(*args, **kwargs), None)
web_1         |   File "/usr/local/lib/python3.8/site-packages/graphql/execution/executor.py", line 531, in <lambda>
web_1         |     lambda resolved: complete_value(
web_1         |   File "/usr/local/lib/python3.8/site-packages/graphql/execution/executor.py", line 546, in complete_value
web_1         |     return complete_nonnull_value(
web_1         |   File "/usr/local/lib/python3.8/site-packages/graphql/execution/executor.py", line 743, in complete_nonnull_value
web_1         |     raise GraphQLError(
web_1         | graphql.error.base.GraphQLError: Cannot return null for non-nullable field CreateToken.token.
```

**System information**
Operating system: Docker image `python:3.8-slim`

**Comment by maarcingebala** [comment]
I cannot reproduce the error. I'm not sure why you're getting it because the `token` field is nullable in the schema (it would be `token: String!` otherwise):
```
type CreateToken {
  token: String
  accountErrors: [AccountError!]!
  user: User
}
```

Can you go to your local Playground and run the query manually to see if it works?
```
mutation {
  tokenCreate(email: "", password: "") {
    token
    accountErrors {
      field
      code
    }
  }
}
```

**Comment by elcolie** [comment]
@maarcingebala 
```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field CreateToken.token.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "tokenCreate",
        "token"
      ],
      "extensions": {
        "exception": {
          "code": "GraphQLError",
          "stacktrace": [
            "Traceback (most recent call last):",
            "  File \"/usr/local/lib/python3.8/site-packages/promise/promise.py\", line 87, in try_catch",
            "    return (handler(*args, **kwargs), None)",
            "  File \"/usr/local/lib/python3.8/site-packages/graphql/execution/executor.py\", line 531, in <lambda>",
            "    lambda resolved: complete_value(",
            "  File \"/usr/local/lib/python3.8/site-packages/graphql/execution/executor.py\", line 546, in complete_value",
            "    return complete_nonnull_value(",
            "  File \"/usr/local/lib/python3.8/site-packages/graphql/execution/executor.py\", line 743, in complete_nonnull_value",
            "    raise GraphQLError(",
            "graphql.error.base.GraphQLError: Cannot return null for non-nullable field CreateToken.token."
          ]
        }
      }
    }
  ],
  "data": {
    "tokenCreate": null
  }
}
```

**Comment by elcolie** [comment]
Change commit to `606f451877e278b5de542d8fd94f0debbf336ed1`. Problem is gone
