### ISSUE TITLE
DB Migrations fail from 2.9 -> 2.10

### ISSUE THREAD

**Issue by mikesimkin** [mirumee/saleor#5618]
### What I'm trying to achieve
I want to migrate to 2.10 from 2.9. However db migrations fail:

````bash
Running migrations:
  Applying plugins.0001_initial... OK
  Applying plugins.0002_auto_20200417_0335... OK
  Applying product.0110_auto_20191108_0340... OK
  Applying account.0035_staffnotificationrecipient... OK
  Applying account.0036_auto_20191209_0407... OK
  Applying account.0037_auto_20191219_0944... OK
  Applying warehouse.0001_initial... OK
  Applying product.0111_auto_20191209_0437... OK
  Applying product.0112_auto_20200129_0050... OK
  Applying product.0113_auto_20200129_0717... OK
  Applying product.0114_auto_20200129_0815... OK
  Applying product.0115_auto_20200221_0257... OK
  Applying order.0077_auto_20191118_0606... OK
  Applying order.0078_auto_20200221_0257... OK
  Applying checkout.0022_auto_20191219_1137... OK
  Applying checkout.0023_checkout_country... OK
  Applying checkout.0024_auto_20200120_0154... OK
  Applying checkout.0025_auto_20200221_0257... OK
  Applying account.0038_auto_20200123_0034... OK
  Applying account.0039_auto_20200221_0257... OK
  Applying core.0001_migrate_metadata... OK
  Applying account.0040_auto_20200415_0443... OK
  Applying account.0041_permissions_to_groups... OK
  Applying account.0040_auto_20200225_0237... OK
  Applying account.0041_merge_20200421_0529... OK
  Applying account.0042_merge_20200422_0555... OK
  Applying account.0043_rename_service_account_to_app... OK
  Applying webhook.0003_unmount_service_account... OK
  Applying account.0044_unmount_app_and_app_token... OK
  Applying account.0045_auto_20200427_0425... OK
  Applying app.0001_initial... OK
  Applying discount.0019_auto_20200217_0350... OK
  Applying django_prices_openexchangerates.0005_auto_20190124_1008... OK
  Applying giftcard.0003_auto_20200217_0350... OK
  Applying menu.0016_auto_20200217_0350... OK
  Applying warehouse.0002_auto_20200123_0036... OK
  Applying warehouse.0003_warehouse_slug...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 231, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/app/saleor/warehouse/migrations/0003_warehouse_slug.py", line 17, in create_unique_slug_for_warehouses
    first_char = warehouse.name[0].lower()
IndexError: string index out of range
````

### Steps to reproduce the problem
Bring up empty installation of Saleor 2.9 (commit 877e5c285bac9a4b3a35a45063e3451f4bfbad52) and populatedb
1. docker-compose build api
2. docker-compose run --rm api python3 manage.py migrate
3. docker-compose run --rm api python3 manage.py populatedb --createsuperuser
4. Update to 2.10 (commit a1ec77677e1a769ad7995e3163c7c35295c13ed6) and run migrations

### What I expected to happen
Migrations complete successfully.

### Screenshots
**System information**
Operating system:

````bash
docker version                                       
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
````

**Comment by NyanKiyoshi** [comment]
Should be fixed by https://github.com/mirumee/saleor/pull/5611 not yet released though

**Comment by ilanosm** [comment]
Was facing the same issue.
Created a new DB and did migrations and it was successful. 
Though this might be a bug.
