### ISSUE TITLE
TypeError: The loader.load() function must be called with a value,but got: None.

### ISSUE THREAD

**Issue by PiotrLaszczyk** [mirumee/saleor#5639]
### What I'm trying to achieve
Collecting product list

### Steps to reproduce the problem
1. I was using saleor in production 
2. Request that worked for really long time suddenly start to fail after manualy deleting some categories via dashboard.

            query {
                products (first:100) {
                    edges {
                        cursor
                        node {
                            id
                            name
                            variants{
                                id
                                sku
                                quantity
                                trackInventory
                            }
                            category {
                                name
                                id
                            }
                            productType {
                                name
                            }
                            isPublished
                            chargeTaxes
                            taxType {
                                taxCode
                                description
                            }
                            descriptionJson
                            attributes {
                                attribute {
                                    id
                                    name
                                }
                                values {
                                    name
                                    slug
                                }
                            }                            
                        }
                    }
                }
            } 

2020-05-13 22:54:12.901507 :: WebShopGraphQL: exception: response error: {'message': 'The loader.load() function must be called with a value,but got: None.', 'locations': [{'line': 14, 'column': 9}], 'path': ['products', 'edges', 33, 'node', 'category'], 'extensions': {'exception': {'code': 'TypeError', 'stacktrace': ['Traceback (most recent call last):', '  File "/app/.heroku/python/lib/python3.8/site-packages/promise/promise.py", line 489, in _resolve_from_executor', '    executor(resolve, reject)', '  File "/app/.heroku/python/lib/python3.8/site-packages/promise/promise.py", line 756, in executor', '    return resolve(f(*args, **kwargs))', '  File "/app/.heroku/python/lib/python3.8/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise', '    return next(*args, **kwargs)', '  File "./saleor/graphql/product/types/products.py", line 462, in resolve_category', '    return CategoryByIdLoader(info.context).load(root.category_id)', '  File "/app/.heroku/python/lib/python3.8/site-packages/promise/dataloader.py", line 86, in load', '    raise TypeError(', 'TypeError: The loader.load() function must be called with a value,but got: None.']}}}

**System information**
Operating system: heroku / production

**Comment by NyanKiyoshi** [comment]
Seems like it's the same issue as https://github.com/mirumee/saleor/issues/5589

**Comment by NyanKiyoshi** [comment]
Can you try again onto master? It should have been fixed already by #5589

**Comment by PiotrLaszczyk** [comment]
Second funny thing... I erased whole categories from dashboard (to make this working somehow) but then:

2020-05-13 23:20:20.429198 :: WebShopGraphQL: info: query without token
{'products': {'totalCount': 0}}
2020-05-13 23:20:20.428913 :: WebShopGraphQL: info: updating token...
2020-05-13 23:20:20.429034 :: WebShopGraphQL: info: email: ***
2020-05-13 23:20:20.429122 :: WebShopGraphQL: info: password: ****
2020-05-13 23:20:20.429198 :: WebShopGraphQL: info: preparing query for token
2020-05-13 23:20:20.429450 :: WebShopGraphQL: info: executing query for token
2020-05-13 23:20:20.995728 :: WebShopGraphQL: info: token refreshed: token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InNwZWR5dG9yQGlob21lLXN5c3RlbXMucGwiLCJleHAiOjE1ODk0MDUxMjAsIm9yaWdJYXQiOjE1ODk0MDQ4MjAsInVzZXJfaWQiOiJWWE5sY2pveCIsImlzX3N0YWZmIjp0cnVlLCJpc19zdXBlcnVzZXIiOnRydWV9.pNM3koR180ntOkEJDC7JtR***************
2020-05-13 23:20:20.995874 :: WebShopGraphQL: info: updating client...
2020-05-13 23:20:20.995964 :: WebShopGraphQL: info: with token
2020-05-13 23:20:33.325415 :: WebShopGraphQL: info: client updated
2020-05-13 23:20:33.325548 :: WebShopGraphQL: info: autentication checker...
2020-05-13 23:20:20.429198 :: WebShopGraphQL: info: query with token
{'products': {'totalCount': 3819}}

So I have two different number of products with or without token... ;)

**Comment by PiotrLaszczyk** [comment]
Summarizing:

I broke it: I had categories, and products related. I manually (by dasboard) removed categories, products stays ....and this triggered this issue, additionally untokenized query showed 0 products and tokenized showed all products (also thouse with removed categories)

I fixed it by: manually removing (by dashboard) products with broken categories.. 

Any way, removing category should remove products... there is even such message:
"Are you sure you want to delete this category?
Remember this will also delete all products assigned to this category."

**Comment by maarcingebala** [comment]
The reason why you see more products when passing the token might that then you are authorized to also see unpublished products. Without the token you'll always get only those that are published for anonymous users - customers.

The second issue needs to be fixed - we used to have categories required by products at the DB level. Then, removing a category also removed all the products. Later we changed it, so that category is no longer mandatory for a product. Removing it from the system removes the relationship, but all the products stay in DB. We should either fix the message in UI or remove these products as well.

**Comment by PiotrLaszczyk** [comment]
Just take this under consideration. You dont have it in salor as params are sticked to products but when some automated system evaluates params for newly created products then I look at is category ;). Then consistent filters could be created on category level. This is typical approach... and then You cannot simply move product to different category with its dependencies as it takes its attributes also.. its better to remove and create from beginnig with new ecosystem requirements.
