### ISSUE TITLE
Deploy to Heroku broken

### ISSUE THREAD

**Issue by kilinkis** [mirumee/saleor#5649]
### What I'm trying to achieve
Install on heroku

### Steps to reproduce the problem
1. click the Deploy to Heroku button
2. Fill the fields and launch the deploy

### What I expected to happen
Successful install

This is the build log:

```
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12.x...
       Downloading and installing node 12.16.3...
       Using default npm version: 6.14.4
       
-----> Installing dependencies
       Installing node modules (package.json + package-lock)
       
       > core-js@2.6.11 postinstall /tmp/build_5fc62cb3e09195d25997c353df069971/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       added 223 packages from 180 contributors and audited 223 packages in 6.571s
       
       3 packages are looking for funding
         run `npm fund` for details
       
       found 0 vulnerabilities
       
       
-----> Build
       Running heroku-postbuild
       
       > saleor@0.0.0 heroku-postbuild /tmp/build_5fc62cb3e09195d25997c353df069971
       > npm run build-emails
       
       
       > saleor@0.0.0 build-emails /tmp/build_5fc62cb3e09195d25997c353df069971
       > mjml --config.beautify false -l skip "templates/templated_email/source/*.mjml" -o templates/templated_email/compiled
       
       
-----> Caching build
       - node_modules
       
-----> Pruning devDependencies
       Skipping because NPM_CONFIG_PRODUCTION is 'false'
       
-----> Build succeeded!
-----> Python app detected
 !     Python has released a security update! Please consider upgrading to python-3.8.2
       Learn More: https://devcenter.heroku.com/articles/python-runtimes
-----> Installing python-3.8.0
-----> Installing pip
-----> Installing SQLite3
-----> Installing requirements with pip
       Ignoring python-magic-bin: markers 'sys_platform == "win32"' don't match your environment
       Collecting amqp==2.5.2
         Downloading amqp-2.5.2-py2.py3-none-any.whl (49 kB)
       Collecting aniso8601==7.0.0
         Downloading aniso8601-7.0.0-py2.py3-none-any.whl (42 kB)
       Collecting asgiref==3.2.7
         Downloading asgiref-3.2.7-py2.py3-none-any.whl (19 kB)
       Collecting babel==2.8.0
         Downloading Babel-2.8.0-py2.py3-none-any.whl (8.6 MB)
       Collecting beautifulsoup4==4.7.1
         Downloading beautifulsoup4-4.7.1-py3-none-any.whl (94 kB)
       Collecting billiard==3.6.3.0
         Downloading billiard-3.6.3.0-py3-none-any.whl (89 kB)
       Collecting boto3==1.13.7
         Downloading boto3-1.13.7-py2.py3-none-any.whl (128 kB)
       Collecting botocore==1.16.7
         Downloading botocore-1.16.7-py2.py3-none-any.whl (6.2 MB)
       Collecting braintree==3.49.0
         Downloading braintree-3.49.0-py2.py3-none-any.whl (122 kB)
       Collecting cachetools==4.1.0
         Downloading cachetools-4.1.0-py3-none-any.whl (10 kB)
       Collecting cairocffi==1.1.0
         Downloading cairocffi-1.1.0.tar.gz (68 kB)
         WARNING: Requested cairocffi==1.1.0 from https://files.pythonhosted.org/packages/f7/99/b3a2c6393563ccbe081ffcceb359ec27a6227792c5169604c1bd8128031a/cairocffi-1.1.0.tar.gz#sha256=f1c0c5878f74ac9ccb5d48b2601fcc75390c881ce476e79f4cfedd288b1b05db (from -r /tmp/build_5fc62cb3e09195d25997c353df069971/requirements.txt (line 11)), but installing version file-.cairocffi-VERSION
       Collecting cairosvg==2.4.2
         Downloading CairoSVG-2.4.2-py3-none-any.whl (50 kB)
       Collecting celery==4.4.2
         Downloading celery-4.4.2-py2.py3-none-any.whl (422 kB)
       Collecting certifi==2020.4.5.1
         Downloading certifi-2020.4.5.1-py2.py3-none-any.whl (157 kB)
       Collecting cffi==1.14.0
         Downloading cffi-1.14.0-cp38-cp38-manylinux1_x86_64.whl (409 kB)
       Collecting chardet==3.0.4
         Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
       Collecting cssselect2==0.3.0
         Downloading cssselect2-0.3.0-py3-none-any.whl (31 kB)
       Collecting defusedxml==0.6.0
         Downloading defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
       Collecting dj-database-url==0.5.0
         Downloading dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
       Collecting dj-email-url==1.0.0
         Downloading dj_email_url-1.0.0-py2.py3-none-any.whl (9.8 kB)
       Collecting django==3.0.6
         Downloading Django-3.0.6-py3-none-any.whl (7.5 MB)
       Collecting django-appconf==1.0.4
         Downloading django_appconf-1.0.4-py2.py3-none-any.whl (6.3 kB)
       Collecting django-cache-url==3.1.2
         Downloading django_cache_url-3.1.2-py2.py3-none-any.whl (4.3 kB)
       Collecting django-countries==6.1.2
         Downloading django_countries-6.1.2-py3-none-any.whl (791 kB)
       Collecting django-filter==2.2.0
         Downloading django_filter-2.2.0-py3-none-any.whl (69 kB)
       Collecting django-graphql-jwt==0.3.0
         Downloading django_graphql_jwt-0.3.0-py2.py3-none-any.whl (40 kB)
       Collecting django-js-asset==1.2.2
         Downloading django_js_asset-1.2.2-py2.py3-none-any.whl (5.8 kB)
       Collecting django-measurement==3.2.3
         Downloading django_measurement-3.2.3-py2.py3-none-any.whl (7.2 kB)
       Collecting django-mptt==0.11.0
         Downloading django_mptt-0.11.0-py2.py3-none-any.whl (109 kB)
       Collecting django-phonenumber-field==4.0.0
         Downloading django_phonenumber_field-4.0.0-py3-none-any.whl (51 kB)
       Collecting django-prices==2.2.0
         Downloading django_prices-2.2.0-py3-none-any.whl (10 kB)
       Collecting django-prices-openexchangerates==1.1.0
         Downloading django_prices_openexchangerates-1.1.0-py3-none-any.whl (22 kB)
       Collecting django-prices-vatlayer==1.1.0
         Downloading django_prices_vatlayer-1.1.0-py3-none-any.whl (7.8 kB)
       Collecting django-render-block==0.6
         Downloading django_render_block-0.6-py2.py3-none-any.whl (10 kB)
       Collecting django-storages==1.9.1
         Downloading django_storages-1.9.1-py2.py3-none-any.whl (42 kB)
       Collecting django-templated-email==2.3.0
         Downloading django-templated-email-2.3.0.tar.gz (18 kB)
       Collecting django-versatileimagefield==2.0
         Downloading django_versatileimagefield-2.0-py2.py3-none-any.whl (53 kB)
       Collecting docutils==0.15.2
         Downloading docutils-0.15.2-py3-none-any.whl (547 kB)
       Collecting draftjs-sanitizer==1.0.0
         Downloading draftjs-sanitizer-1.0.0.tar.gz (6.1 kB)
       Collecting enmerkar==0.7.1
         Downloading enmerkar-0.7.1-py3-none-any.whl (12 kB)
       Collecting faker==4.0.3
         Downloading Faker-4.0.3-py3-none-any.whl (1.0 MB)
       Collecting freezegun==0.3.15
         Downloading freezegun-0.3.15-py2.py3-none-any.whl (14 kB)
       Collecting google-api-core==1.17.0
         Downloading google_api_core-1.17.0-py2.py3-none-any.whl (70 kB)
       Collecting google-auth==1.14.3
         Downloading google_auth-1.14.3-py2.py3-none-any.whl (89 kB)
       Collecting google-cloud-core==1.3.0
         Downloading google_cloud_core-1.3.0-py2.py3-none-any.whl (26 kB)
       Collecting google-cloud-storage==1.28.1
         Downloading google_cloud_storage-1.28.1-py2.py3-none-any.whl (80 kB)
       Collecting google-i18n-address==2.3.5
         Downloading google_i18n_address-2.3.5-py2.py3-none-any.whl (773 kB)
       Collecting google-measurement-protocol==1.0.0
         Downloading google-measurement-protocol-1.0.0.tar.gz (2.8 kB)
       Collecting google-resumable-media==0.5.0
         Downloading google_resumable_media-0.5.0-py2.py3-none-any.whl (38 kB)
       Collecting googleapis-common-protos==1.51.0
         Downloading googleapis-common-protos-1.51.0.tar.gz (35 kB)
       Collecting graphene==2.1.8
         Downloading graphene-2.1.8-py2.py3-none-any.whl (107 kB)
       Collecting graphene-django==2.10.0
         Downloading graphene_django-2.10.0-py2.py3-none-any.whl (72 kB)
       Collecting graphene-federation==0.1.0
         Downloading graphene-federation-0.1.0.tar.gz (21.1 MB)
       Collecting graphql-core==2.3.1
         Downloading graphql_core-2.3.1-py2.py3-none-any.whl (251 kB)
       Collecting graphql-relay==2.0.1
         Downloading graphql_relay-2.0.1-py3-none-any.whl (20 kB)
       Collecting html-to-draftjs==1.0.1
         Downloading html-to-draftjs-1.0.1.tar.gz (6.7 kB)
       Collecting html5lib==1.0.1
         Downloading html5lib-1.0.1-py2.py3-none-any.whl (117 kB)
       Collecting idna==2.9
         Downloading idna-2.9-py2.py3-none-any.whl (58 kB)
       Collecting jaeger-client==4.3.0
         Downloading jaeger-client-4.3.0.tar.gz (81 kB)
       Collecting jmespath==0.9.5
         Downloading jmespath-0.9.5-py2.py3-none-any.whl (24 kB)
       Collecting jsonfield==3.1.0
         Downloading jsonfield-3.1.0-py3-none-any.whl (8.0 kB)
       Collecting kombu==4.6.8
         Downloading kombu-4.6.8-py2.py3-none-any.whl (183 kB)
       Collecting lxml==4.5.0
         Downloading lxml-4.5.0-cp38-cp38-manylinux1_x86_64.whl (5.6 MB)
       Collecting markdown==3.2.2
         Downloading Markdown-3.2.2-py3-none-any.whl (88 kB)
       Collecting maxminddb==1.5.4
         Downloading maxminddb-1.5.4.tar.gz (282 kB)
       Collecting maxminddb-geolite2==2018.703
         Downloading maxminddb-geolite2-2018.703.tar.gz (26.1 MB)
       Collecting measurement==3.2.0
         Downloading measurement-3.2.0.tar.gz (12 kB)
       Collecting mpmath==1.1.0
         Downloading mpmath-1.1.0.tar.gz (512 kB)
       Collecting oauthlib==3.1.0
         Downloading oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
       Collecting opentracing==2.3.0
         Downloading opentracing-2.3.0.tar.gz (48 kB)
       Collecting phonenumberslite==8.12.3
         Downloading phonenumberslite-8.12.3-py2.py3-none-any.whl (448 kB)
       Collecting pillow==7.1.2
         Downloading Pillow-7.1.2-cp38-cp38-manylinux1_x86_64.whl (2.1 MB)
       Collecting prices==1.0.0
         Downloading prices-1.0.0.tar.gz (6.0 kB)
       Collecting promise==2.3
         Downloading promise-2.3.tar.gz (19 kB)
       Collecting protobuf==3.11.3
         Downloading protobuf-3.11.3-cp38-cp38-manylinux1_x86_64.whl (1.3 MB)
       Collecting psycopg2-binary==2.8.5
         Downloading psycopg2_binary-2.8.5-cp38-cp38-manylinux1_x86_64.whl (3.0 MB)
       Collecting purl==1.5
         Downloading purl-1.5-py2.py3-none-any.whl (10 kB)
       Collecting pyasn1==0.4.8
         Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
       Collecting pyasn1-modules==0.2.8
         Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
       Collecting pycparser==2.20
         Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
       Collecting pyjwt==1.7.1
         Downloading PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
       Collecting pyphen==0.9.5
         Downloading Pyphen-0.9.5-py2.py3-none-any.whl (3.0 MB)
       Collecting python-dateutil==2.8.1
         Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
       Collecting python-magic==0.4.18
         Downloading python_magic-0.4.18-py2.py3-none-any.whl (8.6 kB)
       Collecting pytz==2020.1
         Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
       Collecting razorpay==1.2.0
         Downloading razorpay-1.2.0-py3-none-any.whl (162 kB)
       Collecting redis==3.5.1
         Downloading redis-3.5.1-py2.py3-none-any.whl (71 kB)
       Collecting requests==2.23.0
         Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
       Collecting rsa==4.0
         Downloading rsa-4.0-py2.py3-none-any.whl (38 kB)
       Collecting rx==1.6.1
         Downloading Rx-1.6.1-py2.py3-none-any.whl (179 kB)
       Collecting s3transfer==0.3.3
         Downloading s3transfer-0.3.3-py2.py3-none-any.whl (69 kB)
       Collecting sentry-sdk==0.14.3
         Downloading sentry_sdk-0.14.3-py2.py3-none-any.whl (103 kB)
       Collecting singledispatch==3.4.0.3
         Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl (12 kB)
       Collecting six==1.14.0
         Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
       Collecting soupsieve==2.0
         Downloading soupsieve-2.0-py2.py3-none-any.whl (32 kB)
       Collecting sqlparse==0.3.1
         Downloading sqlparse-0.3.1-py2.py3-none-any.whl (40 kB)
       Collecting stripe==2.48.0
         Downloading stripe-2.48.0-py2.py3-none-any.whl (203 kB)
       Collecting sympy==1.5.1
         Downloading sympy-1.5.1-py2.py3-none-any.whl (5.6 MB)
       Collecting text-unidecode==1.3
         Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
       Collecting threadloop==1.0.2
         Downloading threadloop-1.0.2.tar.gz (4.9 kB)
       Collecting thrift==0.13.0
         Downloading thrift-0.13.0.tar.gz (59 kB)
       Collecting tinycss2==1.0.2
         Downloading tinycss2-1.0.2-py3-none-any.whl (61 kB)
       Collecting tornado==6.0.4
         Downloading tornado-6.0.4.tar.gz (496 kB)
       Collecting tqdm==4.46.0
         Downloading tqdm-4.46.0-py2.py3-none-any.whl (63 kB)
       Collecting typing==3.7.4.1
         Downloading typing-3.7.4.1-py3-none-any.whl (25 kB)
       Collecting urllib3==1.25.9
         Downloading urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
       Collecting uwsgi==2.0.18
         Downloading uwsgi-2.0.18.tar.gz (801 kB)
       Collecting vine==1.3.0
         Downloading vine-1.3.0-py2.py3-none-any.whl (14 kB)
       Collecting weasyprint==51
         Downloading WeasyPrint-51-py3-none-any.whl (359 kB)
       Collecting webencodings==0.5.1
         Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
       Collecting setuptools>=39.2.0
         Downloading setuptools-46.3.0-py3-none-any.whl (582 kB)
       Building wheels for collected packages: cairocffi, django-templated-email, draftjs-sanitizer, google-measurement-protocol, googleapis-common-protos, graphene-federation, html-to-draftjs, jaeger-client, maxminddb, maxminddb-geolite2, measurement, mpmath, opentracing, prices, promise, threadloop, thrift, tornado, uwsgi
         Building wheel for cairocffi (setup.py): started
         Building wheel for cairocffi (setup.py): finished with status 'done'
         Created wheel for cairocffi: filename=cairocffi-file_.cairocffi_VERSION-py3-none-any.whl size=88788 sha256=09fd8fdb4d3bac70271796ff8fc4f911746fa3bb34e09cd27b1d5e1cb19ead17
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/71/c7/16/0cd3bf6e08dae3bd2edeb3e731447c4864559f55bc1a15f7e1
         Building wheel for django-templated-email (setup.py): started
         Building wheel for django-templated-email (setup.py): finished with status 'done'
         Created wheel for django-templated-email: filename=django_templated_email-2.3.0-py3-none-any.whl size=15589 sha256=ee74e34ddc61733b21fce8c32c87a9e5b30038676f9b43967d07a1e8ff3b7641
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/c7/4e/a6/6cbc1a540ac7a9be854265fa7c3663054458402f79537cdc3a
         Building wheel for draftjs-sanitizer (setup.py): started
         Building wheel for draftjs-sanitizer (setup.py): finished with status 'done'
         Created wheel for draftjs-sanitizer: filename=draftjs_sanitizer-1.0.0-py3-none-any.whl size=6330 sha256=3b775949fba331acd816883f3c1a11c7ed4c4cd016865aa122c8f7a967f7bb38
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/e9/66/54/953ef8d90939be2d777e3df46bab64f3d2ffa33329f9ba5d94
         Building wheel for google-measurement-protocol (setup.py): started
         Building wheel for google-measurement-protocol (setup.py): finished with status 'done'
         Created wheel for google-measurement-protocol: filename=google_measurement_protocol-1.0.0-py3-none-any.whl size=4959 sha256=0e9cb97ef48ad427fcfd5c6dae020b12e2c4f14bdc14950ef2b4bb9414a37640
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/6b/32/f2/074ac7c96409c9adc0550e625a17b2da1e8fe2c01c36d89198
         Building wheel for googleapis-common-protos (setup.py): started
         Building wheel for googleapis-common-protos (setup.py): finished with status 'done'
         Created wheel for googleapis-common-protos: filename=googleapis_common_protos-1.51.0-py3-none-any.whl size=77592 sha256=5e982a2fbd59471fc78d7908af579655d0a8b1571f45b3c42b40347cf11f49cd
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/0d/81/d7/c82ed88e8977ef82d567716c51defc3fd8775c78fa5c4efc7b
         Building wheel for graphene-federation (setup.py): started
         Building wheel for graphene-federation (setup.py): finished with status 'done'
         Created wheel for graphene-federation: filename=graphene_federation-0.1.0-py3-none-any.whl size=7744 sha256=b7434f3e59ff7c849d233751cdbd24f6818a41cf8d64eba5152b7c5604cac31f
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/e1/a4/b9/158ff081822af4d28647110aa09ccaabe99fd878fd45b02e5f
         Building wheel for html-to-draftjs (setup.py): started
         Building wheel for html-to-draftjs (setup.py): finished with status 'done'
         Created wheel for html-to-draftjs: filename=html_to_draftjs-1.0.1-py3-none-any.whl size=6618 sha256=4f649559c84dc1e11bbfe0a7809f1e11029afeaf6947794d009ca8a9a62d51fa
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/16/9f/08/f731dd4b799883541bb6664dd766412e5cc869603ab63847b4
         Building wheel for jaeger-client (setup.py): started
         Building wheel for jaeger-client (setup.py): finished with status 'done'
         Created wheel for jaeger-client: filename=jaeger_client-4.3.0-py3-none-any.whl size=64291 sha256=4a34c259085a4035eee47d0353f4ba576a049a1b207e4fb9aee46e78d6a338ba
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/ef/67/cc/1e96fd3ac7a245e8115eb2fe99f57a01699127e0ee212e4e1d
         Building wheel for maxminddb (setup.py): started
         Building wheel for maxminddb (setup.py): finished with status 'done'
         Created wheel for maxminddb: filename=maxminddb-1.5.4-py3-none-any.whl size=14867 sha256=c3ad9bed4b2294e30438d07a5b872d434bb0e051d4567a8cff5a6ca729fde184
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/a7/11/8e/613147a683234875ef661d65011614cf46bcccf9fee7ab1a79
         Building wheel for maxminddb-geolite2 (setup.py): started
         Building wheel for maxminddb-geolite2 (setup.py): finished with status 'done'
         Created wheel for maxminddb-geolite2: filename=maxminddb_geolite2-2018.703-py3-none-any.whl size=26407039 sha256=90aa0ff24f4cd2257525884eb866be091c89e28befa099fd2c3f895d3d4e49e4
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/d6/5d/09/77fbfeb20a1ca58c39bfc6dcef685ab61f069e1b0dc6d971df
         Building wheel for measurement (setup.py): started
         Building wheel for measurement (setup.py): finished with status 'done'
         Created wheel for measurement: filename=measurement-3.2.0-py2.py3-none-any.whl size=17364 sha256=085d39e27c62e74e1e120d8619ceb8c994fe21496d3dd51246aa7847b2921054
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/b2/9e/af/812244644f94fc6a5fee5d40ac430e3c6f4c65d4467949cf55
         Building wheel for mpmath (setup.py): started
         Building wheel for mpmath (setup.py): finished with status 'done'
         Created wheel for mpmath: filename=mpmath-1.1.0-py3-none-any.whl size=532239 sha256=0df0c0af1b303f4144c26c22916e7783ad1d85143c7301bd7ca8dd0bd23ed641
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/29/2c/1c/d2e4580cde2743b0aef389e936ac21a2db92921ddbca53faa1
         Building wheel for opentracing (setup.py): started
         Building wheel for opentracing (setup.py): finished with status 'done'
         Created wheel for opentracing: filename=opentracing-2.3.0-py3-none-any.whl size=51347 sha256=d7bf32ecb83c7fd4acd320696bf05a881ae48fac692cd602150df069152e21ea
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/d8/59/32/28a68fc65ba428fce889c46994767b2e4d000ee81e2ae47512
         Building wheel for prices (setup.py): started
         Building wheel for prices (setup.py): finished with status 'done'
         Created wheel for prices: filename=prices-1.0.0-py3-none-any.whl size=8816 sha256=00bdd875cde7de3a90a813b4d207cc6ddab6ca1ddcf591a64b80ee2838a1f6cf
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/00/56/89/3f4a31d5ff8e4c791ecf86ca2b7900da45f2028598d82c55d4
         Building wheel for promise (setup.py): started
         Building wheel for promise (setup.py): finished with status 'done'
         Created wheel for promise: filename=promise-2.3-py3-none-any.whl size=21495 sha256=2eb313edaa52767c55dfe9e099e3e3255906908efafa1c02aa541e42f54cc20e
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/54/aa/01/724885182f93150035a2a91bce34a12877e8067a97baaf5dc8
         Building wheel for threadloop (setup.py): started
         Building wheel for threadloop (setup.py): finished with status 'done'
         Created wheel for threadloop: filename=threadloop-1.0.2-py3-none-any.whl size=3423 sha256=713f1cf74d432dcb90cb0d0b5394473109f84733405aabbd0890d1be85e7b379
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/45/b4/e0/10a61e44f3381ae9f0454997f045d5695d92399e5e498380d4
         Building wheel for thrift (setup.py): started
         Building wheel for thrift (setup.py): finished with status 'done'
         Created wheel for thrift: filename=thrift-0.13.0-cp38-cp38-linux_x86_64.whl size=424099 sha256=3ff3e1805b4a464b216d67339494d1198d6bdef7293639ca330d1b5c255a942a
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/0a/52/7e/8054b57725b8f2b9ddbaacb81b271b939681cc03f8231e6ebc
         Building wheel for tornado (setup.py): started
         Building wheel for tornado (setup.py): finished with status 'done'
         Created wheel for tornado: filename=tornado-6.0.4-cp38-cp38-linux_x86_64.whl size=427534 sha256=9e8d24629136aeb1a722cbc7ccbc6e92a072110fa83120cd54fa6461915a2514
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/88/79/e5/598ba17e85eccf2626eab62e4ee8452895636cd542650d450d
         Building wheel for uwsgi (setup.py): started
         Building wheel for uwsgi (setup.py): finished with status 'done'
         Created wheel for uwsgi: filename=uWSGI-2.0.18-cp38-cp38-linux_x86_64.whl size=6459700 sha256=75b8a16f24e2ab807262ef36af6ecc51605bd5314d642fa94ec107905f21d020
         Stored in directory: /tmp/pip-ephem-wheel-cache-4j2ejn0e/wheels/48/07/77/7996e2077b5ab7ee02928e2338a970e18091bac789c62932c1
       Successfully built cairocffi django-templated-email draftjs-sanitizer google-measurement-protocol googleapis-common-protos graphene-federation html-to-draftjs jaeger-client maxminddb maxminddb-geolite2 measurement mpmath opentracing prices promise threadloop thrift tornado uwsgi
       ERROR: weasyprint 51 has requirement cairocffi>=0.9.0, but you'll have cairocffi file-.cairocffi-VERSION which is incompatible.
       Installing collected packages: vine, amqp, aniso8601, asgiref, pytz, babel, soupsieve, beautifulsoup4, billiard, six, python-dateutil, urllib3, docutils, jmespath, botocore, s3transfer, boto3, idna, chardet, certifi, requests, braintree, cachetools, pycparser, cffi, setuptools, cairocffi, webencodings, tinycss2, cssselect2, defusedxml, pillow, cairosvg, kombu, celery, dj-database-url, dj-email-url, sqlparse, django, django-appconf, django-cache-url, django-countries, django-filter, pyjwt, promise, rx, graphql-core, singledispatch, graphql-relay, graphene, graphene-django, django-graphql-jwt, django-js-asset, mpmath, sympy, measurement, django-measurement, django-mptt, django-phonenumber-field, enmerkar, typing, prices, django-prices, django-prices-openexchangerates, jsonfield, django-prices-vatlayer, django-render-block, django-storages, django-templated-email, python-magic, django-versatileimagefield, draftjs-sanitizer, text-unidecode, faker, freezegun, protobuf, googleapis-common-protos, pyasn1, rsa, pyasn1-modules, google-auth, google-api-core, google-cloud-core, google-resumable-media, google-cloud-storage, google-i18n-address, google-measurement-protocol, graphene-federation, lxml, html-to-draftjs, html5lib, tornado, threadloop, thrift, opentracing, jaeger-client, markdown, maxminddb, maxminddb-geolite2, oauthlib, phonenumberslite, psycopg2-binary, purl, pyphen, razorpay, redis, sentry-sdk, stripe, tqdm, uwsgi, weasyprint
         Attempting uninstall: setuptools
           Found existing installation: setuptools 39.0.1
           Uninstalling setuptools-39.0.1:
             Successfully uninstalled setuptools-39.0.1
       Successfully installed amqp-2.5.2 aniso8601-7.0.0 asgiref-3.2.7 babel-2.8.0 beautifulsoup4-4.7.1 billiard-3.6.3.0 boto3-1.13.7 botocore-1.16.7 braintree-3.49.0 cachetools-4.1.0 cairocffi-file-.cairocffi-VERSION cairosvg-2.4.2 celery-4.4.2 certifi-2020.4.5.1 cffi-1.14.0 chardet-3.0.4 cssselect2-0.3.0 defusedxml-0.6.0 dj-database-url-0.5.0 dj-email-url-1.0.0 django-3.0.6 django-appconf-1.0.4 django-cache-url-3.1.2 django-countries-6.1.2 django-filter-2.2.0 django-graphql-jwt-0.3.0 django-js-asset-1.2.2 django-measurement-3.2.3 django-mptt-0.11.0 django-phonenumber-field-4.0.0 django-prices-2.2.0 django-prices-openexchangerates-1.1.0 django-prices-vatlayer-1.1.0 django-render-block-0.6 django-storages-1.9.1 django-templated-email-2.3.0 django-versatileimagefield-2.0 docutils-0.15.2 draftjs-sanitizer-1.0.0 enmerkar-0.7.1 faker-4.0.3 freezegun-0.3.15 google-api-core-1.17.0 google-auth-1.14.3 google-cloud-core-1.3.0 google-cloud-storage-1.28.1 google-i18n-address-2.3.5 google-measurement-protocol-1.0.0 google-resumable-media-0.5.0 googleapis-common-protos-1.51.0 graphene-2.1.8 graphene-django-2.10.0 graphene-federation-0.1.0 graphql-core-2.3.1 graphql-relay-2.0.1 html-to-draftjs-1.0.1 html5lib-1.0.1 idna-2.9 jaeger-client-4.3.0 jmespath-0.9.5 jsonfield-3.1.0 kombu-4.6.8 lxml-4.5.0 markdown-3.2.2 maxminddb-1.5.4 maxminddb-geolite2-2018.703 measurement-3.2.0 mpmath-1.1.0 oauthlib-3.1.0 opentracing-2.3.0 phonenumberslite-8.12.3 pillow-7.1.2 prices-1.0.0 promise-2.3 protobuf-3.11.3 psycopg2-binary-2.8.5 purl-1.5 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.20 pyjwt-1.7.1 pyphen-0.9.5 python-dateutil-2.8.1 python-magic-0.4.18 pytz-2020.1 razorpay-1.2.0 redis-3.5.1 requests-2.23.0 rsa-4.0 rx-1.6.1 s3transfer-0.3.3 sentry-sdk-0.14.3 setuptools-46.3.0 singledispatch-3.4.0.3 six-1.14.0 soupsieve-2.0 sqlparse-0.3.1 stripe-2.48.0 sympy-1.5.1 text-unidecode-1.3 threadloop-1.0.2 thrift-0.13.0 tinycss2-1.0.2 tornado-6.0.4 tqdm-4.46.0 typing-3.7.4.1 urllib3-1.25.9 uwsgi-2.0.18 vine-1.3.0 weasyprint-51 webencodings-0.5.1
-----> $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 224, in fetch_command
           app_name = commands[subcommand]
       KeyError: 'collectstatic'
       During handling of the above exception, another exception occurred:
       Traceback (most recent call last):
         File "manage.py", line 10, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 231, in fetch_command
           settings.INSTALLED_APPS
         File "/app/.heroku/python/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
           self._setup(name)
         File "/app/.heroku/python/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
           self._wrapped = Settings(settings_module)
         File "/app/.heroku/python/lib/python3.8/site-packages/django/conf/__init__.py", line 142, in __init__
           mod = importlib.import_module(self.SETTINGS_MODULE)
         File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
         File "<frozen importlib._bootstrap>", line 991, in _find_and_load
         File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
         File "<frozen importlib._bootstrap_external>", line 783, in exec_module
         File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
         File "/tmp/build_5fc62cb3e09195d25997c353df069971/saleor/settings.py", line 55, in <module>
           raise ImproperlyConfigured(
       django.core.exceptions.ImproperlyConfigured: ALLOWED_CLIENT_HOSTS environment variable must be set when DEBUG=False.
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by NyanKiyoshi** [comment]
`ALLOWED_CLIENT_HOSTS` is missing in https://github.com/mirumee/saleor/blob/0935d4e6e251fad97213f11311bc2a2150e3efd9/app.json

**Comment by maarcingebala** [comment]
I would say we should change the default configuration to not deploy with `DEBUG=False` setting. First of all this feature of Saleor is used to try out so it's more likely that you want to use the app in debug mode. Switching to production usually requires more actions and you should do it deliberately.

I also don't know what value for `ALLOWED_CLIENT_HOSTS` should we suggest in the `app.json` file - it should be rather set by the user in the Heroku admin panel. But if we want to do that, we can always set `*` as the default.
