### ISSUE TITLE
InvalidCacheBackendError, ModuleNotFoundError: No module named 'django_redis'

### ISSUE THREAD

**Issue by akarsh1995** [mirumee/saleor#5864]
### What I'm trying to achieve
Upload the first product image in dashboard.

### Steps to reproduce the problem
1. CELERY_BROKER_URL settings should point to correct broker redis in heroku config vars.
2. Try uploading an image file for a product keeping eye on the celery logs. (used storefront)

### What I expected to happen
InvalidCacheBackendError
Redis: Missing default cache backenddjango_redis.cache.RedisCache as default cache backend setting.

```
2020-07-11T08:58:23.218205+00:00 app[celeryworker.1]: Traceback (most recent call last):
2020-07-11T08:58:23.218206+00:00 app[celeryworker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/core/cache/__init__.py", line 50, in _create_cache
2020-07-11T08:58:23.218207+00:00 app[celeryworker.1]: backend_cls = import_string(backend)
2020-07-11T08:58:23.218207+00:00 app[celeryworker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string
2020-07-11T08:58:23.218207+00:00 app[celeryworker.1]: module = import_module(module_path)
2020-07-11T08:58:23.218208+00:00 app[celeryworker.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-07-11T08:58:23.218209+00:00 app[celeryworker.1]: return _bootstrap._gcd_import(name[level:], package, level)
2020-07-11T08:58:23.218209+00:00 app[celeryworker.1]: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-07-11T08:58:23.218210+00:00 app[celeryworker.1]: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-07-11T08:58:23.218210+00:00 app[celeryworker.1]: File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
2020-07-11T08:58:23.218211+00:00 app[celeryworker.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-07-11T08:58:23.218211+00:00 app[celeryworker.1]: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-07-11T08:58:23.218212+00:00 app[celeryworker.1]: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-07-11T08:58:23.218212+00:00 app[celeryworker.1]: File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2020-07-11T08:58:23.218213+00:00 app[celeryworker.1]: ModuleNotFoundError: No module named 'django_redis'
2020-07-11T08:58:23.218213+00:00 app[celeryworker.1]: 
2020-07-11T08:58:23.218214+00:00 app[celeryworker.1]: During handling of the above exception, another exception occurred:
2020-07-11T08:58:23.218214+00:00 app[celeryworker.1]: 
2020-07-11T08:58:23.218215+00:00 app[celeryworker.1]: Traceback (most recent call last):
2020-07-11T08:58:23.218216+00:00 app[celeryworker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/versatileimagefield/image_warmer.py", line 114, in _prewarm_versatileimagefield
2020-07-11T08:58:23.218216+00:00 app[celeryworker.1]: url = get_url_from_image_key(versatileimagefieldfile, size_key)
2020-07-11T08:58:23.218216+00:00 app[celeryworker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/versatileimagefield/utils.py", line 196, in get_url_from_image_key
2020-07-11T08:58:23.218217+00:00 app[celeryworker.1]: img_url = img_url[size_key].url
2020-07-11T08:58:23.218217+00:00 app[celeryworker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/versatileimagefield/datastructures/sizedimage.py", line 132, in __getitem__
2020-07-11T08:58:23.218217+00:00 app[celeryworker.1]: if cache.get(resized_url) and resized_url is not None:
2020-07-11T08:58:23.218218+00:00 app[celeryworker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/core/cache/__init__.py", line 98, in __getattr__
2020-07-11T08:58:23.218218+00:00 app[celeryworker.1]: return getattr(caches[DEFAULT_CACHE_ALIAS], name)
2020-07-11T08:58:23.218219+00:00 app[celeryworker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/core/cache/__init__.py", line 79, in __getitem__
2020-07-11T08:58:23.218219+00:00 app[celeryworker.1]: cache = _create_cache(alias)
2020-07-11T08:58:23.218220+00:00 app[celeryworker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/core/cache/__init__.py", line 52, in _create_cache
2020-07-11T08:58:23.218220+00:00 app[celeryworker.1]: raise InvalidCacheBackendError(
2020-07-11T08:58:23.218229+00:00 app[celeryworker.1]: django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django_redis.cache.RedisCache': No module named 'django_redis'
2020-07-11T08:58:23.220467+00:00 app[celeryworker.1]: [2020-07-11 03:58:23,220: ERROR/ForkPoolWorker-1] Thumbnail generation failed
```

### Screenshots

**System information**
```
Celery report: software -> celery:4.4.2 (cliffs) kombu:4.6.8 py:3.8.0
            billiard:3.6.3.0 redis:3.5.1
platform -> system:Linux arch:64bit, ELF
            kernel version:4.4.0-1073-aws imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:redis results:disabled
```

Operating system: `Linux 5026f0cc-1ac6-4c35-aea7-5a0ffac1a0f6 4.4.0-1073-aws #77-Ubuntu SMP Fri Jun 5 17:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by amitosh1995** [comment]
I am also stuck with the same issue. Product Image shows on the product detail page but thumnails are not being generated and hence only placeholder is used. 

anywhere thumbnails are used, it just shows placeholder images everywhere in the cart and homepage.
but in product detail page it shows actual image.

i think the problem is with thumbnail generation somewhere. i have tried python manage.py create_thumbnails command as well . but it also fails

**Comment by maarcingebala** [comment]
@akarsh1995 @amitosh1995 What version of Saleor are you running?

**Comment by akarsh1995** [comment]
> @akarsh1995 @amitosh1995 What version of Saleor are you running?

Saleor core 2.10.1

Thereafter I installed django-redis to fix the bug... 

Fortunately it worked @maarcingebala
