### ISSUE TITLE
Warehouse migration failing

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor#5865]
### What I'm trying to achieve
Trying to upgrade an existing version 2.9 instance to 2.10.

Result:
```
Applying warehouse.0001_initial...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.CheckViolation: new row for relation "warehouse_stock" violates check constraint "warehouse_stock_quantity_allocated_check"
DETAIL:  Failing row contains (2, -388, -389, 5, 2e37c6cf-6902-4944-8393-1cb5a0956cfb).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 231, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/app/saleor/warehouse/migrations/0001_initial.py", line 49, in forward
    Stock.objects.bulk_create(stocks)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 492, in bulk_create
    returned_columns = self._batched_insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1220, in _batched_insert
    inserted_columns = self._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1391, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: new row for relation "warehouse_stock" violates check constraint "warehouse_stock_quantity_allocated_check"
DETAIL:  Failing row contains (2, -388, -389, 5, 2e37c6cf-6902-4944-8393-1cb5a0956cfb).

```

### Steps to reproduce the problem
1. 
2. 

### What I expected to happen
I want the DB migrate command to finish successfully.

### Screenshots

**System information**
Operating system:

**Comment by fowczarek** [comment]
In this migration, we implement warehouses in the saleor.  Each variant has stock in the warehouse. Stock contains fields: `(id, quantity, quantity_allocated, product_variant, warehouse)`. `quantity` and `quantity_allocated` are `PositiveIntegerField` and it can contain only values greater or equals 0. Your saleor instance `quantity` and `quantity_allocated` are negative.

**Comment by JannikZed** [comment]
You are right! We had a strange product variant with a large negative quantity. I downgrade again, removed the variant and could successfully upgrade our instance. Thank you :)
