### ISSUE TITLE
Unable to docker-compose OSX.

### ISSUE THREAD

**Issue by RayLuxembourg** [mirumee/saleor#6317]
Followed the instructions and got this
```
db uses an image, skipping
redis uses an image, skipping
jaeger uses an image, skipping
mailhog uses an image, skipping
Building storefront
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 302, in build
  File "compose/project.py", line 468, in build
  File "compose/project.py", line 450, in build_service
  File "compose/service.py", line 1125, in build
  File "site-packages/docker/api/build.py", line 261, in build
  File "site-packages/docker/api/build.py", line 308, in _set_auth_headers
  File "site-packages/docker/auth.py", line 311, in get_all_credentials
  File "site-packages/docker/auth.py", line 262, in _resolve_authconfig_credstore
  File "site-packages/docker/auth.py", line 287, in _get_store_instance
  File "site-packages/docker/credentials/store.py", line 25, in __init__
docker.credentials.errors.InitializationError: docker-credential-gcloud not installed or not available in PATH
[47794] Failed to execute script docker-compose
```

**Comment by RayLuxembourg** [comment]
fixed by ```Docker Go to Troubleshoot -> Reset to factory defaults```
