### ISSUE TITLE
Sale matching query does not exist

### ISSUE THREAD

**Issue by LeOndaz** [mirumee/saleor#6403]
Well, I've created a discount "Sale" and I pressed the first save after I typed in all the needed data (name, type, dates). after that the form which takes the discount value appeared, I didn't save, I got out then tried to delete it. I was testing to see if it works with the 0 value, It didn't get saved in the first place, since it didn't get saved, how does it persist (if it does) ?
```
Traceback (most recent call last):
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/celery/app/trace.py", line 409, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/leondaz/crime_scene/core/saleor/product/tasks.py", line 63, in update_products_minimal_variant_prices_of_discount_task
    discount = Sale.objects.get(pk=discount_pk)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
saleor.discount.models.Sale.DoesNotExist: Sale matching query does not exist.
```

**Comment by LeOndaz** [comment]
not stsale
