### ISSUE TITLE
pricing always returns null in 3.0.0-a.0

### ISSUE THREAD

**Issue by LeOndaz** [mirumee/saleor#6538]

**Comment by LeOndaz** [comment]
hmm I think the pricing now exists only on variants? Well, I field is still of the product itself and this made some confusion

**Comment by LeOndaz** [comment]
any news about this?

**Comment by LeOndaz** [comment]
Pricing on variants also return null

**Comment by maarcingebala** [comment]
If you're fetching products as an admin user, you need to explicitly provide the `channel` parameter which is required to fetch pricing info. When querying the API as a customer you would get an error message when the channel is not provided or a default channel would be used (if there is only one in the system).

**Comment by LeOndaz** [comment]
I understand, I've my default channel included as a variable, I get the products in the response and pricing info is always null, no matter
```
{
  "data": {
    "products": {
      "edges": [
        {
          "node": {
            "id": "UHJvZHVjdDox",
            "name": "Samsung note 20",
            "slug": "samsung-note-20",
            "descriptionJson": "{\"time\": 1607852091982, \"blocks\": [{\"data\": {\"text\": \"Powered by a <b>nice </b>chip, not a potato chip, just a nice chip\"}, \"type\": \"paragraph\"}], \"version\": \"2.19.0\"}",
            "seoTitle": "",
            "seoDescription": "",
            "pricing": null,
            "images": [
              {
                "id": "UHJvZHVjdEltYWdlOjE=",
                "alt": "",
                "url": "http://localhost:8000/media/products/n2.jpg"
              }
            ],
            "isAvailable": null,
            "isAvailableForPurchase": null,
            "weight": null,
            "attributes": [
              {
                "attribute": {
                  "id": "QXR0cmlidXRlOjE=",
                  "slug": "badges",
                  "name": "Badges"
                },
                "values": [
                  {
                    "id": "QXR0cmlidXRlVmFsdWU6MQ==",
                    "slug": "hot",
                    "name": "Hot"
                  }
                ]
              },
              {
                "attribute": {
                  "id": "QXR0cmlidXRlOjU=",
                  "slug": "tags",
                  "name": "Tags"
                },
                "values": [
                  {
                    "id": "QXR0cmlidXRlVmFsdWU6NQ==",
                    "slug": "2k20",
                    "name": "2k20"
                  },
                  {
                    "id": "QXR0cmlidXRlVmFsdWU6Ng==",
                    "slug": "samsung",
                    "name": "SAMSUNG"
                  },
                  {
                    "id": "QXR0cmlidXRlVmFsdWU6Nw==",
                    "slug": "top-phones",
                    "name": "TOP PHONES"
                  }
                ]
              }
            ],
            "variants": [
              {
                "id": "UHJvZHVjdFZhcmlhbnQ6MQ==",
                "sku": "SAMNOTE20-8123",
                "name": "",
                "pricing": null,
                "attributes": []
              }
            ],
            "defaultVariant": {
              "sku": "SAMNOTE20-8123",
              "attributes": []
            },
            "productType": {
              "slug": "smartphone",
              "name": "Smartphone"
            },
            "category": {
              "id": "Q2F0ZWdvcnk6MQ==",
              "name": "Smartphone",
              "slug": "smartphone",
              "level": 0,
              "description": "",
              "seoTitle": "",
              "seoDescription": ""
            }
          },
          "cursor": "WyJzYW1zdW5nLW5vdGUtMjAiXQ=="
        }
      ],
      "pageInfo": {
        "startCursor": "WyJzYW1zdW5nLW5vdGUtMjAiXQ==",
        "endCursor": "WyJzYW1zdW5nLW5vdGUtMjAiXQ==",
        "hasNextPage": false,
        "hasPreviousPage": false
      },
      "totalCount": 1
    }
  }
}
```

**Comment by maarcingebala** [comment]
Can you share the query?

**Comment by LeOndaz** [comment]
Fragments used
```
fragment productVariantDetails on ProductVariant {
  id
  sku
  name
  pricing {
    price {
      net {
        amount
      }
      gross {
        amount
      }
    }
    priceUndiscounted {
      net {
        amount
      }
      gross {
        amount
      }
    }
    onSale
    discount {
      gross {
        amount
      }
      net {
        amount
      }
    }
  }
  attributes {
    attribute {
      id
      name
    }
    values {
      id
      name
    }
  }
}
fragment categoryDetailFragment on Category {
  id
  name
  slug
  level
  description
  seoTitle
  seoDescription
}

fragment productDetailFragment on Product {
  id
  name
  slug
  descriptionJson
  seoTitle
  seoDescription
  pricing {
    discount {
      gross {
        amount
      }
    }
    priceRange {
      start {
        net {
          amount
        }
      }
    }
  }
  images {
    id
    alt
    url
  }
  isAvailable
  isAvailableForPurchase
  weight {
    unit
    value
  }
  pricing {
    discount {
      gross {
        amount
      }
    }
    onSale
  }

  attributes {
    attribute {
      id
      slug
      name
    }
    values {
      id
      slug
      name
    }
  }
  variants {
    ...productVariantDetails
  }
  defaultVariant {
    sku
    attributes {
      attribute {
        name
        id
      }
      values {
        name
        id
      }
    }
  }
  productType {
    slug
    name
  }
  category {
    ...categoryDetailFragment
  }
}
```
The query
```
query getProductList(
  $first: Int
  $last: Int
  $after: String
  $before: String
  $filter: ProductFilterInput
  $sortBy: ProductOrder
) {
  products(
    first: $first
    last: $last
    after: $after
    before: $before
    filter: $filter
    sortBy: $sortBy
  ) {
    edges {
      node {
        ...productDetailFragment
      }
      cursor
    }
    ...productPageInfoFragment
  }
}
```

Variables
```
{
  "channel": "default",
  "first": 20,
}
```
I tested 
```
  "filter": {"channel": "default", "isPublished": true },
```
Same result

**Comment by maarcingebala** [comment]
`channel` is present in JSON variables but it's not present in the query `getProductList`, you should add it here:
```
query getProductList(
  $first: Int
  $last: Int
  $after: String
  $before: String
  $filter: ProductFilterInput
  $sortBy: ProductOrder
  $channel: String
)
```

**Comment by LeOndaz** [comment]
OH MY GOD, SYMPTOMS OF BRAIN MALFUNCTING, Really sorry about that, anyway, I've figured out something that needs fixing which is, I had 2 variants, one had a price and one did not, I got 
```
Traceback (most recent call last):
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/promise/promise.py", line 87, in try_catch
    return (handler(*args, **kwargs), None)
  File "/home/leondaz/crime_scene/backend/core/saleor/graphql/product/types/products.py", line 609, in calculate_pricing_with_collections
    availability = get_product_availability(
  File "/home/leondaz/crime_scene/backend/core/saleor/product/utils/availability.py", line 150, in get_product_availability
    discounted_net_range = get_product_price_range(
  File "/home/leondaz/crime_scene/backend/core/saleor/product/utils/availability.py", line 116, in get_product_price_range
    prices = [
  File "/home/leondaz/crime_scene/backend/core/saleor/product/utils/availability.py", line 119, in <listcomp>
    variant_channel_listing=variants_channel_listing[i],
graphql.error.located_error.GraphQLLocatedError: list index out of range

Traceback (most recent call last):
  File "/home/leondaz/crime_scene/venv/lib/python3.8/site-packages/promise/promise.py", line 87, in try_catch
    return (handler(*args, **kwargs), None)
  File "/home/leondaz/crime_scene/backend/core/saleor/graphql/product/types/products.py", line 324, in calculate_pricing_with_collections
    availability = get_variant_availability(
  File "/home/leondaz/crime_scene/backend/core/saleor/product/utils/availability.py", line 228, in get_variant_availability
    get_variant_price(
  File "/home/leondaz/crime_scene/backend/core/saleor/product/utils/availability.py", line 98, in get_variant_price
    price=variant_channel_listing.price,
```
which makes sense, I think this case should be handled by saleor when at least a variant of all has no price

**Comment by LeOndaz** [comment]
I'd like to mention that this issue is a big problem for the dashboard aswell, keeps "Saleor has ran into a problem", I should be posting an issue about it there soon

**Comment by maarcingebala** [comment]
We will fix the issue, it should return None and not throw an error.
