### ISSUE TITLE
webpack-bundle.json failed 

### ISSUE THREAD

**Issue by sagoyanfisic** [mirumee/saleor#656]
I'm installing but I have an error generating the site, I followed the installation steps but it still does not work, they could help me please

> Error reading /home/msalinas/Documentos/e-commerce/saleor/webpack-bundle.json. Are you sure webpack has generated the file and the path is correct?

**Comment by patrys** [comment]
It seems you either skipped the `$ npm run build-assets` step or it errored out.

**Comment by sagoyanfisic** [comment]
generate error sgt

> saleor@0.0.0 build-assets /home/msalinas/Documentos/e-commerce/saleor
> UV_THREADPOOL_SIZE=8 node ./node_modules/webpack/bin/webpack.js -p


Error: EACCES, permission denied 'webpack-bundle.json'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.writeFileSync (fs.js:971:15)
    at Plugin.writeOutput (/home/msalinas/Documentos/e-commerce/saleor/node_modules/webpack-bundle-tracker/index.js:89:6)
    at Compiler.<anonymous> (/home/msalinas/Documentos/e-commerce/saleor/node_modules/webpack-bundle-tracker/index.js:39:12)
    at Compiler.applyPlugins (/home/msalinas/Documentos/e-commerce/saleor/node_modules/tapable/lib/Tapable.js:26:37)
    at Compiler.compile (/home/msalinas/Documentos/e-commerce/saleor/node_modules/webpack/lib/Compiler.js:390:7)
    at Compiler.<anonymous> (/home/msalinas/Documentos/e-commerce/saleor/node_modules/webpack/lib/Compiler.js:173:9)
    at Compiler.readRecords (/home/msalinas/Documentos/e-commerce/saleor/node_modules/webpack/lib/Compiler.js:302:10)
    at Compiler.<anonymous> (/home/msalinas/Documentos/e-commerce/saleor/node_modules/webpack/lib/Compiler.js:170:8)
    at Compiler.next (/home/msalinas/Documentos/e-commerce/saleor/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/home/msalinas/Documentos/e-commerce/saleor/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js:23:3)
    at Compiler.next (/home/msalinas/Documentos/e-commerce/saleor/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/home/msalinas/Documentos/e-commerce/saleor/node_modules/webpack/lib/CachePlugin.js:22:58)
    at Compiler.applyPluginsAsync (/home/msalinas/Documentos/e-commerce/saleor/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.run (/home/msalinas/Documentos/e-commerce/saleor/node_modules/webpack/lib/Compiler.js:167:7)
    at processOptions (/home/msalinas/Documentos/e-commerce/saleor/node_modules/webpack/bin/webpack.js:188:12)
    at Object.<anonymous> (/home/msalinas/Documentos/e-commerce/saleor/node_modules/webpack/bin/webpack.js:192:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by patrys** [comment]
It looks like an error specific to your machine, the clue may be in the following line:

>Error: EACCES, permission denied 'webpack-bundle.json'

**Comment by sagoyanfisic** [comment]
> saleor@0.0.0 build-assets /home/msalinas/Documentos/e-commerce/saleor
> UV_THREADPOOL_SIZE=8 node ./node_modules/webpack/bin/webpack.js -p

Hash: 9bc28156eae204269664
Version: webpack 1.13.2
Time: 6853ms
                             Asset     Size  Chunks             Chunk Names
    vendor.c30120592246c5386883.js   126 kB       0  [emitted]  vendor
      cart.d68cb527934abeb9b985.js   213 kB       1  [emitted]  cart
 dashboard.e414fc4a3376a61f13f5.js   295 kB       2  [emitted]  dashboard
storefront.922d6358df5fc38370f6.js  1.08 kB       3  [emitted]  storefront
   [0] multi vendor 52 bytes {0} [built]
    + 195 hidden modules

WARNING in vendor.c30120592246c5386883.js from UglifyJs
Condition always true [./~/jquery/dist/jquery.js:9778,0]
Condition always true [./~/jquery.cookie/jquery.cookie.js:9,0]
Dropping unreachable code [./~/jquery.cookie/jquery.cookie.js:12,2]

WARNING in cart.d68cb527934abeb9b985.js from UglifyJs
Condition always true [./~/react/lib/ReactMount.js:764,0]
Condition always true [./~/react/lib/findDOMNode.js:46,0]
Condition always true [./~/react/lib/instantiateReactComponent.js:80,0]
Dropping unreachable code [./~/react/lib/shouldUpdateReactComponent.js:40,0]
Condition always true [./~/react/lib/traverseAllChildren.js:158,0]
Side effects in initialization of unused variable CartItemAmount [./saleor/static/js/components/cart.js:224,13]
Side effects in initialization of unused variable CartItemSubtotal [./saleor/static/js/components/cart.js:238,13]
Side effects in initialization of unused variable CartTotal [./saleor/static/js/components/cart.js:251,13]
Condition always true [./~/react/lib/ReactDOMComponent.js:907,0]
Dropping side-effect-free statement [./~/react/lib/ReactEventListener.js:72,0]
Dropping unused function handleTopLevelWithPath [./~/react/lib/ReactEventListener.js:98,0]
Dropping unused variable DOCUMENT_FRAGMENT_NODE_TYPE [./~/react/lib/ReactEventListener.js:26,0]

WARNING in dashboard.e414fc4a3376a61f13f5.js from UglifyJs
Side effects in initialization of unused variable $menuToggle [./saleor/static/js/dashboard.js:33,6]
Condition always true [./~/hammerjs/hammer.js:2633,0]
Dropping unreachable code [./~/hammerjs/hammer.js:2637,1]
Condition always true [./~/materialize-css/dist/js/materialize.js:10,0]
Dropping unreachable code [./~/materialize-css/dist/js/materialize.js:14,0]
Condition always true [./~/materialize-css/dist/js/materialize.js:233,3679]
Condition always true [./~/materialize-css/dist/js/materialize.js:236,0]
Dropping unreachable code [./~/materialize-css/dist/js/materialize.js:238,5]
Side effects in initialization of unused variable windowWidth [./~/materialize-css/dist/js/materialize.js:1097,0]
Side effects in initialization of unused variable windowHeight [./~/materialize-css/dist/js/materialize.js:1098,0]
Dropping unused variable count [./~/materialize-css/dist/js/materialize.js:967,0]
Dropping unused variable originalWidth [./~/materialize-css/dist/js/materialize.js:924,0]
Dropping unused variable originalHeight [./~/materialize-css/dist/js/materialize.js:925,0]
Side effects in initialization of unused variable window_width [./~/materialize-css/dist/js/materialize.js:1246,0]
Dropping unused variable timeout [./~/materialize-css/dist/js/materialize.js:1382,0]
Side effects in initialization of unused variable width [./~/materialize-css/dist/js/materialize.js:1735,0]
Side effects in initialization of unused variable direction [./~/materialize-css/dist/js/materialize.js:2227,0]
Side effects in initialization of unused variable y [./~/materialize-css/dist/js/materialize.js:2229,0]
Side effects in initialization of unused variable velocityX [./~/materialize-css/dist/js/materialize.js:2230,0]
Dropping unused variable unique_id [./~/materialize-css/dist/js/materialize.js:2455,0]
Dropping unused variable chips [./~/materialize-css/dist/js/materialize.js:3790,0]
Side effects in initialization of unused variable options [./~/materialize-css/dist/js/materialize.js:3930,0]
Side effects in initialization of unused variable options [./~/materialize-css/dist/js/materialize.js:3976,0]
Dropping unused variable time [./~/materialize-css/dist/js/materialize.js:4163,0]
Condition always true [./~/materialize-css/dist/js/materialize.js:4400,0]
Dropping unreachable code [./~/materialize-css/dist/js/materialize.js:4404,0]
Condition always true [./~/materialize-css/dist/js/materialize.js:5521,0]
Dropping unreachable code [./~/materialize-css/dist/js/materialize.js:5525,0]
Dropping unused variable xTranslation [./~/materialize-css/dist/js/materialize.js:7141,0]
Condition always true [./~/select2/dist/js/select2.js:9,0]
Dropping unreachable code [./~/select2/dist/js/select2.js:12,3]
Side effects in initialization of unused variable $label [./~/select2/dist/js/select2.js:972,0]
Side effects in initialization of unused variable id [./~/select2/dist/js/select2.js:1350,0]
Dropping unused variable self [./~/select2/dist/js/select2.js:1426,0]
Dropping unused variable matches [./~/select2/dist/js/select2.js:3430,0]
Side effects in initialization of unused variable tag [./~/select2/dist/js/select2.js:3608,0]
Side effects in initialization of unused variable instance [./~/select2/dist/js/select2.js:5667,0]
Condition always true [./~/sortablejs/Sortable.js:11,0]
Dropping unreachable code [./~/sortablejs/Sortable.js:14,0]
Side effects in initialization of unused variable slice [./~/sortablejs/Sortable.js:71,0]
Condition always true [./~/underscore/underscore.js:48,0]
Dropping unreachable code [./~/underscore/underscore.js:54,0]
Condition always true [./~/underscore/underscore.js:1543,0]

ERROR in ./saleor/static/scss/cart.scss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss/lib/lazy-result.js:237:31)
    at LazyResult.then (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss/lib/lazy-result.js:141:21)
    at Object.module.exports (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss-loader/index.js:93:10)
 @ ./saleor/static/js/cart.js 23:0-28

ERROR in ./saleor/static/scss/storefront.scss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss/lib/lazy-result.js:237:31)
    at LazyResult.then (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss/lib/lazy-result.js:141:21)
    at Object.module.exports (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss-loader/index.js:93:10)
 @ ./saleor/static/js/storefront.js 11:0-34

ERROR in ./saleor/static/scss/dashboard.scss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss/lib/lazy-result.js:237:31)
    at LazyResult.then (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss/lib/lazy-result.js:141:21)
    at Object.module.exports (/home/msalinas/Documentos/e-commerce/saleor/node_modules/postcss-loader/index.js:93:10)
 @ ./saleor/static/js/dashboard.js 19:0-33

**Comment by patrys** [comment]
Which version of node/npm are you running? Did you use `npm install` or a tool like `yarn`?

**Comment by sagoyanfisic** [comment]
npm -> 1.3.10
node -> v0.10.25

**Comment by patrys** [comment]
Umm, the docs specify that you need Node version 4+ 😉
