### ISSUE TITLE
`Cannot determine path without bucket name` error in collectstatic when using gcloud storage

### ISSUE THREAD

**Issue by axelrtgs** [mirumee/saleor#6651]
In order to prevent the error below from appearing i needed to add `GS_BUCKET_NAME = GS_STORAGE_BUCKET_NAME` in the elif condition for gs storage:
https://github.com/mirumee/saleor/blob/06aee553592a606ed04cf3792c02f7cb34d7afe6/saleor/settings.py#L413-L427

here is the error this fixes:
```
Traceback (most recent call last):
 File "manage.py", line 10, in <module>
   execute_from_command_line(sys.argv)
 File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
   utility.execute()
 File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
   self.fetch_command(subcommand).run_from_argv(self.argv)
 File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
   self.execute(*args, **cmd_options)
 File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
   output = self.handle(*args, **options)
 File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 194, in handle
   collected = self.collect()
 File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 118, in collect
   handler(path, prefixed_path, storage)
 File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 345, in copy_file
   if not self.delete_file(path, prefixed_path, source_storage):
 File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 255, in delete_file
   if self.storage.exists(prefixed_path):
 File "/usr/local/lib/python3.8/site-packages/storages/backends/gcloud.py", line 175, in exists
   return bool(self.bucket.get_blob(name))
 File "/usr/local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1105, in get_blob
   blob.reload(
 File "/usr/local/lib/python3.8/site-packages/google/cloud/storage/_helpers.py", line 205, in reload
   path=self.path,
 File "/usr/local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 282, in path
   return self.path_helper(self.bucket.path, self.name)
 File "/usr/local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1014, in path
   raise ValueError("Cannot determine path without bucket name.")
ValueError: Cannot determine path without bucket name.
```

i tried adding `GS_BUCKET_NAME` to my env but it did not solve the issue although this previous issue seems to suggest it was working at some point https://github.com/mirumee/saleor/issues/5222#issuecomment-581760039

I am not sure if theres a better way to fix it but this seems to be a viable workaround.

**Comment by thematz1** [comment]
I've added the GS_BUCKET_NAME at this point and rebuild with docker-compose build --no-cache. In addition, I pruned images to make space. I moved to the elif as described since I had it in the global namespace above (under GS_AUTO_CREATE_BUCKET). It seems that the API and Worker need staggered deployments in order to access saleor-media as it is readwriteone and fails. From there the log stream indicated bucket failure. This is the reason for matching the described solution, rebuilding --no-cache, pushing new images, and attempting again.


# Google Cloud Storage configuration
GS_PROJECT_ID = os.environ.get("GS_PROJECT_ID")
GS_STORAGE_BUCKET_NAME = os.environ.get("GS_STORAGE_BUCKET_NAME")
GS_MEDIA_BUCKET_NAME = os.environ.get("GS_MEDIA_BUCKET_NAME")
GS_AUTO_CREATE_BUCKET = get_bool_from_env("GS_AUTO_CREATE_BUCKET", False)


# If GOOGLE_APPLICATION_CREDENTIALS is set there is no need to load OAuth token
# See https://django-storages.readthedocs.io/en/latest/backends/gcloud.html
if "GOOGLE_APPLICATION_CREDENTIALS" not in os.environ:
    GS_CREDENTIALS = os.environ.get("GS_CREDENTIALS")

if AWS_STORAGE_BUCKET_NAME:
    STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
elif GS_STORAGE_BUCKET_NAME:
    STATICFILES_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
    GS_BUCKET_NAME = GS_STORAGE_BUCKET_NAME

**Comment by unicast** [comment]
Had the same problem, adding `GS_BUCKET_NAME = GS_STORAGE_BUCKET_NAME` as suggested above solved it. Thank you!
