### ISSUE TITLE
AttributeError: module 'saleor' has no attribute 'attribute'

### ISSUE THREAD

**Issue by thewhiterabbit** [mirumee/saleor#6732]
### What I'm trying to achieve
Production installation

### Steps to reproduce the problem
1. python3 manage.py collectstatic

```
localhost:~/saleor$ python3 manage.py collectstatic
Traceback (most recent call last):
  File "/home/nuzyweb/saleor/lib/python3.8/site-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'saleor' has no attribute 'attribute'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nuzyweb/saleor/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/nuzyweb/saleor/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/nuzyweb/saleor/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nuzyweb/saleor/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/nuzyweb/saleor/lib/python3.8/site-packages/django/apps/config.py", line 136, in create
    import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'saleor.attribute'
```

### What I expected to happen
… XXX static files copied to 'project/static'

**System information**
Operating system:
Ubuntu 20.04
nginx/1.18.0

**Comment by maarcingebala** [comment]
`saleor.attribute` is an app that contains attribute-related models and it's been added to Saleor recently (the code was in Saleor before, we just refactored it into a separate app). I can't reproduce this issue so maybe it's a problem with your loal version. Have you tried removing your `*.pyc` files and trying again?

**Comment by thewhiterabbit** [comment]
I discovered that I needed to download this repo, not the saleor-platform repo via git to avoid the error. Also I discovered that I don't build the requirements.txt myself, I use the existing in this repo.

Thank you for your response. I appreciate it very much.
