### ISSUE TITLE
Plugin with path: saleor.plugins.webhook.plugin.WebhookPlugin doesn't exist

### ISSUE THREAD

**Issue by arycloud** [mirumee/saleor#6823]
### What I'm trying to achieve
Run Saleor lcoally.

### Steps to reproduce the problem
1. Download the source code, extract the zip, and set up a Virtual environment with Python 3.8
2. Install all the dependencies in `requirements.txt` and others
3. Define ENV variables as per requirement
4. Run `python manage.py runserver` within the virtual environment

### What I expected to happen
It should work with the `WebHookPlugin`

If I remove  `"saleor.plugins.webhook.plugin.WebhookPlugin",` from plugins in `settings.py`, it works but when I add it it returns this error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/<USER>/PycharmProjects/saleor-2.11.1/venv/lib/python3.9/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/<USER>/PycharmProjects/saleor-2.11.1/venv/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/Users/<USER>/PycharmProjects/saleor-2.11.1/venv/lib/python3.9/site-packages/django/core/management/base.py", line 442, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: Plugin with path: saleor.plugins.webhook.plugin.WebhookPlugin doesn't exist
```

**System information**
Operating system: MacOS Big Sur

**Comment by krzysztofwolski** [comment]
> Download the source code, extract the zip, and set up a Virtual environment with Python 3.8
Python 3.9 is required
