### ISSUE TITLE
Error when installing 

### ISSUE THREAD

**Issue by lyfung** [mirumee/saleor#6849]
### What I'm trying to achieve
Hi, I m trying to install the saleor core
I had installed the python dependencies and the postgres,
created account for saleor
when I run ``python manage.py migrate``

the below error occurs

``/home/ubuntu/codes/backend/saleor/saleor/urls.py:35: UserWarning: The debug toolbar was not installed. Ignore the error. settings.py should already have warned the user about it.
warnings.warn(
Operations to perform:
Apply all migrations: account, app, auth, checkout, contenttypes, core, csv, discount, django_prices_openexchangerates, django_prices_vatlayer, giftcard, invoice, menu, order, page, payment, plugins, product, shipping, site, sites, warehouse, webhook, wishlist
Running migrations:
Applying product.0130_create_product_description_search_vector...Traceback (most recent call last):
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
return self.cursor.execute(sql)
psycopg2.errors.SyntaxError: syntax error at or near "FUNCTION"
LINE 18: ... ON product_product FOR EACH ROW EXECUTE FUNCTION m...
^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "manage.py", line 10, in <module>
executefromcommandline(sys.argv)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/core/management/init.py", line 401, in executefrom_command_line
utility.execute()
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/core/management/\_init.py", line 395, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
self.execute(args, **cmd_options)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
output = self.handle(args, options)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
res = handle_func(*args, kwargs)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 243, in handle
post_migrate_state = executor.migrate(
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
state = migration.apply(state, schema_editor)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 105, in database_forwards
self._run_sql(schema_editor, self.sql)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 130, in _run_sql
schema_editor.execute(statement, params=None)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 142, in execute
cursor.execute(sql, params)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
return super().execute(sql, params)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
return executor(sql, params, many, context)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit_
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/home/ubuntu/codes/backend/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
return self.cursor.execute(sql)
django.db.utils.ProgrammingError: syntax error at or near "FUNCTION"
LINE 18: ... ON product_product FOR EACH ROW EXECUTE FUNCTION m...
^``

Please HELP!

**System information**
Operating system: ubuntu 18.04

**Comment by bastianhilton** [comment]
i'm having this same issue, please help

**Comment by keanesf** [comment]
I am running into the same issue as well

**Comment by Mjackmoor** [comment]
I have too the same problem .. have you maybe it solved?

**Comment by damir-bajramovic** [comment]
I'm having the same issue. If someone has a solution - it would be really helpful.

**Comment by D1ll1ng** [comment]
Same issue here. Can we open this again?

**Comment by D1ll1ng** [comment]
> I'm having the same issue. If someone has a solution - it would be really helpful.

Did you find a solution ?

**Comment by D1ll1ng** [comment]
> I have too the same problem .. have you maybe it solved?

Did you find a solution?

**Comment by Mjackmoor** [comment]
The problem is with the database .. you should use the same version from pql depends on your saleor release and recreate the db again .. that's was the solution for me .. much luck

**Comment by keanesf** [comment]
Agree, I upgraded my database to PostgreSQL 13 and that resolved the error.

**Comment by damir-bajramovic** [comment]
@keanesf Worked like a charm! Thank you! You rock! YOU ROCK! YOU ARE AWESOME! Upgraded from 10 to 13 and it started magically working. You made my Saturday night. 

@Mjackmoor Excuse my ignorance, but what is "pql depends"? I was reading docs and somewhere it said that PostgreSQL 9.4+ version should be used (don't quite remember the number, but the major version was 9, I am pretty sure). I used PostreSQL Docker image 10 - had that issue.

**Comment by tiwiex** [comment]
I noticed i had to follow the instruction in https://github.com/neerajgupta2407/saleor_course_resources/blob/master/setup_saleor_core.txt. I used the saleor version 2.10 and psql 13 and python 3.8.2 in virtualenv. Using saleor 2.11 still gave me the errors. Maybe i did something else differently but I don't think so. Been on it for two days. Haaaaap.
