### ISSUE TITLE
Migrate fails 3.0.0-a11 _migrate_from_draftjs_to_editorjs_format is applied before its dependency

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor#6934]
### What I'm trying to achieve
Upgrade from an existing 3.0.0 to newest 3.0.0-a11.

Error on migrate: 
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 95, in handle
    executor.loader.check_consistent_history(connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 302, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration product.0130_migrate_from_draftjs_to_editorjs_format is applied before its dependency product.0131_update_ts_vector_existing_product_name on database 'default'.
```
### Screenshots

**System information**

Operating system:
Saleor version:

**Comment by d-wysocki** [comment]
Hey, this is known issue caused by difference in migrations between 2.11 and 3.0 to fix this we needed to manually restore history migration. 

If this is local instance, just try to cleardb and setup fresh saleor instance with version 3.11 otherwise you need to follow the steps from below:

1. connect to your db and run 
_this command will fake this 2 migrations that was applied in 2.11_
```
INSERT INTO public.django_migrations(app, name, applied) VALUES ('product','0130_create_product_description_search_vector',now());
INSERT INTO public.django_migrations(app, name, applied) VALUES ('product','0131_update_ts_vector_existing_product_name',now());
```

2. complete django migrations 
```
python manage migrate
```
3. again connect to your db and run
_this command will update existing products with search vector for search purpose_
```
UPDATE product_product
SET search_vector =
setweight(to_tsvector('pg_catalog.english', coalesce(name, '')), 'A') ||
setweight(
to_tsvector('pg_catalog.english', coalesce(description_plaintext, '')), 'B');
```

**Comment by JannikZed** [comment]
okay I see! Well, this is now a staging instance - but I'm thinking of our production instances. Does that mean, that we will need to upgrade them all by hand? Or are you going to improve the migration in the future? The staging instance right now is already version 3, so you would normally not expect a minor version upgrade to fail.

**Comment by JannikZed** [comment]
hey @d-wysocki - I was trying to run your fix, but when running the migration after inserting your DB statements, the migration fails with the following error:
```
  Applying product.0140_auto_20210125_0905... OK
  Applying product.0141_update_descritpion_fields... OK
  Applying product.0142_auto_20210308_1135... OK
  Applying product.0143_rename_product_images_to_product_media...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 173, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'product'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column product_product.description_plaintext does not exist
LINE 1: ...etadata", "product_product"."default_variant_id", "product_p...
```
