### ISSUE TITLE
Saleor 3: omitting channel gives psycopg2.ProgrammingError: can't adapt type 'SimpleLazyObject'

### ISSUE THREAD

**Issue by bufke** [mirumee/saleor#7225]
### What I'm trying to achieve

Attempt the following query in Saleor 3

```
{
  product(slug: "apple-juice") {
    variants {
      quantityAvailable 
    }
  }
}
```

It does not work. However this query does

```
{
  product(slug: "apple-juice" channel:"default-channel") {
    variants {
      quantityAvailable 
    }
  }
}
```

### Steps to reproduce the problem
1. Use latest saleor 3 from git master branch
2. Use sample data
3. Have a default channel that you expect to be used when not specifying a channel
4. Make the query

### What I expected to happen

This should work, because Saleor 3 intends to support not specifying channel. However it doesn't in this case.

### Screenshots and logs

```
api_1         | ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:32:Thread-16]
api_1         | Traceback (most recent call last):
api_1         |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
api_1         |     return self.cursor.execute(sql, params)
api_1         | psycopg2.ProgrammingError: can't adapt type 'SimpleLazyObject'
api_1         | 
api_1         | The above exception was the direct cause of the following exception:
api_1         | 
api_1         | Traceback (most recent call last):
api_1         |   File "/usr/local/lib/python3.9/site-packages/promise/dataloader.py", line 261, in dispatch_queue_batch
api_1         |     batch_promise = loader.batch_load_fn(keys)
api_1         |   File "/app/saleor/graphql/core/dataloaders.py", line 41, in batch_load_fn
api_1         |     results = self.batch_load(keys)
api_1         |   File "/app/saleor/graphql/warehouse/dataloaders.py", line 44, in batch_load
api_1         |     quantities = self.batch_load_country(
api_1         |   File "/app/saleor/graphql/warehouse/dataloaders.py", line 82, in batch_load_country
api_1         |     for variant_id, shipping_zone_id, quantity in results:
api_1         |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 287, in __iter__
api_1         |     self._fetch_all()
api_1         |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1308, in _fetch_all
api_1         |     self._result_cache = list(self._iterable_class(self))
api_1         |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 142, in __iter__
api_1         |     return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
api_1         |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1108, in results_iter
api_1         |     results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
api_1         |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
api_1         |     cursor.execute(sql, params)
api_1         |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
api_1         |     return super().execute(sql, params)
api_1         |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
api_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
api_1         |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
api_1         |     return executor(sql, params, many, context)
api_1         |   File "/app/saleor/graphql/views.py", line 50, in tracing_wrapper
api_1         |     return execute(sql, params, many, context)
api_1         |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
api_1         |     return self.cursor.execute(sql, params)
api_1         |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
api_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
api_1         |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
api_1         |     return self.cursor.execute(sql, params)
api_1         | django.db.utils.ProgrammingError: can't adapt type 'SimpleLazyObject'
api_1         | ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:32:Thread-16]
api_1         | Traceback (most recent call last):
api_1         |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
api_1         |     return self.cursor.execute(sql, params)
api_1         | psycopg2.ProgrammingError: can't adapt type 'SimpleLazyObject'
```

**System information**

Saleor version:
- [x] dev (current master)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [X] Linux
- [ ] MacOS
- [ ] Other

Possibly related to https://github.com/mirumee/saleor/pull/7206

**Comment by bufke** [comment]
Appears fixed in master!
