### ISSUE TITLE
"'Product' object has no attribute 'node'" when extending "Product" on federated schema

### ISSUE THREAD

**Issue by Deni-Iconis** [mirumee/saleor#7410]
### What I'm trying to achieve
I'm trying to use Saleor and local Saleor Reviews App with federated(Ariadne) schema to 'extend' User and Product fields with simple product reviews.

### Steps to reproduce the problem
1. Setup environment:
> Run saleor
> Run minimal federated review implementation: [Gist based on Ariadne example](https://gist.github.com/Deni-Iconis/dfa9d83b6104fd259a7ec632dbbae5bc)
> Run [Graphql Federation Gateway](https://github.com/mirumee/gql-federation-gateway) with `export ENDPOINTS="saleor:http://localhost:8000/graphql/ reviews:http://localhost:3033/reviews"`
2. Run Saleors tokenCreate mutation and use that token for next query: 
3. Run a query:
```
{
  me{
    id
    email
    reviews{
      id
      body
      rating
      product {
        id
        name
      }
      user{
        email
        isActive
      }
    }
  }
}
```

### What I expected to happen
I expect it to return data without errors:
```
{
  "data": {
    "me": {
      "id": "VXNlcjox",
      "email": "admin@example.com",
      "reviews": [
        {
          "id": "1",
          "body": "Love them Apple Juices",
          "rating": 5,
          "product": {
            "id": "UHJvZHVjdDox",
            "name": "test"
          },
          "user": {
            "email": "admin@example.com",
            "isActive": true
          }
        }
      ]
    }
  }
}
```
Instead it return an error "'Product' object has no attribute 'node'".
It happens because "__resolve_reference" @ /saleor/graphql/product/types/products.py line 877 expects "ChannelContext" but receives "models.Product". It looks to me like resolvers aren't handling federated shema well.
If you check for types/attributes in resolvers and return proper id attribute for type(ie. root.id instead of root.node.id) "Product" query on reviews also resolves all fields. 

"User" query on reviews can resolve all its fields without errors. 

I'm relatively new to the whole graphql / relay / federation thing, so it's possible that I'm misunderstanding something and doing something wrong, if so please advise how I coud run an federated app with Saleor and extend it's User and Product schema with external fields. 

Ps. Looks like [graphene-federation](https://github.com/preply/graphene-federation) is unmaintained, there was some [effort to maintain it's fork](https://github.com/loft-orbital/graphene-federation )

PPs. saleor/graphql/core/tests/test_federation.py is testing only "User" query, maybe add a couple more, something like:
```
diff --git a/saleor/graphql/core/tests/test_federation.py b/saleor/graphql/core/tests/test_federation.py
index 693400035..fa1edfc6b 100644
--- a/saleor/graphql/core/tests/test_federation.py
+++ b/saleor/graphql/core/tests/test_federation.py
@@ -14,6 +14,10 @@ def user_representation_by_id(staff_user):
 def user_representation_by_email(staff_user):
     return {"_representations": [{"email": staff_user.email, "__typename": "User"}]}
 
+@pytest.fixture
+def product_representation_by_id(product):
+    product_id = graphene.Node.to_global_id("Product", product.id)
+    return {"_representations": [{"id": product_id, "__typename": "Product"}]}
 
 FEDERATED_QUERY = """
 query($_representations: [_Any!]!) {
@@ -27,6 +31,17 @@ query($_representations: [_Any!]!) {
 }
 """
 
+FEDERATED_QUERY_PRODUCT = """
+query($_representations: [_Any!]!) {
+  _entities(representations: $_representations) {
+    ... on Product {
+      name
+      slug
+    }
+  }
+}
+"""
+
 
 def test_get_user_data_through_federated_query_by_id(
     staff_api_client, user_representation_by_id, staff_user
@@ -48,3 +63,16 @@ def test_get_user_data_through_federated_query_by_email(
     assert len(content) == 1
     assert content[0]["id"] == graphene.Node.to_global_id("User", staff_user.id)
     assert content[0]["isStaff"] == staff_user.is_staff
+
+
+def test_get_product_data_through_federated_query_by_id(
+    staff_api_client, product_representation_by_id, product
+):
+    response = staff_api_client.post_graphql(
+        FEDERATED_QUERY_PRODUCT, product_representation_by_id
+    )
+    content = get_graphql_content(response)["data"]["_entities"]
+    print(content)
+    assert len(content) == 1
+    assert content[0]["name"] == product.name
+    assert content[0]["slug"] == product.slug
```

### Screenshots and logs
```
{
  "errors": [
    {
      "message": "'Product' object has no attribute 'node'",
      "path": [
        "_entities"
      ],
      "extensions": {
        "code": "DOWNSTREAM_SERVICE_ERROR",
        "serviceName": "saleor",
        "query": "query ($representations: [_Any!]!) {\n  _entities(representations: $representations) {\n    ... on Product {\n      name\n    }\n  }\n}",
        "variables": {
          "representations": [
            {
              "__typename": "Product",
              "id": "UHJvZHVjdDox"
            }
          ]
        },
        "exception": {
          "code": "AttributeError",
          "stacktrace": [
            "Traceback (most recent call last):",
            "  File \"/usr/local/lib/python3.9/site-packages/promise/promise.py\", line 489, in _resolve_from_executor",
            "    executor(resolve, reject)",
            "  File \"/usr/local/lib/python3.9/site-packages/promise/promise.py\", line 756, in executor",
            "    return resolve(f(*args, **kwargs))",
            "  File \"/usr/local/lib/python3.9/site-packages/graphql/execution/middleware.py\", line 75, in make_it_promise",
            "    return next(*args, **kwargs)",
            "  File \"/usr/local/lib/python3.9/site-packages/graphene_federation/entity.py\", line 47, in resolve_entities",
            "    model_instance = resolver(model_instance, info)",
            "  File \"/app/saleor/graphql/product/types/products.py\", line 879, in __resolve_reference",
            "    return graphene.Node.get_node_from_global_id(_info, root.node.id)",
            "AttributeError: 'Product' object has no attribute 'node'"
          ]
        }
      }
    },
    {
      "message": "Expected \"data._entities\" in response to be an array",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Expected \"data._entities\" in response to be an array",
            "    at /home/deni/dev/saleor/gql-federation-gateway/node_modules/@apollo/gateway/dist/executeQueryPlan.js:148:23",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/home/deni/dev/saleor/gql-federation-gateway/node_modules/@apollo/gateway/dist/executeQueryPlan.js:5:58)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "me": {
      "id": "VXNlcjox",
      "email": "admin@example.com",
      "reviews": [
        {
          "id": "1",
          "body": "Love them Apple Juices",
          "rating": 5,
          "product": null,
          "user": {
            "email": "admin@example.com",
            "isActive": true
          }
        }
      ]
    }
  }
}
```

**System information**

Saleor version:
- [x] dev (current master)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other

**Comment by rafalp** [comment]
Thanks for reporting and providing code for repro!

I've investigated this and found that indeed current approach for products/variants/collections/ect. where we wrap Django model instances in `ChannelContext` breaks Graphene type model and prevents federated queries from being executed correctly.

We also have other problem where are federation is only resolving those items by ID whereas `{ id channelSlug }` is required instead.

I think I'll have PR with the fix for this tomorrow 👍
