### ISSUE TITLE
ValueError: Port could not be cast to integer value as 

### ISSUE THREAD

**Issue by Megidd** [mirumee/saleor#7741]
### What I'm trying to achieve

Setting `EMAIL_URL` to `smtp://username:password@email-smtp.us-east-1.amazonaws.com:587/?tls=True` where `password` contains slash character of `/`.

Amazon SES is giving me a password which contains `/` character for some reason.

### Steps to reproduce the problem

1. Run
`export EMAIL_URL="smtp://AKIAYZT73XCKGD:BFB6UvkMgn9dniEGQZc/xM/KDS9Agc/S2@email-smtp.us-east-2.amazonaws.com:587/?tls=True"`
2. Then run `python3.9 manage.py runserver`

### What I expected to happen

I expected the API server would run just fine.

### Screenshots and logs

However, I'm receiving this log and error:

```
(saleor-venv) m3@suse15:~/repos/fork/saleor> python3.9 manage.py runserver                                            Traceback (most recent call last):
  File "/home/m3/repos/fork/saleor/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/m3/repos/fork/saleor/saleor-venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/m3/repos/fork/saleor/saleor-venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/home/m3/repos/fork/saleor/saleor-venv/lib64/python3.9/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/m3/repos/fork/saleor/saleor-venv/lib64/python3.9/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/m3/repos/fork/saleor/saleor-venv/lib64/python3.9/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/m3/repos/fork/saleor/saleor/settings.py", line 139, in <module>
    email_config = dj_email_url.parse(
  File "/home/m3/repos/fork/saleor/saleor-venv/lib64/python3.9/site-packages/dj_email_url.py", line 75, in parse
    'EMAIL_PORT': url.port,
  File "/usr/lib64/python3.9/urllib/parse.py", line 175, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as 'BFB6UvkMgn9dniEGQZc'
```

## System information

Saleor version: Git tag `2.11.0` checked out
Saleor storefront: Git tag `2.11.1` checked out
Saleor dashboard: Git tag `2.11.1` checked out

### Operating system

Linux, openSUSE Leap 15.3

**Comment by Megidd** [comment]
# Source file

The error is thrown by line `75` of this file at `saleor-venv/lib/python3.9/site-packages/dj_email_url.py`:

```
# -*- coding: utf-8 -*-

import os
import warnings

import urllib.parse


# Register email schemes in URLs.
urllib.parse.uses_netloc.append('smtp')
urllib.parse.uses_netloc.append('console')
urllib.parse.uses_netloc.append('file')
urllib.parse.uses_netloc.append('memory')
urllib.parse.uses_netloc.append('dummy')


DEFAULT_ENV = 'EMAIL_URL'


SCHEMES = {
    'smtp': 'django.core.mail.backends.smtp.EmailBackend',
    'submission': 'django.core.mail.backends.smtp.EmailBackend',
    'submit': 'django.core.mail.backends.smtp.EmailBackend',
    'smtps': 'django.core.mail.backends.smtp.EmailBackend',  # pend deprecation
    'console': 'django.core.mail.backends.console.EmailBackend',
    'file': 'django.core.mail.backends.filebased.EmailBackend',
    'memory': 'django.core.mail.backends.locmem.EmailBackend',
    'dummy': 'django.core.mail.backends.dummy.EmailBackend'
}


TRUTHY = (
    '1',
    'y', 'Y', 'yes', 'Yes', 'YES',
    't', 'T', 'true', 'True', 'TRUE',
    'on', 'On', 'ON',
)


def unquote(value):
    return urllib.parse.unquote(value) if value else value


def config(env=DEFAULT_ENV, default=None):
    """Returns a dictionary with EMAIL_* settings from EMAIL_URL."""

    conf = {}

    s = os.environ.get(env, default)

    if s:
        conf = parse(s)

    return conf


def parse(url):
    """Parses an email URL."""

    conf = {}

    url = urllib.parse.urlparse(url)
    qs = urllib.parse.parse_qs(url.query)

    # Remove query strings
    path = url.path[1:]
    path = path.split('?', 2)[0]

    # Update with environment configuration
    conf.update({
        'EMAIL_FILE_PATH': path,
        'EMAIL_HOST_USER': unquote(url.username),
        'EMAIL_HOST_PASSWORD': unquote(url.password),
        'EMAIL_HOST': url.hostname,
        'EMAIL_PORT': url.port,
        'EMAIL_USE_SSL': False,
        'EMAIL_USE_TLS': False,
    })

    if url.scheme in SCHEMES:
        conf['EMAIL_BACKEND'] = SCHEMES[url.scheme]

    # Set defaults for `smtp`
    if url.scheme == 'smtp':
        if not conf['EMAIL_HOST']:
            conf['EMAIL_HOST'] = 'localhost'
        if not conf['EMAIL_PORT']:
            conf['EMAIL_PORT'] = 25

    # Set defaults for `smtps`
    if url.scheme == 'smtps':
        warnings.warn(
            "`smtps` scheme will be deprecated in a future version,"
            " use `submission` instead",
            UserWarning,
        )
        conf['EMAIL_USE_TLS'] = True

    # Set defaults for `submission`/`submit`
    if url.scheme in ('submission', 'submit'):
        conf['EMAIL_USE_TLS'] = True
        if not conf['EMAIL_PORT']:
            conf['EMAIL_PORT'] = 587

    # Query args overwrite defaults
    if 'ssl' in qs and qs['ssl']:
        if qs['ssl'][0] in TRUTHY:
            conf['EMAIL_USE_SSL'] = True
            conf['EMAIL_USE_TLS'] = False
    elif 'tls' in qs and qs['tls']:
        if qs['tls'][0] in TRUTHY:
            conf['EMAIL_USE_SSL'] = False
            conf['EMAIL_USE_TLS'] = True

    # From addresses
    if '_server_email' in qs:
        conf['SERVER_EMAIL'] = qs['_server_email'][0]
    if '_default_from_email' in qs:
        conf['DEFAULT_FROM_EMAIL'] = qs['_default_from_email'][0]

    return conf
```

**Comment by Megidd** [comment]
I tried to escape the `/` with `\` but it didn't work...

**Comment by Megidd** [comment]
I replaced `/` character in password with `%2F` when setting environment variable:

```bash
### Replace this:
export EMAIL_URL="smtp://AKIAYZT73XCKGD:BFB6UvkMgn9dniEGQZc/xM/KDS9Agc/S2@email-smtp.us-east-2.amazonaws.com:587/?tls=True"

### With this:
export EMAIL_URL="smtp://AKIAYZT73XCKGD:BFB6UvkMgn9dniEGQZc%2FxM%2FKDS9Agc%2FS2@email-smtp.us-east-2.amazonaws.com:587/?tls=True"
```
Looks like it resolved the error without the need to modify the code! Needs more testing.

**Comment by patrys** [comment]
Your solution is correct. You need to `urlencode` each part of the URL to make sure the username, the password, and so on do not contain any invalid characters.
