### ISSUE TITLE
When migrate for the first time, redis needs a bytes-like object not 'str'

### ISSUE THREAD

**Issue by Rahimz** [mirumee/saleor#8056]
### What I'm trying to achieve
I installed saleor and want to migrate the database

### Steps to reproduce the problem

1. git clone https://github.com/mirumee/saleor-platform.git --recursive --jobs 3
2. cd saleor-platform
3. docker-compose build
4. docker-compose run --rm api python3 manage.py migrate

 when I run `docker-compose run --rm api python3 manage.py migrate`  I got this error that says for redis a bytes-like object is required, not a 'str':
```
Starting saleor-platform_db_1 ... 
Starting saleor-platform_jaeger_1 ... done
Starting saleor-platform_redis_1  ... 

ERROR: for saleor-platform_redis_1  a bytes-like object is required, not 'str'

ERROR: for saleor-platform_db_1  a bytes-like object is required, not 'str'

ERROR: for redis  a bytes-like object is required, not 'str'

ERROR: for db  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/b2af45995c6d0c995c0ef60c20510758de89c0ecc85ae261f12eec85518fb37d/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint saleor-platform_db_1 (3e3649e78633929b6949878b617708e3854015bf507f9909f770f8e3d642f79a): Error starting userland proxy: listen tcp4 0.0.0.0:5432: bind: address already in use'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 896, in run
    run_one_off_container(
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1343, in run_one_off_container
    project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 565, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 548, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 567, in execute_convergence_plan
    return self._execute_convergence_start(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 506, in _execute_convergence_start
    _, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 508, in <lambda>
    lambda c: self.start_container_if_stopped(c, attach_logs=not detached, quiet=True),
  File "/usr/lib/python3/dist-packages/compose/service.py", line 620, in start_container_if_stopped
    return self.start_container(container)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'

```

### What I expected to happen
I expect the migration to be completed and then I could populated the database

### Screenshots and logs

**System information**

I am on Ubuntu 20.04

Saleor version:
- [x] dev (current master)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other

**Comment by akitibala** [comment]
hi @Rahimz , i think according to this line
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint saleor-platform_db_1 (3e3649e78633929b6949878b617708e3854015bf507f9909f770f8e3d642f79a): Error starting userland **proxy: listen tcp4 0.0.0.0:5432: bind: address already in use'**")
_some other db or app using same port as postgres(5432)_.


I think for  db to start the port 5432 should be free

**Comment by Rahimz** [comment]
@akitibala I have postgres.service and redis-server.service running on my Ubuntu, so both of these use ports that cause this server error. After I stooped them the migrations completed.

**Comment by metouitude** [comment]
I suggest for anyone who faces this problem to run sudo netstat -tunlp to detect the LISTENIG ports, then shut down the process/service who is listening on that particular port.
